### ISSUE TITLE
double letterspaced ligatures

### ISSUE THREAD

**Issue by schlcht** [lualatex/luaotfload#106]
Using the `letterspace` font feature, letterspacing within ligatures will be doubled (this does not happen with the `typesetters` function): 

    \input luaotfload.sty
    \tracingoutput 1
    \showboxdepth  10
    \showboxbreadth100
    \font\x = "EB Garamond:mode=node;+liga;+dlig" at 10pt
    {\x\directlua{typesetters.kerns.set(0.2)}
    Thefoofi}

    \font\x = "EB Garamond:mode=node;-liga;letterspace=0.2" at 10pt
    \x Thefoofi

    \font\x = "EB Garamond:mode=node;+liga;letterspace=0.2" at 10pt
    \x Thefoofi

    \font\x = "EB Garamond:mode=node;+liga;+dlig;letterspace=0.2" at 10pt
    \x Thefoofi
    \bye

(BTW: Is there a possibility to _selectively_ disable the breaking of ligatures? I reckon it could somehow be done with the `keeptogether` and/or `keepligatures` functions, but I don't really understand their intended use.)

**Comment by phi-gamma** [comment]
Closing this. @schlcht please reopen if you disagree.
