### ISSUE TITLE
kerning before letterspaced text

### ISSUE THREAD

**Issue by schlcht** [lualatex/luaotfload#107]
If letterspaced text is preceded by non-glue (ie. a character or a kern), the letterspace kerning will also be inserted _before_ the first letterspaced letter. _After_ the text, on the other hand, no kern will be inserted. 

Moreover, the two available letterspacing methods treat a preceding kern differently: `letterspacefont` will add both kerns, while the `typesetters` function will discard the letterspace kern. If I were granted a wish, I would say that letterspacing should insert no kern whatsoever before or after the text. But in any case, I guess it should be consistent.

    \input luaotfload.sty
    \tracingoutput 1
    \showboxdepth  10
    \showboxbreadth100
    \font\z = "EB Garamond:mode=node" at 10pt \z
    \font\x = "EB Garamond:mode=node;letterspace=0.2" at 10pt
    a{\x test}b

    a{\directlua{typesetters.kerns.set(0.2)}test}b

    a\kern1pt{\x test}b

    a\kern1pt{\directlua{typesetters.kerns.set(0.2)}test}b
    \bye

PS. Could you say something on the status of the two letterspacing methods: is one preferable over the other? is one even going to be deprecated? (One more difference I found is that `typesetters` will also alter the interword spacing; not sure whether this should be another issue to be opened...)

**Comment by phi-gamma** [comment]
@schlcht closing due to lack of feedback. Please create a new item
to track further issues.
