### ISSUE TITLE
luaotfload 2.4 doesn't find fonts in $OPENTYPEFONTS-folders by name

### ISSUE THREAD

**Issue by u-fischer** [lualatex/luaotfload#165]
I tested this with the prerelease as miktex hasn't updated yet.
I have some opentype fonts  outside of the texmf trees and the system folder in C:\Program Files (x86)\Adobe\Reader 11.0\Resource\Font.  In miktex this folder is listed in $opentypefonts (I have no idea how miktex does this) and earlier versions of luaotfload did found the fonts. 

The folder is listed when I use diagnose=environment:

     luaotfload | diagnose :       $OPENTYPEFONTS: ".;%Rfonts\\opentype//;C:\\Windows\\Fonts;C:\\Program Files (x86)\\Adobe\\Reader 11.0\\Resource\\Font"

     luaotfload | diagnose :                    +: "C:/Program Files (x86)/Adobe/Reader 11.0/Resource/Font"

Nevertheless the fonts in this folder are not listed in the names database with luaotfload 2.4 and are not found if I call them by name "\setmainfont{MinionProRegular}". Using filenames "\setmainfont{MinionPro-Regular.otf}" works fine. 

I made also some tests on texlive and tried to add a folder "G:\fonttest" to the search path but failed. Neither changing osfontdir nor %opentypefonts seemed to work.

Ulrike Fischer

**Comment by phi-gamma** [comment]
Just pushed a fix for the paths supplied on the command
line. That at least makes a different in the examples above.
On Cygwin using the TL Windows binaries, the following will
now cause the path ``c:/tmp`` to be searched as expected:

    OPENTYPEFONTS=c:/tmp/ luaotfload-tool.exe -uf

Please test whether that helps with the original issue.

**Comment by phi-gamma** [comment]
New release has been uploaded, please retest.

**Comment by phi-gamma** [comment]
Closing this, please reopen if necessary.
