### ISSUE TITLE
Luaotfload ignores OpenType attributes in mathmode

### ISSUE THREAD

**Issue by Hugovdberg** [lualatex/luaotfload#204]
I want to use Calluna as the base font for my documents, and eulervm in mathmode. However, the euler numerals look really ugly with Calluna, while Calluna numerals look rather beautiful with euler. To get this to work I use fontspec to load the fonts, and a bit of magic by egreg@stackexchange to change the numerals to Calluna's Lining,Monospaced numerals, see also http://tex.stackexchange.com/q/165238/46598

This bit of code works perfectly using XeTeX, but LuaLaTeX forgets the +lnum and +tnum attributes as soon as it enters mathmode and uses the default numerals. For most fonts this is fine since they have Lining figures by default, although these are usually proportional, so not ideal but not too wrong. However, Calluna (and EB Garamond, which is more readily available) have oldstyle numerals by default which is not preferable in mathmode. As you can see using the code below the attributes are set just fine by lualatex+fontspec, and using xetex the attributes are respected as well in mathmode, but lualatex will produce the wrong numerals.

``` latex
\documentclass{scrartcl}

\usepackage{amsfonts}
\usepackage{eulervm}
\usepackage{siunitx}

\usepackage[no-math]{fontspec}
\setmainfont[
    Ligatures={Common,TeX},
    Numbers={OldStyle,Proportional},
    ]{EBGaramond12-Regular.otf}
\newfontfamily{\liningmain}[
    Ligatures={Common,TeX},
    Numbers={Lining,Monospaced},
    RawFeature=+tnum,
    ]{EBGaramond12-Regular.otf}
\setsansfont[
    Ligatures={Common,TeX},
    Numbers={Lining,Proportional},
    ]{TeX Gyre Heros}
\setmonofont[
    Ligatures={NoRequired,NoCommon,NoContextual},
    Numbers={Lining,Monospaced},
    ]{TeX Gyre Cursor}

% A trick for extracting the family information
% which works independently of the chosen font
\begingroup
  \def\getfamily#1#2#3#4#5{#4}
  \edef\x{\endgroup
  \def\noexpand\liningdefault{\expandafter\expandafter\expandafter
    \getfamily\csname liningmain \endcsname}}\x

\DeclareSymbolFont{liningmath}{\encodingdefault}{\liningdefault}{m}{n}
\DeclareSymbolFontAlphabet{\mathlining}{liningmath}
\Umathcode`0="7 \symliningmath `0
\Umathcode`1="7 \symliningmath `1
\Umathcode`2="7 \symliningmath `2
\Umathcode`3="7 \symliningmath `3
\Umathcode`4="7 \symliningmath `4
\Umathcode`5="7 \symliningmath `5
\Umathcode`6="7 \symliningmath `6
\Umathcode`7="7 \symliningmath `7
\Umathcode`8="7 \symliningmath `8
\Umathcode`9="7 \symliningmath `9

\sisetup{
    math-rm = \mathlining,
}

\usepackage{polyglossia}
\setmainlanguage[variant=british]{english}

\begin{document}
\section{testing}

\fontname\font -- 0123456789

{\liningmain\fontname\font -- 0123456789}

\begin{tabular}{ll}
\hline
Mode & Result\\
\hline
Text mode & 1234567890\\
Math mode & \(1234567890\)\\
\verb|\SI| text mode & \SI{1042358769}{\metre}\\
\verb|\SI| math mode & \(\SI{1234567890}{\metre}\)\\
\verb|\num| text mode & \num{1234567890}\\
\verb|\num| math mode & \(\num{1234567890}\)\\
verbatim & \verb|1234567890|\\
\hline
\end{tabular}

\end{document}
```

A more concise document, as provided by egreg as well, to see how luatex ignores the font specification is given below, using the font specifications as output in the above code:

``` tex
\input ifxetex.sty

\ifxetex
  \font\test="[EBGaramond12-Regular.otf]/ICU:script=latn;language=DFLT;+liga;mapping=tex-text;+lnum;+tnum;"
\else
  \input luaotfload.sty
  \font\test="[EBGaramond12-Regular.otf]:mode=node;script=latn;language=DFLT;+liga;+tlig;+trep;+lnum;+tnum;"
\fi

\test

1234567890

\textfont0=\test
$1234567890$

\bye
```

**Comment by adunning** [comment]
As it hasn't been mentioned here, it may be worth pointing out that this issue has been deemed responsible for the rather serious problem of OpenType options being ignored in URLs with `\urlstyle{same}`; see <http://tex.stackexchange.com/questions/264206/cant-get-oldstyle-figures-in-url-with-lualatex>.

**Comment by jfbu** [comment]
With some fonts one does not get old style figures in math mode (TeX Gyre Termes), but with others it is the other way around, one does not get lining figures in math mode (Vollkorn).

tested with LuaTeX 0.95 + luaotfload 2.7-fix-1 from TeXLive 2016 pretest April 29, 2016.

Here is with TeX Gyre Termes which comes with TeXLive.

```tex
\input luaotfload.sty
\font\test= {name:TeX-Gyre-Termes:+onum}
\test 0123456789
$\fam0 \textfont0=\test 0123456789$ 
\nopagenumbers
\bye
```

Result:
![capture d ecran 2016-04-29 a 19 20 33](https://cloud.githubusercontent.com/assets/2589111/14934511/76e931fc-0eb2-11e6-8a3a-ada6a3e5604d.png)

But it does work with context:

```tex
\starttext
\font\test= {name:TeX-Gyre-Termes:+onum}
\test 0123456789
$\fam0 \textfont0=\test 0123456789$ 
\stoptext
```

gives
![capture d ecran 2016-04-29 a 21 08 19](https://cloud.githubusercontent.com/assets/2589111/14934529/f8b1fd5e-0eb2-11e6-9964-048257422921.png)

(Copied over from closed issue https://github.com/lualatex/luaotfload/issues/347)

**Comment by phi-gamma** [comment]
···<date: 2016-04-30, Saturday>···<from: Jean-François B.>···

> With some fonts one does not get old style figures in math mode (TeX Gyre Termes), but with others it is the other way around, one does not get lining figures in math mode (Vollkorn).
> 
> tested with LuaTeX 0.95 + luaotfload 2.7-fix-1 from TeXLive 2016 pretest April 29, 2016.
> 
> Here is with TeX Gyre Termes which comes with TeXLive.
> 
> ```tex
> \input luaotfload.sty
> \font\test= {name:TeX-Gyre-Termes:+onum}
> \test 0123456789
> $\fam0 \textfont0=\test 0123456789$ 
> \nopagenumbers
> \bye
> ```
> 
> Result:
> ![capture d ecran 2016-04-29 a 19 20 33](https://cloud.githubusercontent.com/assets/2589111/14934511/76e931fc-0eb2-11e6-8a3a-ada6a3e5604d.png)
> 
> But it does work with context:
> 
> ```tex
> \starttext
> \font\test= {name:TeX-Gyre-Termes:+onum}
> \test 0123456789
> $\fam0 \textfont0=\test 0123456789$ 
> \stoptext
> ```

These examples are not equivalent. Luaotfload enables node mode
and a number of features by default. Also, you don’t define fonts
that way Context.

**Comment by jfbu** [comment]
I don't know the correct way in context. If the correct way in context has the same issue as with Plain LuaTeX+luaotfload, then at least that will indicate where to look. If it does not have the same issue, then I guess it is also indication.

**Comment by yannis1962** [comment]
And here is my minimal example (using luatex, beamer, mathastext and the beautiful Fedra font):

```
\pdfoutput1
\documentclass[9pt]{beamer}
\usepackage[no-math]{fontspec}
\usepackage{luatextra}
\usetheme{AnnArbor}
\usecolortheme{crane}
\usefonttheme{professionalfonts}
\setsansfont[
    Path           = /hom/yannis/texmf/cours/stats/,
    Extension      = .otf,
    Ligatures      = TeX,
    BoldFont       = FedraSerifProABold,
    ItalicFont     = FedraSerifProABookItalic,
    BoldItalicFont = FedraSerifProABoldItalic,
    Numbers        = Lining
]{FedraSerifProABook}
\usepackage[italic]{mathastext}
\begin{document}
\begin{frame}[fragile]
\frametitle{An example of unwanted oldstyle figures in Fedra math}
\Huge

0123456789

$0123456789$

$$0123456789$$

\end{frame}
\end{document}
```
And the result is:
![test](https://cloud.githubusercontent.com/assets/749949/14935028/8ad35ace-0ec3-11e6-82aa-ae958c5b64aa.png)

As you can see, in inline text mode figures are lining, and in display mode they are old style. This makes no sense.

**Comment by jfbu** [comment]
Using `mode=base` does not fix all issues. For example 

    TeXGyreTermes:mode=base;script=latn;language=DFLT;+tlig;+tnum;+onum;

does not have tabular figures, but only old style figures. With `mode=node` it has both.

And if the above is _either_ with `+tnum;` _or_ with `+onum;` it works.

**Comment by jfbu** [comment]
@yannis1962 I will upload today to CTAN a new release of `mathastext` which should solve your issue with `Numbers=Lining`.

**Comment by u-fischer** [comment]
I'm closing this issue. As mentioned in https://mailman.ntg.nl/pipermail/ntg-context/2014/077635.html the proper way to handle this "is to define a font where certain rendering is replaced by another but in the same slot". This (probably) can be done e.g. with `fonts.handlers.otf.addfeature`.  The *num opentype features are for text, not for math.

**Comment by adunning** [comment]
For issues such as the URL problem I [mentioned earlier](https://github.com/lualatex/luaotfload/issues/204#issuecomment-149947715), then, does this need to be resolved elsewhere?

**Comment by u-fischer** [comment]
@adunning imho yes. url's are text. Imho in luatex it should be possible to add break points without resorting to math. 

Be aware that this repo is no longer active. luaotfload development is now at https://github.com/latex3/luaotfload.
