### ISSUE TITLE
segfault with Luatex 0.80.1 and 2014 fontloader

### ISSUE THREAD

**Issue by phi-gamma** [lualatex/luaotfload#271]
There’s a segfault reported by @eroux  when indexing
glyphs. A rebuild of the font cache is needed to trigger
it (thanks Akira for pointing that out), it doesn’t happen
with stale cache files.

**Comment by phi-gamma** [comment]
For incompatibility of the fontloader see also:
http://www.ntg.nl/pipermail/ntg-context/2015/081459.html
The version numbers don’t quite match up but it’s not that
Hans didn’t issue a warning at all ;)

**Comment by phi-gamma** [comment]
@eroux Since the Luatex in TL is 0.80.0 (is it?) with which the segfault
does not occur, I’d opt for closing this issue. Next update will come a bit
later, but it will then be 0.80.1 ready. What do you think?

**Comment by eroux** [comment]
I think it is... let's close!
