### ISSUE TITLE
Loading a PFB font with OFM metrics

### ISSUE THREAD

**Issue by yannis1962** [lualatex/luaotfload#273]
In my ḍād package (for Arabic typesetting, see also the TUGboat paper) I use a PostScript font with OFM metrics file. I load the font in the usual way, going through an FD file. This works only for luaLaTeX, since the latter is the only OFM-compatible TeX offspring (thanks to its Omega genes).

My ḍād font is not loaded anymore when I include the fontspec package. As you can see if you visit this overleaf page, as soon as the fontspec package is loaded, the OFM-PFB font dad cannot be found anymore. This means that a user of ḍād cannot use TrueType fonts in luaLaTeX (at least not going through fontspec, which is the most practical way), and this is quite a pity.

How do I load a PFB font with OFM metrics in a fontspec-compatible way?

On stackoverflow, David Carlisle said that "texdoc luaotfload implies ofm fonts should be loaded so my theory is that changing dad in the fd file to [dad] or [file:dad.ofm] or "file:/usr/local/texlive/2015/texmf-dist/fonts/ofm/public/dad/dad" ought to work, but none of them do.... might be worth raising with the luaotfload maintainers". How do I load my font?

**Comment by eroux** [comment]
Hello Yannis, how are you?

I think you forgot the link to overleaf, this would help tracking the bug. 

I used ofm with luaotfload (and fontspec) without any problem a few years ago (but I haven't tried since Gregorio fonts were converted to ttf), so it should be easy to make it work again. Did you try by just loading luaotfload, without fontspec? The problem might be in fontspec itself (the two projects are more or less independants, and I don't know much about fontspec sadly).

**Comment by yannis1962** [comment]
salut Elie, comment va ? tu vis où actuellement ?

Here is the link to the overleaf project:
https://www.overleaf.com/2832243jnwhcc#/7631244/ <https://www.overleaf.com/2832243jnwhcc#/7631244/>

thanks in advance!

> Le 10 juin 2015 à 07:26, Elie Roux <notifications@github.com> a écrit :
> 
> Hello Yannis, how are you?
> 
> I think you forgot the link to overleaf, this would help tracking the bug.
> 
> I used ofm with luaotfload (and fontspec) without any problem a few years ago (but I haven't tried since Gregorio fonts were converted to ttf), so it should be easy to make it work again. Did you try by just loading luaotfload, without fontspec? The problem might be in fontspec itself (the two projects are more or less independants, and I don't know much about fontspec sadly).
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lualatex/luaotfload/issues/273#issuecomment-110592872>.
> 

-- 
-------------------------------------------------------
Yannis Haralambous
Professor
Institut Mines-Télécom, Télécom Bretagne
Computer Science Department
UMR CNRS 6285 Lab-STICC
Technopôle Brest Iroise
CS 83818, 29238 Brest Cedex 3, France
Email: yannis.haralambous@telecom-bretagne.eu <mailto:yannis.haralambous@telecom-bretagne.eu>
Internet: http://perso.telecom-bretagne.eu/yannisharalambous/ <http://omega.enstb.org/yannis>
ICBM address: 48°21'31.57"N 4°34'16.76"W
Twitter: y_haralambous
-------------------------------------------------------
...the ball I threw while playing in the park
has not yet reached the ground
(Dylan Thomas)

Es gab eine Zeit, wo ich nur ungern über Schubert sprechen,
nur Nächtens den Bäumen und Sternen von ihm vorerzählen mögen.
(Robert Schumann)

**Comment by eroux** [comment]
Ça va ! Je suis au fin fond du Périgord (je bosse à la maison)... Je t'écris un mail dans pas longtemps, ce sera plus simple qu'ici !

@phi-gamma I tried to debug it but it's been a long time I haven't put my nose in the fontloader (the bug seems to be here)... Here's a small example:

    \documentclass{article}
    \usepackage{dad}
    \usepackage{luaotfload}
    \begin{document}
    \Huge\arab{AlkitAbu AlkabYru}
    \Huge\arab{الكتابُ الكبيرُ}
    \end{document}

Tell me if you don't have time for this, I'll have time to debug this by the end of the week

**Comment by yannis1962** [comment]
Ils t’ont répondu ?

> Le 10 juin 2015 à 10:12, Elie Roux <notifications@github.com> a écrit :
> 
> Ça va ! Je suis au fin fond du Périgord (je bosse à la maison)... Je t'écris un mail dans pas longtemps, ce sera plus simple qu'ici !
> 
> @phi-gamma <https://github.com/phi-gamma> I tried to debug it but it's been a long time I haven't put my nose in the fontloader (the bug seems to be here)... Here's a small example:
> 
> \documentclass{article}
> \usepackage{dad}
> \usepackage{luaotfload}
> \begin{document}
> \Huge\arab{AlkitAbu AlkabYru}
> \Huge\arab{الكتابُ الكبيرُ}
> \end{document}
> Tell me if you don't have time for this, I'll have time to debug this by the end of the week
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lualatex/luaotfload/issues/273#issuecomment-110645431>.
> 

-- 
-------------------------------------------------------
Yannis Haralambous
Professor
Institut Mines-Télécom, Télécom Bretagne
Computer Science Department
UMR CNRS 6285 Lab-STICC
Technopôle Brest Iroise
CS 83818, 29238 Brest Cedex 3, France
Email: yannis.haralambous@telecom-bretagne.eu <mailto:yannis.haralambous@telecom-bretagne.eu>
Internet: http://perso.telecom-bretagne.eu/yannisharalambous/ <http://omega.enstb.org/yannis>
ICBM address: 48°21'31.57"N 4°34'16.76"W
Twitter: y_haralambous
-------------------------------------------------------
...the ball I threw while playing in the park
has not yet reached the ground
(Dylan Thomas)

Es gab eine Zeit, wo ich nur ungern über Schubert sprechen,
nur Nächtens den Bäumen und Sternen von ihm vorerzählen mögen.
(Robert Schumann)

**Comment by phi-gamma** [comment]
Bonjour!

Je vous comprends seulement un peu ;)

In any case, this was a problem with the loader for the OFM
format which is supposed to be treated the same way as TFM from
our perspective, but lacked the definition. Check out commit
b271e25.. for the boring details. Probably my fault.

A couple related files have been added to the test repo:

    https://bitbucket.org/phg/lua-la-tex-tests/src/tip/plain/pln-ofm-1.tex
    https://bitbucket.org/phg/lua-la-tex-tests/src/tip/plain/pln-ofm-2.tex
    https://bitbucket.org/phg/lua-la-tex-tests/src/tip/latex/ltx-ofm-1.tex

@eroux how urgent is this issue? The patch should be
straightforward to backport to the current 2.5 release. Since it
looks like it’s going to be bad weather tomorrow, I might find
the time to push a hotfix release.

Thanks for reporting!
Philipp

···<date: 2015-06-12, Friday>···<from: yannis1962>···

> Ils t’ont répondu ?
>

**Comment by eroux** [comment]
Thanks for the fix! I don't think TeXLive upates from CTAN these days, so it's clearly not an emergency for today. When do you think the 2.6 version will be ready?

**Comment by yannis1962** [comment]
Thanks for solving the issue (I haven’t checked yet, I will wait until you put it on CTAN).

It is not urgent. Once I will be able to update my system and check that luaotfload works with dad, and once overleaf will have updated its TeXLive distribution, I will release a new version of dad, based on fontspec (I will also include a LaTeX environment for Arabic poetry).

Question: do I really need to write absolute paths in the .fd file? How can I distribute dad as a TeXLive package with absolute file paths in the FD file? Can I write paths relative to TeXLive root?

> Le 13 juin 2015 à 10:08, Elie Roux <notifications@github.com> a écrit :
> 
> Thanks for the fix! I don't think TeXLive upates from CTAN these days, so it's clearly not an emergency for today. When do you think the 2.6 version will be ready?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lualatex/luaotfload/issues/273#issuecomment-111686078>.
> 

-- 
-------------------------------------------------------
Yannis Haralambous
Professor
Institut Mines-Télécom, Télécom Bretagne
Computer Science Department
UMR CNRS 6285 Lab-STICC
Technopôle Brest Iroise
CS 83818, 29238 Brest Cedex 3, France
Email: yannis.haralambous@telecom-bretagne.eu <mailto:yannis.haralambous@telecom-bretagne.eu>
Internet: http://perso.telecom-bretagne.eu/yannisharalambous/ <http://omega.enstb.org/yannis>
ICBM address: 48°21'31.57"N 4°34'16.76"W
Twitter: y_haralambous
-------------------------------------------------------
...the ball I threw while playing in the park
has not yet reached the ground
(Dylan Thomas)

Es gab eine Zeit, wo ich nur ungern über Schubert sprechen,
nur Nächtens den Bäumen und Sternen von ihm vorerzählen mögen.
(Robert Schumann)

**Comment by eroux** [comment]
As long as files can be found by kpse, you don't have to make files absolute; I don't think you'll have to change your .fd files...

**Comment by yannis1962** [comment]
David Carlisle dixit

texdoc luaotfload implies ofm fonts should be loaded so my theory is that changing dad in the fd file to [dad] or [file:dad.ofm]or "file:/usr/local/texlive/2015/texmf-dist/fonts/ofm/public/dad/dad" ought to work, but none of them do….

so you are saying that I don’t need the explicit file path, but I do need the brackets, no?
Is [file:dad.ofm] acceptable?

> Le 13 juin 2015 à 11:56, Elie Roux <notifications@github.com> a écrit :
> 
> As long as files can be found by kpse, you don't have to make files absolute; I don't think you'll have to change your .fd files...
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lualatex/luaotfload/issues/273#issuecomment-111694177>.
> 

-- 
-------------------------------------------------------
Yannis Haralambous
Professor
Institut Mines-Télécom, Télécom Bretagne
Computer Science Department
UMR CNRS 6285 Lab-STICC
Technopôle Brest Iroise
CS 83818, 29238 Brest Cedex 3, France
Email: yannis.haralambous@telecom-bretagne.eu <mailto:yannis.haralambous@telecom-bretagne.eu>
Internet: http://perso.telecom-bretagne.eu/yannisharalambous/ <http://omega.enstb.org/yannis>
ICBM address: 48°21'31.57"N 4°34'16.76"W
Twitter: y_haralambous
-------------------------------------------------------
...the ball I threw while playing in the park
has not yet reached the ground
(Dylan Thomas)

Es gab eine Zeit, wo ich nur ungern über Schubert sprechen,
nur Nächtens den Bäumen und Sternen von ihm vorerzählen mögen.
(Robert Schumann)

**Comment by eroux** [comment]
I don't think you have to change anything (not even the brackets), but it's best to try before... Maybe `name:dad` instead of just `dad` will be necessary, but I'm not sure...

**Comment by phi-gamma** [comment]
···<date: 2015-06-13, Saturday>···<from: Elie Roux>···

> I don't think you have to change anything (not even the
> brackets), but it's best to try before... Maybe `name:dad`
> instead of just `dad` will be necessary, but I'm not sure...

Just ``dad`` should be okay, especially for TFM/OFM which are
looked up through kpse anyways. Ambiguities may arise, however,
if multiple fonts are present that share a file name.
``file:dad.ofm`` is the most explicit one (which I prefer), but
the syntax not portable to other engines. With OFM that probably
matters little, though. The bracket syntax ``[/path/to/font.ext]`` 
serves two purposes: a) compatibility with the Xetex engine,
AFAIR it’s used internally by the Fontspec package, and b) for
supplying absolute paths. The ``name:dad`` one will cause a
lookup in the font name database which is usually overkill if you
already know the file name, though it’s essential for more
human-friendly concepts like font families to work.

**Comment by davidcarlisle** [comment]
@yannis yes sorry about the full path confusion, I was just experimenting with various things to see if they worked before giving up and suggesting you ping here.

**Comment by yannis1962** [comment]
Can you please tell me the version of the corrected file and where I can find it? Is there a way to specify the minimum version required when loading luaotfload?


> Le 13 juin 2015 à 12:18, Philipp Gesang <notifications@github.com> a écrit :
> 
> ···<date: 2015-06-13, Saturday>···<from: Elie Roux>···
> 
> > I don't think you have to change anything (not even the
> > brackets), but it's best to try before... Maybe `name:dad`
> > instead of just `dad` will be necessary, but I'm not sure...
> 
> Just ``dad`` should be okay, especially for TFM/OFM which are
> looked up through kpse anyways. Ambiguities may arise, however,
> if multiple fonts are present that share a file name.
> ``file:dad.ofm`` is the most explicit one (which I prefer), but
> the syntax not portable to other engines. With OFM that probably
> matters little, though. The bracket syntax ``[/path/to/font.ext]`` 
> serves two purposes: a) compatibility with the Xetex engine,
> AFAIR it’s used internally by the Fontspec package, and b) for
> supplying absolute paths. The ``name:dad`` one will cause a
> lookup in the font name database which is usually overkill if you
> already know the file name, though it’s essential for more
> human-friendly concepts like font families to work.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lualatex/luaotfload/issues/273#issuecomment-111695683>.
> 

-- 
-------------------------------------------------------
Yannis Haralambous
Professor
Institut Mines-Télécom, Télécom Bretagne
Computer Science Department
UMR CNRS 6285 Lab-STICC
Technopôle Brest Iroise
CS 83818, 29238 Brest Cedex 3, France
Email: yannis.haralambous@telecom-bretagne.eu <mailto:yannis.haralambous@telecom-bretagne.eu>
Internet: http://perso.telecom-bretagne.eu/yannisharalambous/ <http://omega.enstb.org/yannis>
ICBM address: 48°21'31.57"N 4°34'16.76"W
Twitter: y_haralambous
-------------------------------------------------------
...the ball I threw while playing in the park
has not yet reached the ground
(Dylan Thomas)

Es gab eine Zeit, wo ich nur ungern über Schubert sprechen,
nur Nächtens den Bäumen und Sternen von ihm vorerzählen mögen.
(Robert Schumann)

**Comment by phi-gamma** [comment]
···<date: 2015-06-22, Monday>···<from: yannis1962>···

> Can you please tell me the version of the corrected file and
> where I can find it?

This commit:

    https://github.com/lualatex/luaotfload/commit/b271e253b40cd0af97f6d50f0461f87ad1ed5314

with the patch yielding this file:

    https://github.com/lualatex/luaotfload/blob/b271e253b40cd0af97f6d50f0461f87ad1ed5314/src/luaotfload-loaders.lua

which should work as-is with the Luaotfload 2.5 in CTAN.


>                      Is there a way to specify the minimum
> version required when loading luaotfload?

I don’t think so, unless that feature is available via Latex’s
``\usepackage``. For Plain I don’t think there’s a way to specify
a minimum version.

Best,
Philipp

**Comment by phi-gamma** [comment]
Patch is included in the release candidate: https://github.com/lualatex/luaotfload/releases/tag/v2.6-rc1

Closing this.

**Comment by yannis1962** [comment]
dear Philipp,

two years ago I asked for help concerning compatibility of lua font loading,
now I attempted to include the changes you suggested into my package,
but it doesn't work.

Here is what happens:

1) when I don't use luaotfload everything works fine

2) when I load fontspec at some time, whether before or after dad,
both OFM and TTF fonts are found and loaded, but the smart ligatures of
my OFM font are not executed and all glyphs are in isolated form.

Interestingly enough, this happens only with one font among three
(I supply plain, bold and monospace, the problem occurs only for plain).

Do you think you have some time to investigate what is happening?

Here are the versions of packages I'm using:

Package: fontspec 2016/02/01 v2.5a Font selection for XeLaTeX and LuaLaTeX
 (/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload.sty
Package: luaotfload 2016/06/16 v2.7 OpenType layout system
Lua module: luaotfload-main 2016/06/16 2.70003 OpenType layout system.
Lua module: lualibs 2016-04-06 2.4 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2016-04-06 2.4 ConTeXt Lua libraries -- extended collection.(using write cache: /usr/local/texlive/2016/texmf-var/luatex-cache/generic)(using read cache: /usr/local/texlive/2016/texmf-var/luatex-cache/generic /Users/yannis/.texlive2016/texmf-var/luatex-cache/generic)
luaotfload | conf : Root cache directory is /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names.
luaotfload | init : Loading fontloader “fontloader-2016-06-16.lua” from kpse-resolved path “/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/fontloader-2016-06-16.lua”.
Lua-only attribute luaotfload@state = 1
Lua-only attribute luaotfload@noligature = 2
Lua-only attribute luaotfload@syllabe = 3
luaotfload | init : Context OpenType loader version “3.023”
Inserting `luaotfload.node_processor' at position 1 in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' at position 1 in `hpack_filter'.
Inserting `luaotfload.define_font' at position 1 in `define_font'.
Lua-only attribute luaotfload_color_attribute = 4
luaotfload | conf : Root cache directory is /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names.
Inserting `luaotfload.aux.set_sscale_dimens' at position 1 in `luaotfload.patch_font'.
Inserting `luaotfload.aux.patch_cambria_domh' at position 2 in `luaotfload.patch_font'.
Inserting `luaotfload.aux.fixup_fontdata' at position 1 in `luaotfload.patch_font_unsafe'.
Inserting `luaotfload.aux.set_capheight' at position 3 in `luaotfload.patch_font'.
Inserting `luaotfload.rewrite_fontname' at position 4 in `luaotfload.patch_font'.
luaotfload | main : initialization completed in 0.144 seconds

Thanks in advance,

Yannis

> Le 13 juin 2015 à 12:18, Philipp Gesang <notifications@github.com <mailto:notifications@github.com>> a écrit :
> 
> ···<date: 2015-06-13, Saturday>···<from: Elie Roux>···
> 
> > I don't think you have to change anything (not even the
> > brackets), but it's best to try before... Maybe `name:dad`
> > instead of just `dad` will be necessary, but I'm not sure...
> 
> Just ``dad`` should be okay, especially for TFM/OFM which are
> looked up through kpse anyways. Ambiguities may arise, however,
> if multiple fonts are present that share a file name.
> ``file:dad.ofm`` is the most explicit one (which I prefer), but
> the syntax not portable to other engines. With OFM that probably
> matters little, though. The bracket syntax ``[/path/to/font.ext]`` 
> serves two purposes: a) compatibility with the Xetex engine,
> AFAIR it’s used internally by the Fontspec package, and b) for
> supplying absolute paths. The ``name:dad`` one will cause a
> lookup in the font name database which is usually overkill if you
> already know the file name, though it’s essential for more
> human-friendly concepts like font families to work.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lualatex/luaotfload/issues/273#issuecomment-111695683>.
> 

-------------------------------------------------------
Join the “Graphemics in the 21st century” conference in June 2018!
http://conferences.telecom-bretagne.eu/grafematik/ <http://conferences.telecom-bretagne.eu/grafematik/>
-------------------------------------------------------
Yannis Haralambous
Professor
IMT Atlantique (formerly Télécom Bretagne)
Computer Science Department
UMR CNRS 6285 Lab-STICC
Technopôle Brest Iroise
CS 83818, 29238 Brest Cedex 3, France
Email:  <mailto:yannis.haralambous@imt-atlantique.fr>yannis.haralambous@i <mailto:yannis.haralambous@telecom-bretagne.eu>mt-atlantique.fr <http://mt-atlantique.fr/>
Internet: http://perso.telecom-bretagne.eu/yannisharalambous/ <http://omega.enstb.org/yannis>
ICBM address: 48°21'31.57"N 4°34'16.76"W
Twitter: y_haralambous
-------------------------------------------------------
...the ball I threw while playing in the park
has not yet reached the ground
(Dylan Thomas)

Es gab eine Zeit, wo ich nur ungern über Schubert sprechen,
nur Nächtens den Bäumen und Sternen von ihm vorerzählen mögen.
(Robert Schumann)
