### ISSUE TITLE
Error when a font with script deva is used together with math

### ISSUE THREAD

**Issue by u-fischer** [lualatex/luaotfload#277]
The following document doesn't compile

~~~~~
\documentclass{article}
\usepackage{luaotfload}
\font\test="Nakula:mode=node;script=deva;language=DFLT;+tlig;+trep;"
%\font\test="Nakula:mode=node;language=DFLT;+tlig;+trep;"
\begin{document}\test
श्रेयो $a$
\end{document}
~~~~~

~~~~~
d luc: D:/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/nakula.luc)
(./test-utf8.aux)error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.
lua:9439: attempt to index field 'resources' (a nil value)
.
\newpage ...k \@nobreakfalse \everypar {}\fi \par
                                                  \vfil \penalty -\@M
l.13 \end{document}

?
~~~~~

I got the font from here : http://bombay.indology.info/software/fonts/devanagari/nakula.ttf

The file compiles fine if the `script=deva;` is removed from the font definition. It also works fine if the math is not in the same paragraph. I also tried with Arial Unicode MS and got the same error, but other scripts seem to work fine.

**Comment by phi-gamma** [comment]
With the current fontloader and the Nakula fonts from
http://bombay.indology.info/software/fonts/devanagari/
I cannot reproduce this.

**Comment by u-fischer** [comment]
I can still reproduce it in a current (official TeXlive 2015) system. I transformed it to ascii to avoid problems with copy and paste. It looks as if the error only pops up with some specific devanagari input (the U+094d), and there must be a tfm-font loaded afterwards.

~~~~~
\documentclass{article}
\usepackage{luaotfload}
\font\test="Nakula:mode=node;script=deva;language=DFLT;+tlig;+trep;"
\font\testb=cmr10

\begin{document}
\test ^^^^0936^^^^094d 
\testb b 
\end{document}
~~~~~

**Comment by phi-gamma** [comment]
Thanks! With the current fontloader, the example typesets, resulting in
[this PDF](http://i.imgur.com/IXyaCDC.png). I thus consider it fixed.
Please reopen after 2.6 is out if the issue should persist in some
other manner.
