### ISSUE TITLE
luaotfload-tool does not not remove non-existing files from the index

### ISSUE THREAD

**Issue by wybodekker** [lualatex/luaotfload#278]
When  a .ttf/.otf file is removed, and then luaotfload-tool --update --force is executed, the .lua and .luc files corresponding to the removed files stay in the index ($TEXMFVAR/luatex-cache/generic/fonts/otf). 
I think that the --update option should check the existing .lua files for filenames that don't exist or are not readable, and should remove such .lua and .luc files. The following bash script (I have no lua experience) reports wrong entries in the index (and found 21 in mine):

    #!/bin/bash
    warn() { echo -e " $@"; }
 
    indexpath=$(kpsewhich --expand-var \$TEXMFVAR)/luatex-cache/generic/fonts/otf
    for i in $indexpath/*.lua; do
       # find the file name
       f=$(sed -n '/filename/{
          h
          s/.*"\(.*\)",/\1/
          p
          q
       }' $i)
       j=${i//*\//}
       if [[ ! -e $f ]]; then
           warn "$j: $f does not exist"
       elif [[ ! -r $f ]]; then
           warn "$j: $f is not readable"
       fi
    done

**Comment by phi-gamma** [comment]
Thanks for reporting. A fix will be part of the next release.
