### ISSUE TITLE
Node mode hyphenates words after context sensitive glyphs have been chosen

### ISSUE THREAD

**Issue by SverreStausland** [lualatex/luaotfload#284]
See http://tex.stackexchange.com/questions/262998/context-sensitive-glyph-appears-even-when-hyphenation-removes-the-context

I believe this is ultimately the same issue as in https://github.com/khaledhosny/luaotfload/issues/43, which apparently is also caused by hyphenation happening after ligatures have been selected, rather than the other way around.

**Comment by eroux** [comment]
Would you have a MWE in ConTeXt? That would help bugreporting upstream (the code of luaotfload comes from ConTeXt).

**Comment by SverreStausland** [comment]
Sorry, I have never used ConTeXt, so I wouldn't be able to make MWE for it.

**Comment by michal-h21** [comment]
I am not ConTeXt user either, so my MWE doesn't work as expected (ConTeXt doesn't support `\parbox` command and I don't know how to force line break in af-ter):


    \usemodule[simplefonts][size=10pt]                                                                                         
    \setmainfont[Alegreya]
    \starttext
     Grafika after Tufte full                                                                                                    
    \framed[width=0pt, frame=off, location=left]{for after }
    \stoptext  

What's strange is that while long "f" is used in word "Tufte", it isn't used in "after" (even not in non-breaked word), as opposed to situation in LuaLaTeX, where long "f" is used in both cases.

Anyway, it seems that this long "f" isn't ligature, but it is selected with `gsub` feature. I think I've found the code responsible for handling this case, it is `chainprocs.gsub_single` function in `luaotfload-fontloader.lua`. 

In this snippet:

        replacement=replacement[currentchar]
        if not replacement or replacement=="" then
          if trace_bugs then
            logwarning("%s: no single for %s",cref(kind,chainname,chainlookupname,lookupname,chainindex),gref(currentchar))
          end
        else
          if trace_singles then
            logprocess("%s: replacing single %s by %s",cref(kind,chainname,chainlookupname,lookupname,chainindex),gref(currentchar),gref(replacement))
          end
          current.char=replacement
        end

we can see that this feature replaces directly the character code of the matched glyph, so the linebreaking mechanism can't use the correct form in the case of word break. Maybe discretionary should be used instead?

**Comment by phi-gamma** [comment]
The snippet in the tex.sx link above looks like this with the current fontloader:

![This](http://i.imgur.com/LyXco7G.png)

**Comment by phi-gamma** [comment]
@SverreStausland New release is out, please retest.

**Comment by SverreStausland** [comment]
The new release is not available through texlive yet, so I'll need to wait
until it is.

**Comment by phi-gamma** [comment]
···<date: 2015-12-10, Thursday>···<from: SverreStausland>···

> The new release is not available through texlive yet, so I'll
> need to wait until it is.

Of course =) This is just a reminder, take as long as you wish.

**Comment by phi-gamma** [comment]
@SverreStausland ping
