### ISSUE TITLE
wrong permission on pdf and aux output files

### ISSUE THREAD

**Issue by eroux** [lualatex/luaotfload#285]
Compiling the following file:

```
\input luaotfload.sty

Hello
\bye
```

creates a pdf with `0666` permissions, while commenting the first line creates a pdf with `0644` permissions. The problem is also present with the `.aux` file if the following file is compiled with lualatex:

```
\documentclass{article}
\usepackage{luaotfload}
\begin{document}
  Hello
\end{document}
```

**Comment by phi-gamma** [comment]
Weird stuff, reported upstream: http://tracker.luatex.org/view.php?id=956

**Comment by phi-gamma** [comment]
Upstream fix contained in git-svn-id: https://foundry.supelec.fr/svn/luatex/branches/experimental@5557 0b2b3880-5936-4365-a048-eb17d2e5a6bf

Closing.
