### ISSUE TITLE
luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)

### ISSUE THREAD

**Issue by gossi** [lualatex/luaotfload#288]
Hi there,

I'm using MacTex 2015 and I'm getting this error:

```
luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
```

To me it happens randomly, sometimes the typesetting works, sometimes not. It happens on figures, like this:

```
\begin{figure}[H]
	\centering
	\includegraphics[width=0.6\linewidth]{path/to/a/pdf-file}
	\caption{A caption on this one with $math$ fields and \protect\cite{somebody}}
	\label{fig:A_Label}
\end{figure}
```

Ping me, if you need more input (and how I can provide it to you).

**Comment by eroux** [comment]
Providing a MWE (minimal working example) showing the problem would be nice (even if it doesn't happen at every compilation). If it's in Plain TeX it would be nice, but LaTeX is ok.

**Comment by eroux** [comment]
@gossi do you think you could provide us with an example?

**Comment by gossi** [comment]
It's tricky. My .tex files have grown huge, so I don't know if I reduce it to a MWE, that some of my packages I'd keep out are the interfering packages, though I'm trying.

**Comment by eroux** [comment]
Thanks, that really helps

**Comment by gossi** [comment]
Just tried, it's the case that I expected. The MWE example works. Basically, my tex-stuff works and the code above that throws the error, I have at various other locations as well, so none of them throws an error.
I just was wondered, that this only happens to just one section (which happens to be in its own file). So I commented out the `\input` command. The typeset worked (of course without that particular section). I toggled the comment again and it typesetted. I get an error, because a reference wasn't found (I have three of the above section which is commented out at the moment). I run typeset the second time, which shows the error as shown above.
I commented out that reference that was failing, commented out the `\input` to get a fresh start. Then included the file again and got the error above in the first run this time, here is the whole log:

```
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.23
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.41 
   
[21
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.58
]error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.58
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.71 
   
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.74 
   
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.78 
   
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.81 
   
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.83 
   
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.86 
   
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9409: attempt to index field 'resources' (a nil value)
.
l.88 
```

I meanwhile have splitted the `\caption` into `\caption` and `\caption*`. I tried various variation, with only one of them commented out, both and none with no possitive effect.

Can I help out something else (I'm a developer myself)?

**Comment by eroux** [comment]
Well, I'm not sure we can do something if we can't reproduce it... The only thing you could do is provide the whole document or debug `luaotfload-fontloader.lua` yourself...

**Comment by gossi** [comment]
Well, I opened luaotfload-fontloader.lua and navigated to the respective line:

```
function injections.handler(head,where,keep)
  local has_marks,has_cursives,has_kerns=next(marks),next(cursives),next(kerns)
  if has_marks or has_cursives then
    if trace_injections then
      trace(head)
    end
    local done,ky,rl,valid,cx,wx,mk,nofvalid=false,{},{},{},{},{},{},0
    if has_kerns then 
      local nf,tm=nil,nil
      for n in traverse_id(glyph_code,head) do 
        if n.subtype<256 then
          nofvalid=nofvalid+1
          valid[nofvalid]=n
          if n.font~=nf then
            nf=n.font
            tm=fontdata[nf].resources.marks
          end
```

9409 is the second last line in this chunk of code (well, I guess you are already aware of this). Any chance I can manipulate my tex code to get another result here?

As it has obviously something to do with fonts, I tried to echo it. So I put `print(nf)` in there:

```
          if n.font~=nf then
            nf=n.font
            print(nf)
            tm=fontdata[nf].resources.marks
          end
```

So, the log changed to something like this:

```
60
60
60
60
60
60
60
[19]
60
60
60
60
60
[20
]60
60
60
) (./my-chapter.tex
60
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.23
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.23
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.41 
   
[21]
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.41 
   
[21]
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.58 
   
60
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.58 
   
60
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.71 
   
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.74 
   
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.78 
   
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.81 
   
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.83 
   
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.86 
   
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.88
60
32
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.71 
   
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.74 
   
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.78 
   
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.81 
   
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.83 
   
60
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.86 
   
42
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9410: attempt to index field 'resources' (a nil value)
.
l.88
```

In this case it looks like, the offset `42` is the problem. I let it run multiple times and the problematic index changes. Does that help?

**Comment by eroux** [comment]
I'm affraid not. I don't really debug the loader code anymore (not enough time), the only thing I can do is provide ConTeXt (which is the source of the loader code) with a minimal plainTeX example showing the result. So even a LaTeX example requires some work for me to translate it into plainTeX, leave alone a document I cannot access... Sorry! I'm affraid the only thing you can do is understand the code and fix it, but expect it to take some time...

**Comment by gossi** [comment]
I got it.

First, you only assign the `tm` variable and test if it exists after the if block that is assigning it. You assume, that `fontdata[nf].resources.marks` is available all the time, which isn't. What's missing is a check here, which I put around and so far I'm fine. 

This is what it looks now:
```
          if n.font~=nf then
            nf=n.font
            tm=nil
            if fontdata[nf] and fontdata[nf].resources and fontdata[nf].resources.marks then
              tm=fontdata[nf].resources.marks
            end
          end
          if tm then
            mk[n]=tm[n.char]
          end
```

**Comment by eroux** [comment]
Thanks a lot for the debugging! I'll report it!

**Comment by eroux** [comment]
Well, I'm not sure it's relevant if the bug only appears in corner cases, but whit what font does it occur? (that's what was asked when reporting upstream)

**Comment by gossi** [comment]
I can't tell you, I only got the index number of the font. I can echo it, for sure. But you need to tell me, what variable I need to echo out (`n.font` contains a number).

**Comment by eroux** [comment]
You can access the font table with

    local fontdata = fonts.hashes.identifiers[font_id]

**Comment by gossi** [comment]
ok, I have access to the fontdata. How to get the name property from there? (`fontdata.name` didn't work).

**Comment by eroux** [comment]
I admit i cannot remember the font structure, but you can debug the structure (which is a bit big) using 

    texio.write_nl(table.serialize(fonts.hashes.identifiers[font_id]))

(or something similar)

**Comment by gossi** [comment]
ok, got it:

```
"Calibri:mode=node;script=latn;language=DFLT;"
error: ...xmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua:9412: attempt to index field 'resources' (a nil value)
```

here is the code, that produces the above output:
```
if n.font~=nf then
            nf=n.font
            tm=nil
            print(fontdata[nf].name)
            --if fontdata[nf] and fontdata[nf].resources and fontdata[nf].resources.marks then
              tm=fontdata[nf].resources.marks
            --end
          end
```

**Comment by eroux** [comment]
Well, Calibri is quite common and works in "normal" contexts, so I'm afraid there's not much that can be done without an example, sorry...

**Comment by gossi** [comment]
Ah, the typesetting is working all fine. The only thing was, the above error prevented the typesetting to finish. With my workaround, checking for the respective fields, the typesetting isn't stopped anymore. That's all that was required here to fix this.

**Comment by phi-gamma** [comment]
Probably related: https://github.com/lualatex/luaotfload/issues/277

The latter doesn’t occur anymore with the current fontloader.

**Comment by phi-gamma** [comment]
@gossi New release is out, please retest.

**Comment by phi-gamma** [comment]
We’re a couple of bugfix releases into the new iteration without any
report. Under the circumstances I guess it’s fair to consider the
matter resolved.

Please reopen if necessary.
