### ISSUE TITLE
TTC inclusion failure when subfont name equals font name

### ISSUE THREAD

**Issue by eroux** [lualatex/luaotfload#289]
See [this post](http://tug.org/pipermail/luatex/2015-October/005377.html).

**Comment by phi-gamma** [comment]
@eroux This was fixed upstream with this commit:

    commit f7d8d2d0edf7c5cd845b1c604fbea24ffe5a7e6e
    Author: luigi <luigi@0b2b3880-5936-4365-a048-eb17d2e5a6bf>
    Date:   Fri Oct 9 10:29:42 2015 +0000
    
         a patch for ttc fonts with bad index
        
        git-svn-id: https://foundry.supelec.fr/svn/luatex/trunk@5365 0b2b3880-5936-4365-a048-eb17d2e5a6bf

wasn’t it? I’ll tag this a Luatex bug for now. If this is still reproducible
with the current build from SVN, then we’ll need some font file to test with.

**Comment by eroux** [comment]
I can't remember the details, but I think you're right, I just left it open because the code wasn't imported from ConTeXt. By the way, thanks a lot for continuing the development and maintenance! I was kind of lost and just managed to file bug reports...

**Comment by phi-gamma** [comment]
> I can't remember the details, but I think you're right

Okay, I’ll close this, then. If the issue should reoccur after the
next Luatex release, we can always reopen.

>  By the way, thanks a lot for continuing the development and maintenance! I was kind of lost and just managed to file bug reports...

It’s alright. My spare time just got a little fragmented =)
Expect a reply to your email from months ago next week.
