### ISSUE TITLE
Garbled glyphs when rendering Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by deepakjois** [lualatex/luaotfload#292]
I apologise if this is not related to luaotfload. If so, please let me know where I should report this.

I am typesetting a Urdu document set in Noto Nastaliq Urdu font in LuaLaTeX, and getting really terrible results. I would like to understand what the problem could be. The same document renders much better in XeLaTeX.

For e.g, here is a screenshot for LuaLaTeX:

<img width="404" alt="screenshot 2015-11-15 17 51 19" src="https://cloud.githubusercontent.com/assets/5342/11168728/7cfb6998-8bc2-11e5-96fd-d7f79df2b275.png">

vs. XeLaTeX:

<img width="441" alt="screenshot 2015-11-15 17 57 41" src="https://cloud.githubusercontent.com/assets/5342/11168727/76458dcc-8bc2-11e5-8b6e-7866b491f251.png">

Source for the LuaLaTeX document (will need Noto Nastaliq Urdu font which can be easily downloaded): https://github.com/deepakjois/tex-sandbox/blob/master/lualatex_crappy_arabic.tex

My environment: OS X El Capitan, TeX Live 2015

**Comment by phi-gamma** [comment]
Looks like this with the current code:

![urdu](http://i.imgur.com/U1Aqy96.png)

It didn’t change much, if at all. I’ll try to cook up a Context example
for upstream.

**Comment by deepakjois** [comment]
Hmm… that’s a bit strange. The .ttf font file is 488Kb on my computer. How does that expand out to 579.70Mb? I am a bit mystified as to how a font this small can expand out to such a huge size. Where can I see this on my computer?

This is a font in the Nastaliq style, used to write Arabic. There aren’t many around. This is the only one I know with an open license.

**Comment by deepakjois** [comment]
I got the font from this URL (listed on the Noto site): https://noto-website-2.storage.googleapis.com/pkgs/NotoNastaliqUrdu-unhinted.zip

**Comment by deepakjois** [comment]
Do you have a package with _all_ the Noto fonts by any chance? That could explain the huge size.

**Comment by phi-gamma** [comment]
> Do you have a package with all the Noto fonts by any chance? That could explain the huge size.

That’s it, probably. I just installed this package:

    Name           : ttf-noto
    Version        : 20150927-1
    Description    : Fonts support all languages/characters in Unicode
    …
    Installed Size : 579.70 MiB

It’s a lot of fonts, I just realized:

    $ ./luaotfload-tool.lua --list='*' | grep Noto | wc -l
    167

**Comment by deepakjois** [comment]
I am curious, where does the upstream development of luaotfload happen. Is that in ConTeXt? Is the code repository available online?

**Comment by phi-gamma** [comment]
> I am curious, where does the upstream development of luaotfload happen. Is that in ConTeXt? Is the code repository available online?

Luaotfload development happens right here on Github.
The main component, however, is the fontloader that
is taken from Context. These things are documented in
the manual, btw.

**Comment by phi-gamma** [comment]
Context example:

    https://bitbucket.org/phg/lua-la-tex-tests/src/496adb55d33181b25a645559041a0d20a4f1fe6b/context/cnt-urdu.tex

Output with Context beta 2015.11.19 19:13 with Luatex 5550:

![example urdu output](http://i.imgur.com/tRISdCG.png).

I didn’t get the spacing right since I have no idea what those
settings in the original do. Apart from that, it’s the same thing.
Looks like upstream’s not ahead of the fontloader we currently
ship. I’ll relay this.

**Comment by deepakjois** [comment]
Thank you. The spacing isn’t particularly important in this case. I guess fontspec adjusts the default glue length for the interword spacing, when we specify the `WordSpace` option.

**Comment by phi-gamma** [comment]
There’s a reply from Hans: http://mailman.ntg.nl/pipermail/ntg-context/2015/083691.html
Specifying ``dflt`` doesn’t make a visual difference, though.

**Comment by deepakjois** [comment]
In my example, I changed 

```
\newfontfamily\notourdu[Script=Arabic,Language=Urdu,WordSpace=5]{Noto Nastaliq Urdu}
```
to

```
\newfontfamily\notourdu[Script=Arabic,WordSpace=5]{Noto Nastaliq Urdu}
```

The output improves quite a bit, but still bad IMO.

<img width="500" alt="screenshot 2015-11-28 17 08 24" src="https://cloud.githubusercontent.com/assets/5342/11451642/073b728a-95f3-11e5-9a52-00455e31fcb0.png">

**Comment by khaledhosny** [comment]
BTW, selecting a font not available for the selected script and feature should fallback to `dflt`, so that is a bug in itself.

**Comment by u-fischer** [comment]
This will probably properly work (only) with mode=harf.
