### ISSUE TITLE
adjust letterspacing behavior regarding word space

### ISSUE THREAD

**Issue by phi-gamma** [lualatex/luaotfload#297]
Interword spacing is not scaled appropriately.

* Thread on Stackexchange: http://tex.stackexchange.com/a/276445/14066

* egreg’s minimal example for plain: https://bitbucket.org/phg/lua-la-tex-tests/src?at=default&fileviewer=file-view-default

**Comment by u-fischer** [comment]
It doesn't look as if the problem has been resolved. I don't get sensible wordspace in the example of egreg in the tex.SX-question neither with the official version nor the release version of luaotfload nor with the context fontloader .
