### ISSUE TITLE
unicode key in font resource doesn't contain characters in Private Area anymore

### ISSUE THREAD

**Issue by eroux** [lualatex/luaotfload#308]
It seems [Gregorio](http://gregorio-project.github.io/) has [a problem](https://github.com/gregorio-project/gregorio/issues/717) with latest release. I can't really try now, but my guess is that it uses the internal structure which changed during last update... The relevant pieces of code are [here](https://mail.gna.org/public/gregorio-users/2015-12/msg00036.html), but it's mainly mapping glyphname to unicode char : Gregorio looks for a certainly glyph name in the font, and then tells TeX to typeset the corresponding character. Maybe a high level function could allow that in luaotfload? This would prevent this kind of bug when the internal structure changes.

**Comment by phi-gamma** [comment]
Dear Élie,

thanks for the report.

···<date: 2015-12-17, Thursday>···<from: Elie Roux>···

>                      I can't really try now, but my guess is
> that it uses the internal structure which changed during last
> update...

That’s possible. I’ll have a look.

>           The relevant pieces of code are
> [here](https://mail.gna.org/public/gregorio-users/2015-12/msg00036.html),
> but it's mainly mapping glyphname to unicode char : Gregorio
> looks for a certainly glyph name in the font, and then tells
> TeX to typeset the corresponding character. Maybe a high level
> function could allow that in luaotfload?

Didn’t we have something like this already? If not, I’ll
come up with something.

Best,
Philipp

**Comment by eroux** [comment]
Thanks a lot for investigating! We have a few high level functions for third-party packages to use (like name to slot, slot to name, etc.), but not the ability to get the list for instance (but I might be wrong)

**Comment by eroux** [comment]
[Gregorio issue #717](https://github.com/gregorio-project/gregorio/issues/717#issuecomment-166119071) now contains a plain TeX example showing the problem (no Gregorio installation needed). The font needed to compile this example can be found [here](http://norgz.guiling.fr/greciliae.ttf). Works fine with luaotfload 2.5, but luaotfload 2.6 doesn't return glyphs in unicode private area when accessing `font.getfont(font.id('greciliae')).resources.unicodes`

**Comment by michal-h21** [comment]
Some higher level interface would be really nice. For my [Harbuzz experiment](https://github.com/michal-h21/luatex-harfbuzz-shaper) I use some Luaotfload code to search for fonts in the font DB and for parsing requested font name and features. 

I've looked for a possibility to use Luaotfload also for setting basic font parameters (currently I use [modified fontloader from  LuaTeX wiki](http://wiki.luatex.org/index.php/Use_a_TrueType_font)), because it seems to do a lot of useful things (binary cache, unicode math handling), but I must admit that it is so complex that I can't figure out how to use only needed features (all OpenType features are handled by Harfbuzz so there is no need for their handling in the loader), and on the other hand, how to save some needed data (`map.backmap` in particular).

**Comment by eroux** [comment]
@michal-h21 maybe you could provide the API you would need? We developped some high level functions for microtype a while ago, it's certainly reasonable to implement a few high level functions for harfbuzz too! I'm renaming this issue (because it turned into something completely different from the original title), but I open a new one with your request.

**Comment by eroux** [comment]
The problem is a bit more complex:

in luaotfload < 2.6:

- `resources.unicodes` contains all unicode values, even those in Private Area
- `shared.rawdata.descriptions` doesn't contain unicode values

in luaotfload 2.6:

- `resources.unicodes` doesn't contain characters in Private Area
- `shared.rawdata.descriptions` contains unicode values

So there's no way to share code between the different versions. I can see two solutions to this:

- let gregorio test `luaotfload.version`
- provide some way for gregorio to iterate on `glyphname, unicode in pairs(myfont.luaotfload.nameunicode)` through some metatable or metamethod

@phi-gamma what do you think?

**Comment by phi-gamma** [comment]
···<date: 2015-12-22, Tuesday>···<from: Elie Roux>···

> The problem is a bit more complex:
> 
> in luaotfload < 2.6:
> 
> - `resources.unicodes` contains all unicode values, even those in Private Area
> - `shared.rawdata.descriptions` doesn't contain unicode values
> 
> in luaotfload 2.6:
> 
> - `resources.unicodes` doesn't contain characters in Private Area
> - `shared.rawdata.descriptions` contains unicode values
> 
> So there's no way to share code between the different versions. I can see two solutions to this:
> 
> - let gregorio test `luaotfload.version`
> - provide some way for gregorio to iterate on `glyphname, unicode in pairs(myfont.luaotfload.nameunicode)` through some metatable or metamethod

I’d prefer something like

    local codepoints = luaotfload.aux.codepoints (fontname)
    for i = 1, #codepoints do
      local glyphname, codepoint = codepoints [i] [1], codepoints [i] [2]
    end

or even better

    local cb = function (glyphname, codepoint) do_something () ... end
    if not luaotfload.aux.iter_codepoints (fontname, cb) then
      --- not successful
    end

    local cb = function (acc, glyphname, codepoint)
      acc [#acc + 1] = { do_something (glyphname)
                       , do_something_else (codepoint) }
      ...
      return acc
    end
    local collected = luaotfload.aux.fold_codepoints (fontname, { }, cb)
    if not next (collected) then
      --- not successful
    end

This way we’d keep the iteration details entirely opaque and
could adapt them in whatever way we deem necessary. Users won’t
have to worry about Luaotfload or Fontloader versions.

> @phi-gamma what do you think?

Regarding https://github.com/gregorio-project/gregorio/issues/717
-- can that be considered solved?

**Comment by eroux** [comment]
Your second solution looks good indeed. But as you say, I think this can be considered fixed, the real issue here was the non-obviousness of the lazy filling of `resources.unicodes`, but I'm not sure it can be documented anywhere...
