### ISSUE TITLE
Broken ``tlig`` feature / ``addfeature()`` code requires update

### ISSUE THREAD

**Issue by rpfei74** [lualatex/luaotfload#309]
Recently, colons (:) started to appear as closing quotation marks (”) when setting Minion Pro as the main text font.

\documentclass{scrbook}
\usepackage[no-math]{fontspec}
%\setmainfont{Minion Pro}
\begin{document}
Bla: blu: bli:
\end{document}

The output with Minion Pro is correct with xelatex but not with lualatex.

**Comment by MacDevil** [comment]
After the recent update I noticed that, too.

Additionally, there is some very strange behavior regarding the LetterSpace feature: Please try the following MWE with and without the last line. It will throw an error:
```latex
\documentclass{scrartcl}

\usepackage{fontspec}
\setmainfont{Minion Pro}

\begin{document}
% This works (with false quotation mark instead of colon):
\addfontfeature{LetterSpace=50}
Hello: World!

% This will work:
CASI

% This won’t:
% CASIO

\end{document}
```

It will throw the following error:
```
error: ...TeX/2.9/tex/luatex/luaotfload/luaotfload-letterspace.lua:445: You can
not set field prev.next in a node of type glyph
```

**Comment by priyadarshan** [comment]
I am having exact same problems. I came to this ticket thanks to this sx question: http://tex.stackexchange.com/questions/283595/lualatex-unable-to-switch-off-ligatures-in-smallcaps

Since updating, I have been experiencing lots of `luaotfload-letterspace.lua: You cannot set field prev.next in a node of type glyph`. Before that, I was able to compile same files, with same fonts, with no issues.

**Comment by phi-gamma** [comment]
···<date: 2015-12-17, Thursday>···<from: MacDevil>···

> It will throw the following error:
> ```
> error: ...TeX/2.9/tex/luatex/luaotfload/luaotfload-letterspace.lua:445: You can
> not set field prev.next in a node of type glyph

This is tracked separately in issue #310.

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2015-12-17, Thursday>···<from: rpfei74>···

> Recently, colons (:) started to appear as closing quotation marks (”) when setting Minion Pro as the main text font
> 
> \documentclass{scrbook}
> \usepackage[no-math]{fontspec}
> %\setmainfont{Minion Pro}
> \begin{document}
> Bla: blu: bli:
> \end{document}

The ``tlig`` feature is broken. Here’s a minimal test file:
https://bitbucket.org/phg/lua-la-tex-tests/src/tip/plain/pln-features-14-tlig.tex

**Comment by phi-gamma** [comment]
I’ve sort of tracked the issue down; some secondary code needs
updating due to the revised ligature handling. Unfortunately,
I can’t fix it right aways due to some other issue with combined
substitution / ligature features (there’s only one: “tlig”, but
people seem to expect that to work above all else).

**Comment by vsrepo** [comment]
Thank you for your help. We have two major books almost ready to go to press. I could revert back to previous `luaotfload` version, but I would rather wait for update, as the new features are very much appreciated.

Please let me know if there is anything I could do to help, i.e. testing. Thank you again.

**Comment by phi-gamma** [comment]
···<date: 2015-12-17, Thursday>···<from: repository-tasks>···

> Thank you for your help. We have two major books almost ready
> to go to press.

Hans responded optimistically:

    http://mailman.ntg.nl/pipermail/ntg-context/2015/083836.html

But I can’t make any promises for another release this year.

>                 I could revert back to previous `luaotfload`
> version, but I would rather wait for update, as the new features
> are very much appreciated.

In theory you shouldn’t have to revert. Last year’s fontloader is
still available if you set the following configuration:

    [run]
        fontloader = tl2014

Maybe this gets you far enough already.

> Please let me know if there is anything I could do to help,
> i.e. testing. Thank you again.

Thanks for the offer. I’ll get back at you once I have something
to test.

**Comment by simifilm** [comment]
I think I've also been bitten by this bug. Where exactly do I have to put 
> [run]
        fontloader = tl2014

I put this in `luaotfload.conf` which is in my working directory, but it didn't seem to have any effect. That is on TL2015 on OSX,

**Comment by simifilm** [comment]
I'm seeing something similar with Stempel Garamond LT Pro – ' is replaced with ”. Could this be the same error? If so, where do I put `luaotfload.conf` on OSX? I tried different locations and nothing seems to have any impact.

**Comment by Lenchik** [comment]
@simifilm take a look here: https://github.com/wspr/fontspec/issues/222#issuecomment-166125526

**Comment by simifilm** [comment]
@Lenchik I tried that – no difference.

**Comment by phi-gamma** [comment]
Bisected. This is the offending changeset:
https://bitbucket.org/phg/context-mirror/commits/d7b51cfffa3d797c9a19d6cf5366150bcf032554

Patch sent upstream.

**Comment by phi-gamma** [comment]
Hans incorporated my patch so I think we’re good to go with
our hard-patched version. Please test with the new release
and reopen if needed.

**Comment by simifilm** [comment]
This has indeed fixed my issue. Thanks a lot.

**Comment by simifilm** [comment]
Do I see this correctly, that TeX ligatures don't work yet? For `fontspec` I have `Ligatures=TeX` enabled, but `--` is still rendered as `--`.

**Comment by phi-gamma** [comment]
···<date: 2015-12-23, Wednesday>···<from: Simon Spiegel>···

> Do I see this correctly, that TeX ligatures don't work yet? For `fontspec` I have `Ligatures=TeX` enabled, but `--` is still rendered as `--`.

Drat! Thanks for reporting.

Does the old loader work with the latest release? Here I get the
correct result with a ``luaotfload.conf`` like this:

    [run]
        fontloader = tl2014

**Comment by phi-gamma** [comment]
@simifilm fixed; new package is on its way to CTAN.

* The release: https://github.com/lualatex/luaotfload/releases/tag/v2.6-fix-4
* The fix: https://github.com/lualatex/luaotfload/commit/9320186751b6c6a1113f41331716d3b68d73af7a

That one was ugly …

**Comment by simifilm** [comment]
Hmm, I don't see any improvement with fix-4. `--` still remains unchanged.

**Comment by phi-gamma** [comment]
···<date: 2015-12-25, Friday>···<from: Simon Spiegel>···

> Hmm, I don't see any improvement with fix-4. `--` still remains unchanged.

Did you erase the font cache? (``luaotfload-tool --cache=erase``)

**Comment by simifilm** [comment]
> Did you erase the font cache? (``luaotfload-tool --cache=erase``)

That did the trick.

**Comment by phi-gamma** [comment]
···<date: 2015-12-25, Friday>···<from: Simon Spiegel>···

> > Did you erase the font cache? (``luaotfload-tool --cache=erase``)
> 
> That did the trick.

I’m quite relieved =)
