### ISSUE TITLE
Unable to print ligature-free smallcaps

### ISSUE THREAD

**Issue by priyadarshan** [lualatex/luaotfload#310]
When I installed the latest version of `luaotfload`, I started having issues with smallcaps.

No matter what I do, smallcaps are being printed with ligatures, even when instructed otherwise.

The exact situation is described on [this tex.stackexchange.com question](http://tex.stackexchange.com/questions/283595/lualatex-unable-to-switch-off-ligatures-in-smallcaps) by user gsl.

Basically, with new version I am unable to switch off ligatures when using smallcaps.

I am copying from that question, as I could not describe better:

The following MWE is using Minion, but I tried with many similar fonts: Dante, Merlo, Caslon, etc.

    % !TEX TS-program = LuaLaTeX
    
    \documentclass{article}
    \usepackage{fontspec}
    \defaultfontfeatures{Ligatures={NoRequired, NoCommon, NoContextual}}
    
    \newfontfamily\MinionSmallCaps
    [Ligatures={NoRequired, NoCommon, NoContextual},
    Letters={UppercaseSmallCaps,SmallCaps},
    LetterSpace=80,WordSpace=3]
    {MinionPro}
    
    \begin{document}
    \addfontfeatures{Ligatures={NoRequired, NoCommon, NoContextual}}
    \MinionSmallCaps Test is here [Minion]
    \end{document}

Environment:

    This is LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238) 
    fontspec-luatex.sty    2015/09/24 v2.4e
    fontspec-patches.sty    2015/09/24 v2.4e    
    luaotfload.sty    2015/12/09 v2.6

Results:

[![enter image description here][2]][2]

I am able to have the desired result, using the same text and same font, using InDesign:

[![enter image description here][3]][3]

InDesign settings:

[![enter image description here][4]][4]

How can one completely switch off ligatures while using smallcaps with LuaLaTeX?

---

**Edit 1**

Writing "testate" and using "Minionpro", as suggested by @ulrike-fischer throws an error:

    luaotfload-letterspace.lua:445: You cannot set field prev.next in a node of type glyph

The results is this one:

[![enter image description here][5]][5]

---
**Edit 2**

Using a similar free font, Cardo, with

    \CardoSmallCaps Testate is here [Cardo]

The result is this one:

[![enter image description here][6]][6]

The ligatures are off, although the Letters={UppercaseSmallCaps,SmallCaps} directive seems not to be respected perfectly.

---
**Edit 3**

As user egreg said, 

> It really seems a bug in `luaotfload`, if not in LuaTeX.

---
**Edit 4**
User egreg said

>  I write estate with Linux Libertine as font, I get no letter spacing in TAT, but an error with Minion Pro. So there's some problem when letters are kerned.

  [1]: http://tex.stackexchange.com/questions/54459/switching-off-ligatures-in-lualatex
  [2]: http://i.stack.imgur.com/725aQ.png
  [3]: http://i.stack.imgur.com/sjLe6.png
  [4]: http://i.stack.imgur.com/Jq7o9.png
  [5]: http://i.stack.imgur.com/jdY2R.png
  [6]: http://i.stack.imgur.com/NHIzP.png
  [7]: https://github.com/lualatex/luaotfload/issues/309

**Comment by priyadarshan** [comment]
This issue could be related to #309, although it is not quite similar.

**Comment by phi-gamma** [comment]
···<date: 2015-12-17, Thursday>···<from: Priyadarshan>···

> How can one completely switch off ligatures while using smallcaps with LuaLaTeX?

What do you mean “switch off” -- have you tried defining the font
without the “liga” feature?

> Writing "testate" and using "Minionpro", as suggested by @ulrike-fischer throws an error:
> 
>     luaotfload-letterspace.lua:445: You cannot set field prev.next in a node of type glyph

Probably my fault, I’ll investigate. A lot of things changed on
this front, causing node handling to be more delicate. Thanks for
reporting.

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2015-12-17, Thursday>···<from: Priyadarshan>···

> Writing "testate" and using "Minionpro", as suggested by
> @ulrike-fischer throws an error:
> 
>     luaotfload-letterspace.lua:445: You cannot set field prev.next in a node of type glyph

Interestingly, that error only occurs with the Luatex in Texlive.
With 0.87.0 it doesn’t.

**Comment by phi-gamma** [comment]
···<date: 2015-12-17, Thursday>···<from: Priyadarshan>···

> Writing "testate" and using "Minionpro", as suggested by @ulrike-fischer throws an error:
> 
>     luaotfload-letterspace.lua:445: You cannot set field prev.next in a node of type glyph

Ok, that crash is fixed.

**Comment by priyadarshan** [comment]
Thanks for that. Also, apologies for using Fontspec terminology, while I should have reported this within proper Luaotfload namespace.

**Comment by phi-gamma** [comment]
This turned out to be a regression in letterspacing. With the
current master the output is this:

![letterspace fixed](http://i.imgur.com/ArtCKN4.png)

**Comment by priyadarshan** [comment]
Very nice, thank you!

Would you want me to test it with other fonts as well?
Is there going to be a release soon(ish), perhaps even ad interim, ie not still meant for CTAN?
If not, I see from README one could compile it using Make. I could try that way.

Thank you so much for all your work. It is really appreciated, especially so close to the festivities!

**Comment by phi-gamma** [comment]
@priyadarshan New release has been uploaded. Please test and reopen if
necessary. We’ll continue next year.

**Comment by priyadarshan** [comment]
I will. Thank you so much for your work. Happy holidays!
