### ISSUE TITLE
colon output as quotation mark

### ISSUE THREAD

**Issue by ulilaube** [lualatex/luaotfload#311]
While working on another document I notices that a colon : in the LaTeX source was output as a
” U+201D RIGHT DOUBLE QUOTATION MARK in the pdf output. This did not happen before, so I started investigating. It boiled down to this MWE:

```latex
\documentclass{minimal}
\usepackage{fontspec}
\setmainfont{Minion Pro}
\begin{document}
a:b”c
\end{document}
```

The output in the PDF is  a”b”c instead of a:b”c. I am running TL2015 with luatex 0.80.

* removing the line `\setmainfont{Minion Pro}` thus falling back to `lmroman10-regular.otf` and the problem disappears.
* switching to `\setmainfont{Myriad Pro}` and the problem disappears as well.
* but keeping `\setmainfont{Minion Pro}` and switching from LuaLaTeX to XeteX (that does not use luaotfload) and the problem disappears. Thus I would conclude that my `minionpro-regular.otf` is fine.
* deleting ~/.texlive2015 and forcing luaotfload to recreate its caches changes nothing.

I then I looked at the MWE.log to check which packages and files have recently been changed.

```text
[...]
Package: luaotfload 2015/12/09 v2.6 OpenType layout system
Lua module: luaotfload-main 2015/12/09 2.60001 OpenType layout system.
Lua module: lualibs 2015-12-02 2.3 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2015-12-02 2.3 ConTeXt Lua libraries -- extended collection.
[...]
```

caught my attention as it was only a couple of days ago.
Then I cloned  `lualatex/luaotfload` locally and went back in time to the tag `v2.5-fix-4`.
And used `make tds` to  downgraded my TeX-tree via `texmf-local` to that version.
A `mktexlsr` and `rm ~/.texlive2015` later the MWE.pdf was built without the problem.

I will try to do a little bit more bisecting between v2.5-fix-4 and v2.6 but that might not happen this weekend.

**Comment by phi-gamma** [comment]
See issue #309
