### ISSUE TITLE
luaotfload | load : path lookup unsuccessful

### ISSUE THREAD

**Issue by simifilm** [lualatex/luaotfload#313]
This isn't really a bug, but something I just don't understand. I already posted this [tex.stackechange](http://tex.stackexchange.com/questions/283884/luaotfload-load-path-lookup-unsuccessful), but got no answer so far.

When I typeset documents with `LuaLaTeX` and OpenType fonts I regularly get messages like this in the `.log` file

     luaotfload | load : path lookup of "Palatino Linotype.ttf" unsuccessful,      
     falling back to file:(compiling luc: /usr/local/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotype.luc)(compiling luc:      
     /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotype.luc)(save: 
     /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotype.lua)(save: 
     /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotype.luc)
     luaotfload | load : path lookup of "Palatino Linotype.ttf" unsuccessful, falling back to file: \g__fontspec_family_PalatinoLinotype_int=\count161
     luaotfload | load : path lookup of "PalatinoLinotype.ttf" unsuccessful, falling back to file:(compiling luc: /usr/local/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotype.luc)(compiling luc: 
     /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotype.luc)(save: /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotype.lua)(save: /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotype.luc)
     luaotfload | load : path lookup of "PalatinoLinotype.ttf" unsuccessful, falling back to file:

There are several strange things about this:

- `LuaLaTeX` does actually compile the document with the defined font. Typesetting doesn't fail (which it normally does if `fontspec` fails to find a font).
- `/usr/local/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotype.luc` which is given as first fallback, doesn't exist.
- `/Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotype.luc` does exist, but it looks like it's recreated every time. At least, when I delete this directory before the `LuaLaTeX` run, it gets recreated.
- In the last part of this error message, simply no path is given, it just says `falling back to file:`

Contrary to the errors given, `LuaLaTeX/luaotfload` actually *does* seem to find the needed font file. So what is the meaning of this message then?

**Comment by phi-gamma** [comment]
···<date: 2015-12-21, Monday>···<from: Simon Spiegel>···

> When I typeset documents with `LuaLaTeX` and OpenType fonts I regularly get messages like this in the `log` file
> 
>      luaotfload | load : path lookup of "Palatino Linotypettf" unsuccessful,      
>      falling back to file:(compiling luc: /usr/local/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotypeluc)(compiling luc:      
>      /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotypeluc)(save: 
>      /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotypelua)(save: 
>      /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotypeluc)
>      luaotfload | load : path lookup of "Palatino Linotypettf" unsuccessful, falling back to file: \g__fontspec_family_PalatinoLinotype_int=\count161
>      luaotfload | load : path lookup of "PalatinoLinotypettf" unsuccessful, falling back to file:(compiling luc: /usr/local/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotypeluc)(compiling luc: 
>      /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotypeluc)(save: /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotypelua)(save: /Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatinolinotypeluc)
>      luaotfload | load : path lookup of "PalatinoLinotypettf" unsuccessful, falling back to file:
> 
> There are several strange things about this:
> 
> - `LuaLaTeX` does actually compile the document with the defined font Typesetting doesn't fail (which it normally does if `fontspec` fails to find a font)

That’s not strange. The document compiles despite other packages
filling the log with noise as well.

> - `/usr/local/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotypeluc` which is given as first fallback, doesn't exist
> - `/Users/simi/Library/texlive/2015/texmf-var/luatex-cache/generic/fonts/otf/palatino-linotypeluc` does exist, but it looks like it's recreated every time At least, when I delete this directory before the `LuaLaTeX` run, it gets recreated

Cache paths are created if nonexistent and writable.

> - In the last part of this error message, simply no path is given, it just says `falling back to file:`

That is no error message. It’s a diagnostic caused by the lookup
Fontspec uses which is by default unqualified so Luaotfload needs
to figure out what Fontspec actually wants. Testing for whether
an existing path in the filesystem is requested is just one of
the possible steps. The font is then found using another
mechanism.

**Comment by simifilm** [comment]
That is no error message. It’s a diagnostic caused by the lookup
      Fontspec uses which is by default unqualified so Luaotfload needs
      to figure out what Fontspec actually wants. 

If this is not an error message, the phrasing is not optimal, because, as you say, it creates a lot of noise, and it least for me it is definitely not clear that `luaotfload` is actually successful in loading the font. If the last line `falling back to file:` means that it loads the font file, this should be made more explicit.

**Comment by simifilm** [comment]
Does the closing of the bug mean that there's no intention of improving these messages? I think they're really not very helpful, at the moment. As the lack of reaction on tex.stackexchange indicates, no one really seems to know what they mean. I think it would be useful to at least clearly indicate that a font has been successfully loaded in the end.

**Comment by phi-gamma** [comment]
···<date: 2015-12-21, Monday>···<from: Simon Spiegel>···
> Does the closing of the bug mean that there's no intention of
> improving these messages? I think they're really not very
> helpful, at the moment.

There’s another item pending:

    https://github.com/lualatex/luaotfload/issues/263

This is closely related since the ``anon`` style lookup is how
most accesses by Fontspec are handled. The goal is to provide
a mechanism that resembles Xetex’s by default but can be
configured by the user. (Giving preference to path lookups is a
horrible mess IMO so we should at least provide means to opt out
of it.)

I expect the status messages to change in the course of this
planned overhaul but ATM I can’t say exactly when it’ll be ready.

>                         As the lack of reaction on
> tex.stackexchange indicates, no one really seems to know what
> they mean.

I’d supply some reaction if that idiotic forum software would
stop treating me as a robot. The issue has been known for over a
year:

    http://meta.tex.stackexchange.com/questions/4410

without anyone showing the willingness to fix it. In any case,
tex.sx is by no means authoritative, the asker can always consult
the relevant mailing lists.
