### ISSUE TITLE
non-printing characters in the OpenType layout of LuaLaTeX

### ISSUE THREAD

**Issue by ClintEastwood** [lualatex/luaotfload#317]
I discovered a probable bug in the LuaLaTex OpenType layout code: a couple of non-printing characters (such as 200c, 200d, 200e 200f and so on) do in fact show up in the pdf, even though they should not. I so far used `\catcode"200E=9` to ignore them. This is alright for 200e and 200f, but not for 200c and 200d because through ignoring them they also lose their effect, in the case of 200c and 200d the effect should be joining two characters or separating them, respectively.

![khane-ye](https://cloud.githubusercontent.com/assets/1502050/12079180/15b8a98c-b230-11e5-8ad5-2ae98a94701c.png)

I also realised that not every font prints these characters: Scheherazade, for example does not, but this is merely because it does not have them as a glyph anyway.

Maybe, I thought, this is a feature and not a bug, because after all it is good sometimes to be able to visualise invisible characters -- but then one should also be able to turn off that feature.

I reported the error also described on tex.sx: http://tex.stackexchange.com/q/285719/12277

The MWE:

```
% !TEX TS-program = lualatexmk
\documentclass{article}
\usepackage{fontspec}
    \newfontfamily\arabicfont[  Script=Arabic,%
                            Numbers=Arabic,%
                            Scale=MatchLowercase%
                                ]{ArabicTypesetting}%
\newcommand{\arabtext}[1]       % Arabic inside LTR
    {\bgroup\textdir TRT\arabicfont #1\egroup}    
\begin{document}
\arabtext{خانه‌ای}
\end{document}
```

**Comment by phi-gamma** [comment]
···<date: 2016-01-03, Sunday>···<from: ClintEastwood>···

> I discovered a probable bug in the LuaLaTex OpenType layout
> code: a couple of non-printing characters (such as 200c, 200d,
> 200e 200f and so on) do in fact show up in the pdf, even though
> they should not I so far used `\catcode"200E=9` to ignore them
> This is alright for 200e and 200f, but not for 200c and 200d
> because through ignoring them they also lose their effect, in the
> case of 200c and 200d the effect should be joining two characters
> or separating them, respectively

Weird. For comparison, here’s a test for Context

    https://bitbucket.org/phg/lua-la-tex-tests/src/tip/context/cnt-arabic-2.tex

There’s no change in behavior between the old and the new
fontloader. Here’s the corresponding output:

![arab text with visible spacing](http://i.imgur.com/EpkIGkF.png)

This definitely looks different: The vertical bar is more compact
vertically and there’s some extra spacing. But AFAICT it emits
the same number of distinct glyphs as Luaotfload; not being
familiar with Arabic I assume this is the same defect?

**Comment by phi-gamma** [comment]
···<date: 2016-01-25, Monday>···<from: phg>···

> ···<date: 2016-01-03, Sunday>···<from: ClintEastwood>···
> 
> > I discovered a probable bug in the LuaLaTex OpenType layout
> > code: a couple of non-printing characters (such as 200c, 200d,
> > 200e 200f and so on) do in fact show up in the pdf, even though
> > they should not I so far used `\catcode"200E=9` to ignore them
> > This is alright for 200e and 200f, but not for 200c and 200d
> > because through ignoring them they also lose their effect, in the
> > case of 200c and 200d the effect should be joining two characters
> > or separating them, respectively
> 
> Weird. For comparison, here’s a test for Context
> 
>     https://bitbucket.org/phg/lua-la-tex-tests/src/tip/context/cnt-arabic-2.tex
> 
> There’s no change in behavior between the old and the new
> fontloader. Here’s the corresponding output:
> 
> ![arab text with visible spacing](http://i.imgur.com/EpkIGkF.png)
> 
> This definitely looks different: The vertical bar is more compact

Scratch that; I made a mistake and used a different font. With
the arabtype.ttf that ships with Windows 7 I indeed get identical
output with Context.[0] Thus, if this is a bug, at least it’s not
ours ;)

![arab output with arab type](http://i.imgur.com/5NKrq23.png)

[0] There appears to be a minute difference in spacing caused
    by the different set of features applied by Luaotfload for
    Arabic script.

**Comment by ClintEastwood** [comment]
What do you mean by "if this is a bug, at least it’s not ours"? I don't quite understand. Do you mean to say that it is due to the fonts I used -- in the present case `arabtype` -- that these non-printing characters occur? I am asking, because Khaled Hosny specifically told me that:
>> That is a question for whoever is developing the OpenType layout code you [=me] are using with LuaTeX, they are clearly not following the OpenType and Unicode specs.

So he denies that the printing of these characters is due to the font. If it is also not due to `luaotfload`, then, where do I have to report this issue? Any idea?

The point is that on is literally unable to use LuaTeX and ConTeX for Persian at all if one needs to use a specific font, because Persian orthography relies on the usage of these characters. A friend fo mine, for example, now has to use a different (less suitable) font for her publication.

**Comment by phi-gamma** [comment]
···<date: 2016-01-25, Monday>···<from: ClintEastwood>···

> What do you mean by "if this is a bug, at least it’s not ours"?

It occurs in Context too under the same conditions. Ergo: bug in
the fontloader. We have a policy of not fixing those unilaterally
except when there’s a compelling reason.

>> That is a question for whoever is developing the OpenType
>> layout code you [=me] are using with LuaTeX, they are clearly not
>> following the OpenType and Unicode specs.

He’s saying the same thing: It’s a fontloader issue. I’ll forward
it to the Context list, cause that’s where the development
happens.

> The point is that on is literally unable to use LuaTeX and
> ConTeX for Persian at all if one needs to use a specific font,

Those spurious characters in your example, is that specific to
Persian? Judging from the past discussions on the mailing list
there’s not that many Persian users so the issue might have been
missed easily. Can you provide details regarding the expected
output?

**Comment by ClintEastwood** [comment]
Ok, thanks. I do understand now what you meant.

About these characters. There are three reasons I can think of why the current state of LuaTeX/ConTeXt (i.e. the fact that non-printing characters show up in the pdf even though the should not) is bad:

1. Modern Persian orthography sometimes requires the use of the "zero-width-non-joiner" (ZWNJ : U+200C). Explanation: Persian (and Arabic) letters often connect to the letters that follow and/or precede them: e.g.  اسبها : here, the first letter ا is isolated, whereas the rest are connected. Sometimes, however, one likes to keep them from connecting with each other. Here in this case, one would rather like to write اسب‌ها. Note that there is no space between the two characters (compare it with اسب ها where there is in fact a whitespace). The fact that modern Persian orthography sometimes requires this also explains why the ZWNJ is on the normal Persian keyboard! The current state of LuaTeX/ConTeXt however represents the actually invisible character by a line (as in my image above and the one displayed below).

2. If one wants to type the name of God (Allāh), one needs to press four keys: ه + ل + ل + ا . The result, however adds extra-diacritical symbols automatically (this depends on the font, actually). So by pressing four keys we do not just get the four letters joined to each other (as in ال‍له) but the following: الله -- you see the difference, i.e. the diacritical marks above the one stroke? This is ok for normal texts, because the diacritical signs need to be added for displaying the name of God properly -- if you are, however, an academic, you often may prefer they were absent -- but there is no way to keep the from appearing other than using a "zero-width-joiner" (ZWJ : U+200D). AT leats this is the most convenient way, because it breaks the automatic addition of the diacritical signs. As a note aside: The ZWJ is also very often used in Indic script, as wikipedia told me.

3. I recognised that Arabic and Persian texts are often full with the "right-to-left mark" (U+200F) and sometimes even the left-to-right mark (U+200E). I don't know the reason why. But when you copy and paste stuff (e.g. from the internet) and run LuaTeX on it, you often get these symbols. It would be tiresome to have to go through the entire text just to check that these symbols which should be invisible are printed.

So these are my top-three reasons why this is actually a not so nice situation for me and, incidentally, for *everyone* who wants to write Persian (or Indic script).

So, in order to specifically answer your question: These symbols are not specific to Persian, as they can occur in other languages, too. However, some languages (among them Persian) really require their usage. As for the expected output: They should not be visible at all. But fonts usually can indicate them by lines with a small arrow on top of the line (for the right-to-left and left-ot-right marks) or a cross on top of the line (for the ZWJ) or simply a line (for ZWNJ). This, however, should be on option, so that on *can* make them visible.

See also here: ![symbols for invisible characters](https://www.microsoft.com/typography/otfntdev/zwnj.gif)

**Comment by u-fischer** [comment]
closing here as it is referenced in the related https://github.com/u-fischer/luaotfload/issues/63.
