### ISSUE TITLE
Cap ligatures in Adobe Arno Pro won't compile

### ISSUE THREAD

**Issue by translit** [lualatex/luaotfload#319]
Hi and best wishes for 2016.

I've got an issue with the 'RA' ligature.

The font I use – [Adobe Arno Pro][1] – contains a beautiful liason between the bottom serifs of capital R and A that used to complie just fine. But after updating my MacTeX installation, LuaTeX rev. 39057 stumbles: `This can't happen (linebreak_tail).` 

Here's the minimum working example:

    \documentclass[]{memoir}
    \usepackage{fontspec}
    \setmainfont[]{Arno Pro}
    \newcommand\allcapsspacing[1]{{\addfontfeature{LetterSpace=7.5}#1}}
    \begin{document}
    {\Huge \allcapsspacing{FOOBRA}}\\[\baselineskip]
    \end{document}

The code compiles well if I switch the font or lowercase `FOOBRA`.

Is this a LuaLaTeX bug?

  [1]: http://blogs.adobe.com/typblography/files/2013/11/ArnoPro-Regular_GC.pdf

**Comment by phi-gamma** [comment]
Hi,

thanks for the report. Best wishes for the year to you too.

···<date: 2016-01-04, Monday>···<from: translit>···

> I've got an issue with the 'RA' ligature

Looks like I broke it :/ I’ve included a minimal failing example
in the test repo:

    https://bitbucket.org/phg/lua-la-tex-tests/src/tip/plain/pln-letterspace-11-liga.tex

I’ll investigate.

> Is this a LuaLaTeX bug?

Nope, the letterspacing code is Luaotfload only.

>   [1]: http://blogsadobecom/typblography/files/2013/11/ArnoPro-Regular_GCpdf

That URL got muddled but I could reconstruct it:

    http://blogs.adobe.com/typblography/files/2013/11/ArnoPro-Regular_GC.pdf

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2016-01-04, Monday>···<from: translit>···

> I've got an issue with the 'RA' ligature
> …
> The code compiles well if I switch the font or lowercase `FOOBRA`

I’ve cooked something up. Could you test this patch to
``luaotfload-letterspace.lua``?

    https://github.com/phi-gamma/luaotfload/commit/8481fc2a3da5571d3817fe7797f9191543e7dcc8

Looks like invalid node sequences were being passed to Luatex
after letterspacing ligature components.

**Comment by phi-gamma** [comment]
···<date: 2016-01-04, Monday>···<from: translit>···

> I've got an issue with the 'RA' ligature
> 
> The font I use – [Adobe Arno Pro][1] – contains a beautiful
> liason between the bottom serifs of capital R and A that used to
> complie just fine But after updating my MacTeX installation,
> LuaTeX rev 39057 stumbles: `This can't happen (linebreak_tail)` 

The latest release contains the patch; did the situation improve?

**Comment by phi-gamma** [comment]
Assumed fixed, closing. Please reopen if appropriate.
