### ISSUE TITLE
selecting fonts by filename no longer works

### ISSUE THREAD

**Issue by mewtant** [lualatex/luaotfload#321]
While trying to fix a font I did not want to install (https://tex.stackexchange.com/q/290261/7883), I could not select it by filename, something I was able to do with another font as recently as 27 January 2016.  I update TeX Live every day or two and unfortunately don't remember which packages were affected by the latest update.

**Comment by phi-gamma** [comment]
···<date: 2016-01-30, Saturday>···<from: mewtant>···

> While trying to fix a font I did not want to install
> (https://texstackexchangecom/q/290261/7883), I could not select
> it by filename

Without a minimal example one can only speculate as to what
happens.

>                 something I was able to do with another font as
> recently as 27 January 2016  I update TeX Live every day or two
> and unfortunately don't remember which packages were affected by
> the latest update

There was no Luaotfload release in that time frame, the most
recent one was published on 2016-01-15. In any case, there’s a
small chance the font cache gets in the way. Did you run

    luaotfload-tool --cache=erase

followed by a database update?

Which version are you running (``luaotfload-tool --version``)?

Can ``luaotfload-tool`` locate the file?

    luaotfload-tool --find=file:MyBeautifulFont.otf
    luaotfload-tool --find=file:MyBeautifulFont.otf --info
    luaotfload-tool --list=* | grep -i beautiful

(Adapt the search strings, of course!)

**Comment by phi-gamma** [comment]
Assumed fixed, closing. Please reopen if appropriate.

**Comment by mewtant** [comment]
My example was the answer at https://tex.stackexchange.com/q/290261/7883, though you have to substitute `\setmainfont{Wyld.otf}` for `\setmainfont{Wyld}` (I didn’t want to confuse the O.P. with this other issue).  However, it no longer fails since `fontspec` 2.5a made its way to the CTAN mirrors here.

**Comment by phi-gamma** [comment]
Can’t reproduce; minimal example: https://bitbucket.org/phg/lua-la-tex-tests/src/7636040abb24fce4848062eb67a7b09447441143/plain/pln-load-font-7-wyld.tex
