### ISSUE TITLE
luaotfload does not follow symlinks

### ISSUE THREAD

**Issue by fgrsnau** [lualatex/luaotfload#325]
If the `~/.fonts` directory is symlinked to a different directory, luaotfload fails to index fonts in this location. Only scanning is affected. Once the fonts are included in the luaoftload font database everthing works as expected.

In file `luaotfload-database.lua` the functions `find_files_indeed` and `find_files` use the function `lfsisdir` and thus simply skip symlinks. Something like `lfslisdir` (in the sense of `stat` vs `lstat`) should have been used.

**Comment by phi-gamma** [comment]
···<date: 2016-04-04, Monday>···<from: Stefan Haller>···

Thanks for reporting!

> If the `~/.fonts` directory is symlinked to a different
> directory, luaotfload fails to index fonts in this location. Only
> scanning is affected. Once the fonts are included in the
> luaoftload font database everthing works as expected.

Scanning works here:

    ~ ▶ luaotfload-tool -V
    
    luaotfload-tool:
            Luaotfload font management and diagnostic utility.
            License: GNU GPL v2.0.
            Report problems to <https://github.com/lualatex/luaotfload/issues>
    
    luaotfload-tool version: "2.6"
    Revision: "55799dad5b8a2716aea1cfee28b4ce093e587f8a"
    Lua interpreter: stock; version "Lua 5.2"
    Luatex version: 0.89.4
    Platform: type=unix name=linux
        +  machine: x86_64
        + nodename: phlegethon
        +  release: 4.1.19-1-lts
        +  sysname: Linux
        +  version: #1 SMP Sun Mar 6 09:23:49 CET 2016
    Index: version="55799dad5b8a2716aea1cfee28b4ce093e587f8a
    ~ ▶ [ -d .fonts ] || echo "nope" 2>&1
    ~ ▶ luaotfload-tool -uv
    luaotfload | db : Updating the font names database.
    luaotfload | db : Scanning TEXMF for fonts...
    luaotfload | db : Scanning system fonts...
    luaotfload | db : Scanning 3200 collected font files ...
    ~ ▶ luaotfload-tool --list '*' >/tmp/fonts-content-before
    ~ ▶ mv .fonts actual-home-fonts
    ~ ▶ luaotfload-tool -uv
    luaotfload | db : Updating the font names database.
    luaotfload | db : Scanning TEXMF for fonts...
    luaotfload | db : Scanning system fonts...
    luaotfload | db : Scanning 2595 collected font files ...
    ~ ▶ ln -s actual-home-fonts .fonts
    ~ ▶ readlink -f .fonts
    /home/phg/actual-home-font
    ~ ▶ luaotfload-tool -uv
    luaotfload | db : Updating the font names database.
    luaotfload | db : Scanning TEXMF for fonts...
    luaotfload | db : Scanning system fonts...
    luaotfload | db : Scanning 3200 collected font files ...
    ~ ▶ luaotfload-tool --list '*' >/tmp/fonts-content-after
    ~ ▶ diff -q /tmp/fonts-content-before /tmp/fonts-content-after
    ~ ▶ 

What does ``readlink ~/.fonts`` return?
What does ``luaotfload -V`` yield for you?

Best,
Philipp

**Comment by phi-gamma** [comment]
I’ve just given this another go because I wasn’t sure: There’s no bug.
In fact, ``lfs.isdir()`` does follow links, as does ``lfs.attributes()`` if
called on a symlink path. Try this and you’ll see:

    #!/usr/bin/env texlua
    print (">>", lfs.isdir("/home/MYUSER/.fonts") and "dir" or "nope")
    print (">>", lfs.attributes("/home/MYUSER/.fonts", "mode"))
    print (">>", lfs.attributes("/home/MYUSER/.fonts"))

Consequently, Luaotfload correctly finds fonts if ``~/.fonts`` or anything
under it are just symlinks.

Please reopen if you have further data.
