### ISSUE TITLE
missing ligature

### ISSUE THREAD

**Issue by hvoss49** [lualatex/luaotfload#326]
In the first word the ligature is missing. In the second one it is ok.
It works fine for xetex and context.

```
\input luaotfload.sty
\font \foo = file:AccanthisADFStdNo3-Regular.otf at 12pt
\foo
Reinstoffen
Reinstoffe
\bye
```

> This is LuaTeX, Version beta-0.95.0 (TeX Live 2016)  (format=luatex 2016.4.9)  9 APR 2016 22:35

**Comment by phi-gamma** [comment]
Hi,

thanks for the report.

I had a quick look at the example using the pre-release
fontloader. It is indeed broken, but AFAICS only in node
mode. Here’s an example that shows the difference:

    https://bitbucket.org/phg/lua-la-tex-tests/src/8fc4dd9e3b5cb70b838d23567f2216df15c01a38/plain/pln-features-16-liga.tex

The result looks like this:

![Demo imagery](http://i.imgur.com/GeewwSp.png)

···<date: 2016-04-09, Saturday>···<from: hvoss49>···

> In the first word the ligature is missing. In the second one it is ok.
> It works fine for xetex and context.

The bug occurs in the latest Context too if you enable the same
set of features as Luaotfload does by default:

    https://bitbucket.org/phg/lua-la-tex-tests/src/b85ea16e9c12c0c673307e0e75200459fd1f7d9b/context/cnt-features-14-liga.tex

I’ll forward this upstream.

Best,
Philipp

**Comment by phi-gamma** [comment]
@hvoss49 Did you try the 2.7 / pretest fontloader?

**Comment by hvoss49** [comment]
Yes, everything is fine now. Thanks
