### ISSUE TITLE
luaotfload changes the file mode creation mask

### ISSUE THREAD

**Issue by gdetrez** [lualatex/luaotfload#329]
I wanted to understand why minted cache directory were created with strange permission and I found out that it was the (indirect) loading of luaotfload that changed the file mode creation mask.

I made-up this small example to confirm it:
```latex
\documentclass{article}

\immediate\write18{umask}
\usepackage{luaotfload}
\immediate\write18{umask}

\begin{document}
\immediate\write18{mkdir \jobname}
\end{document}
```

When building with `lualatex --shell-escape test.tex`, this is the output:

```
This is LuaTeX, Version beta-0.79.1 (TeX Live 2014) (rev 4971) 
 \write18 enabled.
(./test.tex
LaTeX2e <2011/06/27>
Babel <3.9k> and hyphenation patterns for 76 languages loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))0002

(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload.sty
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/luatex.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/luatex-loader.sty
(/usr/share/texlive/texmf-dist/scripts/oberdiek/oberdiek.luatex.lua)))
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase-compat.sty)
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase-modutils.sty
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase-loader.sty
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase.loader.lua))
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/modutils.lua))
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase-regs.sty)
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase-attr.sty
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/attr.lua))
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase-cctb.sty
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/cctb.lua))
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/luatexbase-mcb.sty
(/usr/share/texlive/texmf-dist/tex/luatex/luatexbase/mcb.lua)))
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload.lua)
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-fontloader.lua)(
using write cache: /home/gregoire/.texlive2013/texmf-var/luatex-cache/generic)(u
sing read cache: /usr/share/texlive/texmf-var/luatex-cache/generic /home/gregoir
e/.texlive2013/texmf-var/luatex-cache/generic)
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-override.lua)
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-loaders.lua)
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-database.lua)
luaotfload | cache : Caching of name: lookups active.
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-colors.lua)
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-features.lua)
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-letterspace.lua)
(/usr/share/texlive/texmf-dist/tex/luatex/luaotfload/luaotfload-auxiliary.lua))0000

(./test.aux) (./test.aux))
 287 words of node memory still in use:
   2 hlist, 1 vlist, 1 rule, 2 glue, 1 kern, 4 attribute, 40 glue_spec, 4 attrib
ute_list, 2 write nodes
   avail lists: 2:7,3:1,6:3,7:1,9:1
No pages of output.
Transcript written on test.log.
```

It's a bit buried but it shows that the mask is 0002 before loading luaotfload and 0000 after.

**Comment by phi-gamma** [comment]
···<date: 2016-04-13, Wednesday>···<from: Grégoire Détrez>···

> I wanted to understand why minted cache directory were created
> with strange permission and I found out that it was the
> (indirect) loading of luaotfload that changed the file mode
> creation mask.

This was a bug in Luatex, not Luaotfload, that has been fixed for
ages.

> This is LuaTeX, Version beta-0.79.1 (TeX Live 2014) (rev 4971) 

Please update to a recent TeX live.

Best,
Philipp

**Comment by eg9** [comment]
I tested the example with TeX Live 2015; I see no difference.

    > lualatex -shell-escape testmask
    This is LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238) 
     \write18 enabled.
    (./testmask.tex
    LaTeX2e <2016/02/01>
    Babel <3.9q> and hyphenation patterns for 1 language(s) loaded.
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/usr/local/texlive/2015/texmf-dist/tex/latex/base/size10.clo))0022
    
    (/usr/local/texlive/2015/texmf-dist/tex/luatex/luaotfload/luaotfload.sty(using w
    rite cache: /Users/enrico/Library/texlive/2015/texmf-var/luatex-cache/generic)(u
    sing read cache: /usr/local/texlive/2015/texmf-var/luatex-cache/generic /Users/e
    nrico/Library/texlive/2015/texmf-var/luatex-cache/generic)
    luaotfload | main : initialization completed in 0.364 seconds)0000
     (./testmask.aux)
    (./testmask.aux))
     278 words of node memory still in use:
       2 hlist, 1 vlist, 1 rule, 2 glue, 3 attribute, 40 glue_spec, 3 attribute_list
    , 2 write nodes
       avail lists: 2:7,3:1,6:3,7:1,9:1
    No pages of output.
    Transcript written on testmask.log.

**Comment by phi-gamma** [comment]
···<date: 2016-04-14, Thursday>···<from: eg9>···

> I tested the example with TeX Live 2015; I see no difference.

Tracker item 956; in trunk since revision 5624. Not in TL yet, I
remembered that wrong, sorry.

Best,
Philipp
