### ISSUE TITLE
crash upon Type1 fonts (TL2016 pretest)

### ISSUE THREAD

**Issue by dohyunkim** [lualatex/luaotfload#334]
```tex
\input luaotfload.sty
\font\1=cmr10 at 10pt \1
test.
\bye
```
gives a fatal error
```
kpathsea:make_tex: Invalid fontname `"cmr10"', contains '"'

! error:  (file "cmr10") (type 3): font "cmr10" at 600 not found
!  ==> Fatal error occurred, no output PDF file produced!
```
which might be related to `rewrite_fontname` function in luaotfload-auxiliary.lua. AFAIR, there was no such issue in TL2015. I'm curious about what has changed  since then.

Anyway, inserting a conditional as follows seems to solve the issue. Not sure whether this patch is optimal. Instead, we may check special characters in `specification`.
```lua
  if tfmdata.encodingbytes == 2 then
    tfmdata.name = [["]] .. specification .. [["]]
  end
```

**Comment by phi-gamma** [comment]
···<date: 2016-04-19, Tuesday>···<from: Dohyun Kim>···

> ```tex
> \input luaotfload.sty
> \font\1=cmr10 at 10pt \1
> test.
> \bye
> ```
> gives a fatal error
> ```
> kpathsea:make_tex: Invalid fontname `"cmr10"', contains '"'
> 
> ! error:  (file "cmr10") (type 3): font "cmr10" at 600 not found
> !  ==> Fatal error occurred, no output PDF file produced!
> ```
> which might be related to `rewrite_fontname` function in luaotfload-auxiliary.lua. AFAIR, there was no such issue in TL2015. I'm curious about what has changed  since then.

Beats me. Perhaps some extra protection for strings in path
lookups? The Lua side of loading AFM & Co. hasn’t changed much
AFAICT.

> Anyway, inserting a conditional as follows seems to solve the issue. Not sure whether this patch is optimal. Instead, we may check special characters in `specification`.
> ```lua
>   if tfmdata.encodingbytes == 2 then
>     tfmdata.name = [["]] .. specification .. [["]]
>   end
> ```

Why ``encodingbytes``, though? According to the manual, this
could be set deliberately for Type1 fonts. Thus I’ve changed the
check for ``data.properties.format`` (could be just
``data.format`` I think). In practice, of course, it should make
very little difference.

Thanks for spotting this,
Philipp
