### ISSUE TITLE
luaotfload-tool is broken

### ISSUE THREAD

**Issue by eg9** [lualatex/luaotfload#337]
After today's (2016-04-22) update of the 2016 TeX Live pretest distribution (Mac OS X, not MacTeX), I ran

    luaotfload-tool -u -vvv

which stopped with the following message

    ...texmf-dist/tex/luatex/luaotfload/luaotfload-database.lua:2733: attempt to compare number with nil

Here's the version information

    > tlmgr info luaotfload
    package:     luaotfload
    category:    Package
    shortdesc:   OpenType 'loader' for Plain TeX and LaTeX
    longdesc:    The package adopts the TrueType/OpenType Font loader code provided in ConTeXt, and adapts it to use in Plain TeX and LaTeX. It works under LuaLaTeX only.
    installed:   Yes
    revision:    40655
    sizes:       src: 145k, doc: 417k, run: 4641k, bin: 5k
    relocatable: No
    cat-version: 2.7
    cat-date:    2016-04-21 11:09:36 +0200
    cat-license: gpl2
    cat-topics:  font-use luatex
    collection:  collection-luatex

**Comment by jfbu** [comment]
mentioned also at https://github.com/lualatex/luaotfload/issues/327#issuecomment-213286413 (I cross link in case people follow the two issues)

**Comment by u-fischer** [comment]
line 2733 compares pfmweight > 500, pfmweight is nil for some fonts. it works again if one sets in line 2707  ` local pfmweight         = entry.pfmweight or 0` (but I have no idea what is a good default value).

**Comment by dohyunkim** [comment]
https://github.com/lualatex/luaotfload/blob/master/src/luaotfload-database.lua#L3540
```
 names.version = 2.6
```
should be 
```
 names.version = 2.7
```

**Comment by phi-gamma** [comment]
···<date: 2016-04-22, Friday>···<from: Dohyun Kim>···

> https://github.com/lualatex/luaotfload/blob/master/src/luaotfload-database.lua#L3540
> ```
>  names.version = 2.6
> ```
> should be 
> ```
>  names.version = 2.7

That’s probably it. My fault, sorry. Did anyone remove the cache?

    luaotfload-tool --cache=erase

A forced update might do as well.

I’ll fix the versioning.

**Comment by u-fischer** [comment]
Removing the cache works. Didn't thought about it yesterday -- was too late. The combo-fonts are neat, but there is a closing quote missing in the docu. Also as a german I think it would be better to use/show braces instead of (perhaps active) quotes.

**Comment by phi-gamma** [comment]
···<date: 2016-04-23, Saturday>···<from: u-fischer>···

> Removing the cache works.

Neat.

>                           Didn't thought about it yesterday --
> was too late. The combo-fonts are neat, but there is a closing
> quote missing in the docu.

Thanks, fixed.

>                            Also as a german I think it would be
> better to use/show braces instead of (perhaps active) quotes. 

In the examples? They both have the same effect, so we’ve been
using them interchangeably in the manual.

**Comment by jfbu** [comment]
just to confirm that after modifying luaotfload-database.lua#L3540 to hold ` names.version   = 2.7` then doing `luaotfload-tool --cache=erase` the 

```luaotfload-tool -u -vvv```

has now completed successfully on my system, with today's tlpretest update (april 24, 10:00 AM CEST)

**Comment by jfbu** [comment]
However something surprises me, as I got :

```bash
$ luaotfload-tool --cache=erase

$ luaotfload-tool -u -vvv
luaotfload | util : Setting the log level to 3.
luaotfload | util : Task completed successfully.
luaotfload | db : Updating the font names database.
luaotfload | db : Font names database loaded from /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names/luaotfload-names.luc
luaotfload | db : Loading took 16 ms.
luaotfload | db : Version mismatch; expected 2.700, got 2.600.
luaotfload | db : Force rebuild.
luaotfload | db : Updating the font names database forcefully.
```
thus it looks as if the `--cache=erase` did not do what I thought it would.

**Comment by jfbu** [comment]
fwiw, I paste here complete Terminal output

```bash
$ luaotfload-tool -u -vvv
luaotfload | util : Setting the log level to 3.
luaotfload | util : Task completed successfully.
luaotfload | db : Updating the font names database.
luaotfload | db : Font names database loaded from /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names/luaotfload-names.luc
luaotfload | db : Loading took 16 ms.
luaotfload | db : Version mismatch; expected 2.700, got 2.600.
luaotfload | db : Force rebuild.
luaotfload | db : Updating the font names database forcefully.
luaotfload | db : Blacklisted file "spltfgbd.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisted file "spltfgbi.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisted file "spltfgit.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisted file "spltfgrg.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisting 4 files and directories.
luaotfload | db : Whitelisting 0 files.
luaotfload | db : Scanning TEXMF for fonts...
luaotfload | db : Path “.” matches $PWD (“/Users/xxxxxx”), skipping.
luaotfload | db : Path “.” matches $PWD (“/Users/xxxxxx”), skipping.
luaotfload | db : Path “.” matches $PWD (“/Users/xxxxxx”), skipping.
luaotfload | db : Initiating scan of 515 directories.
luaotfload | db : Collected 2490 files.
luaotfload | db : Scanning system fonts...
luaotfload | db : Searching in static system directories...
luaotfload | db : Collected 429 files.
luaotfload | db : Scanning 2919 collected font files ...
luaotfload | db : Scanned 2919 files, 1674 new.
luaotfload | db : Found 2919 font files; 1674 new, 0 stale entries.
luaotfload | db : Creating filename map.
luaotfload | db : Analyzing families.
luaotfload | db : Analyzing shapes, weights, and styles.
luaotfload | db : Ordering design sizes.
luaotfload | db : Rebuilt in 10186 ms.
luaotfload | db : Font index saved at ...
luaotfload | db : Gzip: /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names/luaotfload-names.lua.gz
luaotfload | db : Byte: /usr/local/texlive/2016/texmf-var/luatex-cache/generic/names/luaotfload-names.luc
luaotfload | cache : Lookup cache saved.
luaotfload | cache : Lookup cache emptied.
luaotfload | db : Blacklisted file "spltfgbd.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisted file "spltfgbi.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisted file "spltfgit.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisted file "spltfgrg.ttf" via "/usr/local/texlive/2016/texmf-dist/tex/luatex/luaotfload/luaotfload-blacklist.cnf".
luaotfload | db : Blacklisting 4 files and directories.
luaotfload | db : Whitelisting 0 files.
luaotfload | db : Scanning TEXMF for fonts...
luaotfload | db : Path “.” matches $PWD (“/Users/xxxxxx”), skipping.
luaotfload | db : Path “.” matches $PWD (“/Users/xxxxxx”), skipping.
luaotfload | db : Path “.” matches $PWD (“/Users/xxxxxx”), skipping.
luaotfload | db : Initiating scan of 515 directories.
luaotfload | db : Collected 2490 files.
luaotfload | db : Scanning system fonts...
luaotfload | db : Searching in static system directories...
luaotfload | db : Collected 429 files.
luaotfload | db : Scanning 2919 collected font files ...
luaotfload | db : Scanned 2919 files, 0 new.
luaotfload | db : Found 2919 font files; 0 new, 0 stale entries.
luaotfload | db : Creating filename map.
luaotfload | db : Analyzing families.
luaotfload | db : Analyzing shapes, weights, and styles.
luaotfload | db : Ordering design sizes.
luaotfload | db : Rebuilt in 11856 ms.
luaotfload | db : No new or removed fonts, skip saving to disk.
luaotfload | cache : Lookup cache saved.
luaotfload | cache : Lookup cache emptied.
luaotfload | db : Fonts in the database: 1882
luaotfload | util : Task completed successfully.
```

the scan seems to be repeated, I don't know if normal.
