### ISSUE TITLE
luaotfload v2.7 fails with fonts accompanying tfm

### ISSUE THREAD

**Issue by aminophen** [lualatex/luaotfload#338]
Following code compiles correctly with LuaTeX beta-0.80.0 + luaotfload v2.6 (= TL2015 frozen), but fails with LuaTeX beta-0.95.0 + luaotfload v2.7 (= TL2016 pretest).

~~~~ tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{cmtt10}
\begin{document}
Hello, \LaTeX!
\end{document}
~~~~
~~~~
luaotfload | resolve : step 1: apply method "tex" (function: 0x7fa3e561b920)
luaotfload | resolve : 1: method "tex" indicated lookup success
luaotfload | resolve : method "tex" resolved "cmtt10" -> cmtt10 (cmtt10.tfm)
luaotfload | resolve : step 1: apply method "tex" (function: 0x7fa3e561b920)
luaotfload | resolve : 1: method "tex" indicated lookup success
luaotfload | resolve : method "tex" resolved "cmtt10" -> cmtt10 (cmtt10.tfm)...exmf-dist/tex/luat
ex/luaotfload/luaotfload-auxiliary.lua:333: attempt to index field 'metadata' (a nil value)
stack traceback:
	...exmf-dist/tex/luatex/luaotfload/luaotfload-auxiliary.lua:333: in function '
provides_script'
	/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.lua:32: in func
tion 'check_ot_script'
	[\directlua]:1: in main chunk.
\fontspec_check_script:nTF ...ontspec_font","#1")}
                                                  \bool_if:NTF \l__fontspec_...

l.3 \setmainfont{cmtt10}
~~~~

**Comment by phi-gamma** [comment]
Hi,

thanks for the report.

···<date: 2016-04-23, Saturday>···<from: H. Yamashita>···

> Following code compiles correctly with LuaTeX beta-0.80.0 + luaotfload v2.6 (= TL2015 frozen), but fails with LuaTeX beta-0.95.0 + luaotfload v2.7 (TL2016 pretest).
> 
> ~~~~ tex
> \documentclass{article}
> \usepackage{fontspec}
> \setmainfont{cmtt10}
> \begin{document}
> Hello, \LaTeX!
> \end{document}
> ~~~~

Not a Luaotfload issue, I think. Here’s a minimal example which
runs just fine:

    https://bitbucket.org/phg/lua-la-tex-tests/src/13966399567c5bc5f1593ee5f8dfca55c8f776fa/plain/pln-load-font-11-tfm.tex


> 	/usr/local/texlive/2016/texmf-dist/tex/latex/fontspec/fontspec.lua:32: in func
> tion 'check_ot_script'
> 	[\directlua]:1: in main chunk.
> \fontspec_check_script:nTF ...ontspec_font","#1")}
>                                                   \bool_if:NTF \l__fontspec_...
> 
> l.3 \setmainfont{cmtt10}

Fontspec doesn’t appear to have adapted yet to the latest changes
in the fontloader, which frankly isn’t a surprise considering the
extent of the change. Just give them some time to catch up.

Best,
Philipp

**Comment by aminophen** [comment]
> Fontspec doesn’t appear to have adapted yet to the latest changes

Oh, I see. I'm sorry for bothering you.

**Comment by phi-gamma** [comment]
···<date: 2016-04-23, Saturday>···<from: H. Yamashita>···

> > Fontspec doesn’t appear to have adapted yet to the latest changes
> 
> Oh, I see. I'm sorry for bothering you.

Not at all, please don’t stop reporting.

**Comment by u-fischer** [comment]
Imho it is not a fontspec problem. I can get the error message with luaotfload alone:

```
\documentclass{article}
\usepackage{luaotfload}
\begin{document}

\font \fnt = cmtt10 at 42 pt
\fnt

\directlua{luaotfload.aux.provides_script(font.current(),"latn")}

\end{document}
```

This leads to the error, while in TL 2015 it worked fine. Using a font without tfm like e.g. arial works fine. 

```

luaotfload | resolve : step 1: apply method "tex" (function: 051C7CD8)
luaotfload | resolve : 1: method "tex" indicated lookup success
luaotfload | resolve : method "tex" resolved "cmtt10" -> cmtt10 (cmtt10.tfm)...e
xmf-dist/tex/luatex/luaotfload/luaotfload-auxiliary.lua:333: attempt to index field 'metadata' (a nil value)
stack traceback:
	...exmf-dist/tex/luatex/luaotfload/luaotfload-auxiliary.lua:333: in function 'provides_script'
	[\directlua]:1: in main chunk.
l.12 ....aux.provides_script(font.current(),"latn")}
```
