### ISSUE TITLE
crash with certain fonts

### ISSUE THREAD

**Issue by schlcht** [lualatex/luaotfload#340]
The following: 
```
\input luaotfload.sty
\font\x="Vollkorn:script=latn;"
\x A B
\bye
```
will break with: 
```
error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-04-21.lua:13129: attempt to index upvalue 'parameters' (a nil value)
```

This only happens with certain fonts. It also works fine without the `script` tag, or if I remove the space between `A` and `B`.

**Comment by phi-gamma** [comment]
Hi,

thanks for the report!

···<date: 2016-04-24, Sunday>···<from: schlcht>···

> ```
> \input luaotfload.sty
> \font\x="Vollkorn:script=latn;"
> \x A B
> \bye
> ```
> will break with: 
> ```
> error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-04-21.lua:13129: attempt to index upvalue 'parameters' (a nil value)
> ```
> 
> This only happens with certain fonts. It also works fine without the `script` tag, or if I remove the space between `A` and `B`.

Here’s a test that reproduces the crash with
the Plain loader:

    https://bitbucket.org/phg/lua-la-tex-tests/src/3cbe90381d13d5e1df5aeb874a5b0eafac88d562/plain/pln-load-font-13-parameters.tex

Forwarded to Hans.

Best,
Philipp

**Comment by phi-gamma** [comment]
@schlcht Did the latest release improve things on your end?

**Comment by s9w** [comment]
My [problem with Myriad Pro ](http://tug.org/pipermail/tex-live/2016-April/038249.html)is fixed, thanks!

**Comment by phi-gamma** [comment]
···<date: 2016-04-29, Friday>···<from: Sebastian Werhausen>···

> My [problem with Myriad Pro ](http://tug.org/pipermail/tex-live/2016-April/038249.html)is fixed, thanks!

Great that it works for you and thanks for the feedback!

Best,
Philipp

**Comment by schlcht** [comment]
Works for me too, thanks!
