### ISSUE TITLE
Fraction rule disappears with newtxmath and luaotfload v2.7

### ISSUE THREAD

**Issue by h-kitagawa** [lualatex/luaotfload#341]
`\frac12` in the following code gives a fraction “without fraction rule”.
It seems that  `\fontdimen8` was not correctly read from ntxexx.tfm.

    \documentclass{article}
    \usepackage{luaotfload}
    \usepackage{newtxmath}
    \begin{document}
    \[ \frac 12\]
    \the\fontdimen8 \textfont3,
    \fontname\textfont3 % --> ntxexx
    \end{document}

I think it’s luaotfload issue, because the above code works fine if `\usepackage{luaotfload}` is commented out.

EDIT: I’m using TL2016 pretest (2016/04/24), LuaTeX-0.95.0 and luaotfload v2.7 2016/04/21.

**Comment by eg9** [comment]
Apart from the problem, that I can confirm, I'm not sure I like my console to be polluted with tens of lines such as

    luaotfload | loaders : Extending reader sequence for “evl”.

or

    luaotfload | resolve : step 1: apply method "tex" (function: 0x1070e54c0)
    luaotfload | resolve : 1: method "tex" indicated lookup success
    luaotfload | resolve : method "tex" resolved "cmr7" -> cmr7 (cmr7.tfm)
    luaotfload | resolve : step 1: apply method "tex" (function: 0x1070e54c0)
    luaotfload | resolve : 1: method "tex" indicated lookup success
    luaotfload | resolve : method "tex" resolved "cmr7" -> cmr7 (cmr7.tfm)

**Comment by phi-gamma** [comment]
Hi,

thanks for the report.

···<date: 2016-04-25, Monday>···<from: Hironori Kitagawa>···

> `\frac12` in the following code gives a fraction “without fraction rule”.
> It seems that  `\fontdimen8` was not correctly read from ntxexx.tfm.
> 
>     \documentclass{article}
>     \usepackage{luaotfload}
>     \usepackage{newtxmath}
>     \begin{document}
>     \[ \frac 12\]
>     \the\fontdimen8 \textfont3,
>     \fontname\textfont3 % --> ntxexx
>     \end{document}
> 
> I think it's luaotfload issue, because the above code works
> fine if `\usepackage{luaotfload}` is commented out.

Does it work with other formats like Opentype? I had to adapt
the hack that sets ``\fontdimen8`` to the new data structures.

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2016-04-25, Monday>···<from: Hironori Kitagawa>···

> `\frac12` in the following code gives a fraction “without fraction rule”.
> It seems that  `\fontdimen8` was not correctly read from ntxexx.tfm.
> 
>     \documentclass{article}
>     \usepackage{luaotfload}
>     \usepackage{newtxmath}
>     \begin{document}
>     \[ \frac 12\]
>     \the\fontdimen8 \textfont3,
>     \fontname\textfont3 % --> ntxexx
>     \end{document}
> 
> I think it's luaotfload issue, because the above code works fine if `\usepackage{luaotfload}` is commented out.

Here’s the output with some modifications I just put in place:

![capheight hack](http://i.imgur.com/DBcLmNB.png)

That’s what I get too when commenting out Luaotfload in your
example.

Best,
Philipp

**Comment by h-kitagawa** [comment]
> Here’s the output with some modifications I just put in place:

`\fontdimen8` and `\frac` works fine with fontloader-2016-04-26.lua. Thanks.

Now I looked other `\fontdimen`s in ntxexx.tfm. Then, I got the following two differs:

`\fontdimen` | without luaotfload |with luaotfload
----------- | ------------ | ------------
`\fontdimen10` | 0.00107pt | 1.67pt
`\fontdimen11` | 0.00076pt | 1.99998pt

Other 11 `\fontdimen`s are same.

**Comment by phi-gamma** [comment]
···<date: 2016-04-26, Tuesday>···<from: Hironori Kitagawa>···

> > Here’s the output with some modifications I just put in place:
> 
> `\fontdimen8` and `\frac` works fine with fontloader-2016-04-26.lua. Thanks.
> 
> Now I looked other `\fontdimen`s in ntxexx.tfm. Then, I got the following two differs:
> 
> `\fontdimen` | without luaotfload |with luaotfload
> ----------- | ------------ | ------------
> `\fontdimen10` | 0.00107pt | 1.67pt
> `\fontdimen11` | 0.00076pt | 1.99998pt
> 
> Other 11 `\fontdimen`s are same.

The package has a number of fonts so I threw together a crude
script for comparing the before / after Luaotfload values:

    https://bitbucket.org/phg/lua-la-tex-tests/src/c47c7e06c8b7bdad52d99fc18005e0e6ba655cc9/plain/pln-patch-1-fontdimen.tex

**Comment by phi-gamma** [comment]
···<date: 2016-04-26, Tuesday>···<from: Hironori Kitagawa>···

> > Here’s the output with some modifications I just put in place:
> 
> `\fontdimen8` and `\frac` works fine with fontloader-2016-04-26.lua. Thanks.
> 
> Now I looked other `\fontdimen`s in ntxexx.tfm. Then, I got the following two differs:
> 
> `\fontdimen` | without luaotfload |with luaotfload
> ----------- | ------------ | ------------
> `\fontdimen10` | 0.00107pt | 1.67pt
> `\fontdimen11` | 0.00076pt | 1.99998pt
> 
> Other 11 `\fontdimen`s are same.

Fixed. The constants table has moved.
