### ISSUE TITLE
bold font is detected as bold italic (TL2016)

### ISSUE THREAD

**Issue by dohyunkim** [lualatex/luaotfload#342]
I have an entry in my luaotfload-names.lua.gz:
```lua
    ["sourcehansansk"]={
     ["bi"]={
      ["default"]=298,
     },
     ["r"]={
      ["default"]=304,
     },
    },
```
but index 298 is a bold font, not bold italic:
```lua
  {
   ["basename"]="SourceHanSansK-Bold.otf",
   ["familyname"]="sourcehansansk",
   ["fontname"]="sourcehansanskbold",
   ["format"]="otf",
   ["fullname"]="sourcehansanskbold",
   ["fullpath"]="/Users/nomosnomos/Library/Fonts/SourceHanSansK-Bold.otf",
   ["index"]=298,
   ["italicangle"]=0,
   ["location"]="texmf",
   ["pfmweight"]=700,
   ["plainname"]="Source Han Sans K Bold",
   ["size"]=false,
   ["subfamily"]="regular",
   ["subfont"]=false,
   ["version"]="Version 1.004;PS 1.004;hotconv 1.0.82;makeotf.lib2.5.63406",
   ["weight"]="bold",
  },
```
The culprit seems to be the fact that `tonumber` in [line 2806](https://github.com/lualatex/luaotfload/blob/master/src/luaotfload-database.lua#L2806) and line 2824 in luaotfload-database.lua is always `nil` as `info.modifier` is string such as "bold" or "semibold".

**Comment by phi-gamma** [comment]
···<date: 2016-04-25, Monday>···<from: Dohyun Kim>···

> I have an entry in my luaotfload-names.lua.gz:
> ```lua
>     ["sourcehansansk"]={
>      ["bi"]={
>       ["default"]=298,
>      },
>      ["r"]={
>       ["default"]=304,
>      },
>     },
> ```
> but index 298 is a bold font, not bold italic:
> ```lua
>   {
>    ["basename"]="SourceHanSansK-Bold.otf",
>    ["familyname"]="sourcehansansk",
>    ["fontname"]="sourcehansanskbold",
>    ["format"]="otf",
>    ["fullname"]="sourcehansanskbold",
>    ["fullpath"]="/Users/nomosnomos/Library/Fonts/SourceHanSansK-Bold.otf",
>    ["index"]=298,
>    ["italicangle"]=0,
>    ["location"]="texmf",
>    ["pfmweight"]=700,
>    ["plainname"]="Source Han Sans K Bold",
>    ["size"]=false,
>    ["subfamily"]="regular",
>    ["subfont"]=false,
>    ["version"]="Version 1.004;PS 1.004;hotconv 1.0.82;makeotf.lib2.5.63406",
>    ["weight"]="bold",
>   },
> ```
> The culprit seems to be the fact that `tonumber` in
> [line 2806](https://github.com/lualatex/luaotfload/blob/master/src/luaotfload-database.lua#L2806)
> and line 2824 in luaotfload-database.lua is always `nil` as
> `info.modifier` is string such as "bold" or "semibold".

Thanks for the report. Due to the new loader certain values are
shuffled. Seems like another ``pfmweight`` vs. ``weight`` issue
on the first glance. I’ll investigate.

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2016-04-25, Monday>···<from: Dohyun Kim>···

> I have an entry in my luaotfload-names.lua.gz:
> ```lua
>     ["sourcehansansk"]={
>      ["bi"]={
>       ["default"]=298,
>      },
>      ["r"]={
>       ["default"]=304,
>      },
>     },
> ```
> but index 298 is a bold font, not bold italic:

Fixed. (Actually I fixed this a while ago but seem to have
fumbled the commit …)
