### ISSUE TITLE
tds.zip of the development version?

### ISSUE THREAD

**Issue by u-fischer** [lualatex/luaotfload#343]
Would it be possible to automatically offer a tds.zip of the newest version? This would make it make it easier to test if a commit solves a problem without having to wait for the next upload on CTAN.

**Comment by phi-gamma** [comment]
···<date: 2016-04-26, Tuesday>···<from: u-fischer>···

> Would it be possible to automatically offer a tds.zip of the
> newest version?

Check out the repo and invoke

    make tds

This will assemble a ``luaotfload.tds.zip`` in the build
directory.

**Comment by u-fischer** [comment]
Running makefiles isn't easy  for windows users, and even if one has make it doesn't work:

~~~~~
$ make tds
make[1]: Entering directory `/C/Users/USER/github/luaotfload/doc'
creating file graph (filegraph.pdf)
/bin/sh: dot: command not found
make[1]: *** [filegraph.pdf] Error 127
make[1]: Leaving directory `/C/Users/USER/github/luaotfload/doc'
make: *** [doc/luaotfload.pdf] Error 2
~~~~~

**Comment by phi-gamma** [comment]
···<date: 2016-04-26, Tuesday>···<from: u-fischer>···

> Running makefiles isn't easy  for windows users, and even if one has make it doesn't work:

If someone were to contribute (and maintain) Windows build files
we could ship them with the repo. Pull requests welcome.

> ~~~~~
> $ make tds
> make[1]: Entering directory `/C/Users/USER/github/luaotfload/doc'
> creating file graph (filegraph.pdf)
> /bin/sh: dot: command not found

Graphviz is missing.

**Comment by simifilm** [comment]
FWIW, my attempts to build `luaotfload` on OSX all failed so far. I did not go into any details, but `make tds` always leads to 

```
creating PDF documentation (luaotfload.pdf)
make[1]: *** [luaotfload.pdf] Error 1
make: *** [doc/luaotfload.pdf] Error 2
```

**Comment by u-fischer** [comment]
OK I managed to build, but there is an error in the mkimport script. 


- I did install graphviz to get dot and so got over the error with missing dot.
- Then I got errors in the mkimport script. Calling it directly showed:


```
$ texlua ./scripts/mkimport package ./build/fontloader-2016-04-27.lua
./scripts/mkimport:819: bad argument #1 to 'date' (invalid conversion specifier
'%F')
```

So I replaced all %F in mkimport by %Y-%m-%d. 

Then I got errors because of the %T in mkimport and I replaced them by %X. 

Then I got an error that git is not found (I used the msys bash shell), so I had to add the path to git (but I have no idea why git is used at all). 

And then it worked.

**Comment by eroux** [comment]
I think most of the problems in the `tds` make target come from the complex doc build and maybe some other things that are not strictly necessary to just try luaotfload... so maybe a `simple-tds` target could be made that would just put the files where they need to be, without all the complex stuff?

**Comment by phi-gamma** [comment]
···<date: 2016-04-27, Wednesday>···<from: u-fischer>···

> OK I managed to build, but there is an error in the mkimport script. 
> 
> 
> - I did install graphviz to get dot and so got over the error with missing dot.
> - Then I got errors in the mkimport script. Calling it directly showed:
> 
> 
> ```
> $ texlua ./scripts/mkimport package ./build/fontloader-2016-04-27.lua
> ./scripts/mkimport:819: bad argument #1 to 'date' (invalid conversion specifier
> '%F')
> ```

Your libc is broken.

> (but I have no idea why git is used at all). 

Come on, it’s a **development** version.

**Comment by phi-gamma** [comment]
···<date: 2016-04-27, Wednesday>···<from: Elie Roux>···

> I think most of the problems in the `tds` make target come from
> the complex doc build and maybe some other things that are not
> strictly necessary to just try luaotfload... so maybe a
> `simple-tds` target could be made that would just put the files
> where they need to be, without all the complex stuff?

It all belongs in the ``tds.zip``.

If someone would work out the depencies for the status file etc.,
perhaps we could create some “light” version. But what would be
the point? You might as well just package the Lua files or grab
the loader from Context. What benefit is there in forcing it all
into a TDS structure?

**Comment by phi-gamma** [comment]
···<date: 2016-04-27, Wednesday>···<from: Simon Spiegel>···

> FWIW, my attempts to build `luaotfload` on OSX all failed so far. I did not go into any details, but `make tds` always leads to 
> 
> ```
> creating PDF documentation (luaotfload.pdf)
> make[1]: *** [luaotfload.pdf] Error 1
> make: *** [doc/luaotfload.pdf] Error 2

Logs?

**Comment by eroux** [comment]
Well, the point would be precisely to address the request: allow users of developer-hostile OSs to test a development version in a simple way

**Comment by phi-gamma** [comment]
···<date: 2016-04-27, Wednesday>···<from: Elie Roux>···

> Well, the point would be precisely to address the request:
> allow users of developer-hostile OSs to test a development
> version in a simple way

My point is that you don’t need a complete TDS for that.
Building the fontloader (``make package``) should do the trick.
Or just use the reference loader.

As I wrote earlier: We could ship build files for other platforms
inside a ``contrib`` directory or whatever.

**Comment by u-fischer** [comment]
> Your libc is broken.

?? What has libc to do with the fact that `os.date ("%F")` in a lua script gives an error?
