### ISSUE TITLE
version number not updated in luaotfload-2.7-fix-1 (CTAN version)

### ISSUE THREAD

**Issue by jfbu** [lualatex/luaotfload#346]
sorry to raise an issue about this, but after installing the tds.zip from CTAN of https://github.com/lualatex/luaotfload/releases/tag/v2.7-fix-1, when I run ``luaotfload-tool --version`` I get the same answer as with original 2.7 release. This initially made me wonder if I installed correctly.

**Comment by phi-gamma** [comment]
···<date: 2016-04-28, Thursday>···<from: Jean-François B.>···

> sorry to raise an issue about this, but after installing the tds.zip from CTAN of https://github.com/lualatex/luaotfload/releases/tag/v2.7-fix-1, when I run ``luaotfload-tool --version`` I get the same answer as with original 2.7 release. This initially made me wonder if I installed correctly.

Use the Git revision.

**Comment by jfbu** [comment]
the SHA number printed by luaotfload-tool --version has remained the same
 
with 2.7-fix-1 installed from CTAN tds.zip as available this morning

$ /usr/local/texlive/2016/texmf-dist/scripts/luaotfload/luaotfload-tool.lua --version

luaotfload-tool:
        Luaotfload font management and diagnostic utility.
        License: GNU GPL v2.0.
        Report problems to <https://github.com/lualatex/luaotfload/issues>

luaotfload-tool version: "2.7"
Revision: "23ff1b009f3b4df6754848196d7556c11c323d83"

original 2.7 which I saved in a luaotfload-27 directory:

$ /usr/local/texlive/2016/texmf-dist/scripts/luaotfload-27/luaotfload-tool.lua --version

luaotfload-tool:
        Luaotfload font management and diagnostic utility.
        License: GNU GPL v2.0.
        Report problems to <https://github.com/lualatex/luaotfload/issues>

luaotfload-tool version: "2.7"
Revision: "23ff1b009f3b4df6754848196d7556c11c323d83"

The git revision is the same. And the two luaotfload-tool.lua are the same file.

How do I get from command line git revision  you are referring to ?

(it can't be the one above which appears to be the one of luaotfload-tool last revision perhaps)

Jean-François

**Comment by phi-gamma** [comment]
···<date: 2016-04-28, Thursday>···<from: Jean-François B.>···

> the SHA number printed by luaotfload-tool --version has remained the same
>  
> with 2.7-fix-1 installed from CTAN tds.zip as available this morning
> 
> $ /usr/local/texlive/2016/texmf-dist/scripts/luaotfload/luaotfload-tool.lua --version
> 
> luaotfload-tool:
>         Luaotfload font management and diagnostic utility.
>         License: GNU GPL v2.0.
>         Report problems to <https://github.com/lualatex/luaotfload/issues>
> 
> luaotfload-tool version: "2.7"
> Revision: "23ff1b009f3b4df6754848196d7556c11c323d83"

That is the revision of the latest release:

      $ git tag --points-at b1a1ee5d1ec8002acee2702e6dd070073e0ee0ee
      v2.7
      $ git tag --points-at 23ff1b009f3b4df6754848196d7556c11c323d83
      v2.7-fix-1

**Comment by jfbu** [comment]
oh, I see.

sorry I understand. I am running the script with the new release other files installed into my personal texmf repertory. The data is not written in the script but fetched somewhere else.

if I remove the texmf repertory and run the old lua file (which apparently is the same) I do get 
Revision: "b1a1ee5d1ec8002acee2702e6dd070073e0ee0ee"

Big noise for nothing. Sorry about that.

**Comment by phi-gamma** [comment]
···<date: 2016-04-28, Thursday>···<from: Jean-François B.>···

> oh, I see.
> 
> sorry I understand. I am running the script with the new release other files installed into my personal texmf repertory. The data is not written in the script but fetched somewhere else.
> 
> if I remove the texmf repertory and run the old lua file (which apparently is the same) I do get 
> Revision: "b1a1ee5d1ec8002acee2702e6dd070073e0ee0ee"
> 
> Big noise for nothing. Sorry about that.

No problem. The versioning is pretty confusing due to the
synchrony with the TeX Live cycle. Personally I’d prefer a linear
numbering scheme (like systemd or chromium) over the forced
semver we’re practicing ATM, but it’s of too little importance
overall.
