### ISSUE TITLE
alternative to using font feature files after 2.7 release?

### ISSUE THREAD

**Issue by jfbu** [lualatex/luaotfload#347]
Sorry if wrong place as more a question than an issue. I can't pinpoint a link but I remember seeing when 2.7 was released that font feature file support had been dropped. 

(update: listed in NEWS file)

I wasn't sure I had understood correctly and tested only on 2.7-fix-1 as my use case was with Vollkorn font which I couldn't use with 2.7.

I observe indeed that font feature file do not appear to be obeyed. My question is thus how should I replace that ? My use case is for using a specific glyph from a stylistic variant (but only that glyph, not the whole stylistic set provided as a font feature).

Addendum: I tested this only with `LuaLaTeX+fontspec`. It is possible that only interface to fff has changed and fontspec not yet updated, but I am not using often enough to Plain LuaTeX  to invest into mastering direct syntax.

**Comment by u-fischer** [comment]
I completly forgot about it, but there was a discussion on the context list: Hans Hagen posted some code how to add features to a font on-the-fly:
http://thread.gmane.org/gmane.comp.tex.context/93228/focus=93229

**Comment by jfbu** [comment]
thanks Ulrike. This link is easier for me to read due to my small screen:

> <https://mailman.ntg.nl/pipermail/ntg-context/2016/083952.html>

any idea about how I should go about translating this:

```
feature oneb {
  sub one by one.ss01;
} oneb;
```

into suitable syntax ? 
I do no master the one used in the thread above, and see no example with glyph names.

Also I don't know if issues will arise with changing font size, or style, or switching to another and back.

**Comment by u-fischer** [comment]
Sorry I have no idea, I haven't currently the time to look at it. You could ask at tex.sx. Or ask at the context list how this can be done in the "plaintex level". Then it should be easy to lift it in the fontspec syntax. It is quite a pity that context/luatex often changes or removes things because of a "we don't need it" and then latex users have to struggle to adapt working solutions.

**Comment by jfbu** [comment]
Thanks Ulrike for the advice : I will raise the issue on the context list.

**Comment by phi-gamma** [comment]
···<date: 2016-04-28, Thursday>···<from: Jean-François B.>···

> I observe indeed that font feature file do not appear to be obeyed.

Those feature files were only ever supported by accident. Now
that we have gotten rid of the dependency on Fontforge the code
paths that would apply those files aren’t used any more.

**Comment by phi-gamma** [comment]
As to the alternatives: Adobe sort-of maintains a spec for feature files:
http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html
There’s no reason that prevents implementing it in Lua. We already have
an API for patching fonts after they’re loaded.

Other options are: Convince Hans or somebody else to do the work for
you. Don’t use broken fonts or fix them properly. Stick with last year’s
Luatex+Luaotfload. Use a different engine that supports those files.

**Comment by eroux** [comment]
`.fea` are also part of [ufo format](http://unifiedfontobject.org/versions/ufo3/features.fea/). I too liked the idea to be able to use a custom fea...

**Comment by phi-gamma** [comment]
@eroux Thanks for the link. From my limited understanding this is a
font development / archiving project. Is TeX actually used in that
niche or are there possible use cases? If you can prove a practical
value and could get somebody to actively test the code, this would
make a pretty convincing case for implementing feature files.

**Comment by eroux** [comment]
The most trendy free font editor, [TruFont](http://trufont.github.io/) only manipulates ufo, and there are some nice python lib for ufos... so I wouldn't say it's niche, it's just developper-oriented. I'm using UFO instead of sfd now to develop fonts, it is handled very nicely by git & co. (the diffs are diffs on the .fea or adding/remove/changing some .glyph, etc. it's all human readable... to some extent)

**Comment by jfbu** [comment]
> Other options are: Convince Hans or somebody else to do the work for
you. Don’t use broken fonts or fix them properly. Stick with last year’s
Luatex+Luaotfload. Use a different engine that supports those files.

As I explained, I was not using a broken font but using a font feature file
to access a specific glyph. I sense some exasperation in your tone, for
which I see no justification.

I know of no different engine supporting those font feature files,
and I used LuaTeX because XeTeX didn't allow it.

However, I have since been explained by  Heiko Oberdiek how to create
a new font (using font forge) having the single glyph substitution
I want. This would allow me to switch to XeTeX after all.

I noticed the obvious (substantial) speed improvements in new
LuaTeX+luaotfload,
which means I am not particularly enthusiastic into going on with the
files from last year's release, for the single project I am using LuaLaTeX.

Besides, I don't expect TeXLive will distribute simultaneously current
LuaTeX+luaotfload and last year's one, together with a toggle between the two,
and although I can (almost) instantly
switch distribution (but I have a to relaunch a shell as I use environment
variables to bypass long response times of kpsewhich --var-value), it is obviously
not  a practical perspective to use TL2015 with its frozen packages. But you
sure know that.

In the mean time I will confirm on the fontspec issue tracker that their
docs should be updated to remove all mention of font feature file support.

**Comment by dohyunkim** [comment]
```tex
\documentclass{article}
\usepackage{fontspec}
\directlua{
    fonts.handlers.otf.addfeature {
        name = "oneb",
        {
            type = "substitution",
            data = {
                ["1"] = "one.ss01",
            },
        },
        "feature oneb for vollkorn font",
    }
}
\setmainfont{Vollkorn-Regular.otf}[RawFeature=+oneb]
\begin{document}
1234567890
\end{document}
```
works for me.

**Comment by jfbu** [comment]
@dohyunkim great that does it! ok also with added bold, italic, bold italic specifiers in the `\setmainfont` call and font size changes in document's body etc. A posteriori it looks like it was immediate from https://mailman.ntg.nl/pipermail/ntg-context/2016/083952.html, and thanks to a rarentemporary increase of intelligence I had gone as far as guessing that `\directlua` was the way to go but unfortunately there was no example with glyph names employed like here, and any practitioner of computers knows that hours pass by very quickly when groping in the dark due to some unfamiliar syntax (I am no Lua practitioner). Thanks for helping me out !

My yesterday's message to context list is awaiting moderator approval. I will thus add a pointer to your comment on the fontspec issue tracker, rather. I hope it can help others.

**Comment by jfbu** [comment]
Just an addendum that the above mwe fails to render `1` as expected after addition of `\usepackage{url}`, `\urlstyle{same}` on the test `\url{1111}`. This is perhaps due to `url`'s detour via math mode, which complicates my use case. I remember there are some issues with LuaTeX applying OTF font features in math mode. The issue was already there with last year's LuaTeX+luaotfload and use of font feature file, but at that time my use case did not employ `\url` but `\href` which does not go via math mode.

**Comment by u-fischer** [comment]
The url problem is certainly due to math mode. But is doesn't look like a general luatex problem. This context file

~~~~~
\starttext

\directlua{
    fonts.handlers.otf.addfeature {
        name = "oneb",
        {
            type = "substitution",
            data = {
                ["1"] = 65,
            },
        },
        "feature oneb ",
    }
}


\font\test= {name:arial:+oneb}
\test 1234
$\fam0 \textfont0=\test 1234 $
\stoptext
~~~~~

outputs this
![contesta](https://cloud.githubusercontent.com/assets/4047173/14922942/a86a2c72-0e3a-11e6-8e3f-768e58c54bf7.PNG)


while the similar plaintex (and latex with and without unicode-math)

~~~~~
\input luaotfload.sty
\directlua{
    fonts.handlers.otf.addfeature {
        name = "oneb",
        {
            type = "substitution",
            data = {
                ["1"] = 65,
            },
        },
        "feature oneb ",
    }
}


\font\test= {name:arial:+oneb}
\test 1234
$\fam0 \textfont0=\test 1234 
\bye
~~~~~

gives
![plaina](https://cloud.githubusercontent.com/assets/4047173/14922968/c7c70630-0e3a-11e6-94c7-cda2ee437143.PNG)

**Comment by jfbu** [comment]
very interesting Ulrike. There is an issue with old style figures at http://tex.stackexchange.com/questions/208688/oldstylefigure-issue-with-lualatex-and-mathastext/277628#277628 which uses

    [Vollkorn-Regular]:mode=node;script=latn;language=DFLT;+tlig;+lnum; at 9.0pt

as font specifier. The math mode use does not obey the `lnum` feature and uses old style figures. One can test this with Plain LuaTeX:

```tex
\input luaotfload.sty
\font\test= {name:Vollkorn-Regular.otf:+lnum}
\test 0123456789
$\fam0 \textfont0=\test 0123456789$ 
\nopagenumbers
\bye
```
Result:

![capture d ecran 2016-04-29 a 19 27 26](https://cloud.githubusercontent.com/assets/2589111/14923968/7931f902-0e40-11e6-8d6c-92e025419982.png)

Surprisingly with a font like TeX Gyre Termes, it is the other way around: If I specify the `onum` feature it is not obeyed in math mode.

```tex
\input luaotfload.sty
\font\test= {name:TeX-Gyre-Termes:+onum}
\test 0123456789
$\fam0 \textfont0=\test 0123456789$ 
\nopagenumbers
\bye
```
Result:
![capture d ecran 2016-04-29 a 19 20 33](https://cloud.githubusercontent.com/assets/2589111/14923886/1f877a9e-0e40-11e6-8cf0-7bbdffb9cadb.png)

I tried to test with context, but it does not recognize `\direclua`. Perhaps the context which comes with TeXLive is not the good one (I see some reference to `mkii` in the log, perhaps it should be `mkiv` ?) (I know nothing about context).

**Comment by phi-gamma** [comment]
···<date: 2016-04-28, Thursday>···<from: Elie Roux>···

> The most trendy free font editor,
> [TruFont](http://trufont.github.io/) only manipulates ufo,

As it happens, LWN has an article about Trufont in this week’s
edition: https://lwn.net/SubscriberLink/684970/750c3a6d31cabcd6/
Sounds promising, indeed =)

But my original question still stands: How is UFO used outside of
font design? As I understand it, fonts are still compiled to some
binary container format for use in applications. I don’t doubt
the usefulness of a textual representation that maps to spline
fonts, I just don’t see the applicability outside font design per
se. Can, e. g. {Star,Libre,Open}office handle them?

**Comment by u-fischer** [comment]
> I tried to test with context, but it does not recognize \direclua. Perhaps the context which comes with TeXLive is not the good one (I see some reference to mkii in the log, perhaps it should be mkiv ?) (I know nothing about context).

you need to compile with `context file`. It should work (but in the long run the context in texlive will get outdated, only the minimals are updated regularly)

**Comment by eroux** [comment]
Indeed, UFO fonts are for development only, it makes no sense to use it in production

**Comment by jfbu** [comment]
@u-fischer  allright, I was trying to launch it from an Emacs buffer but the mode seems to be mis-configured. From the command line ok. Then
 ```tex
\starttext
\font\test= {name:TeX-Gyre-Termes:+onum}
\test 0123456789
$\fam0 \textfont0=\test 0123456789$ 
\stoptext
```
gives
![capture d ecran 2016-04-29 a 21 08 19](https://cloud.githubusercontent.com/assets/2589111/14926832/8c15ceaa-0e4e-11e6-8f2e-4a13d07217a1.png)

to be compared with the Plain LuaTeX case above.

**Comment by mikkelee** [comment]
How do I go about implementing the following featurefile using `fonts.handlers.otf.addfeature`?

```
languagesystem DFLT dflt;
languagesystem latn dflt;

@nots = [a b c d e f g h i j k l m n o p q r t u v w x y z];

feature hist {
    sub s' @nots by longs;
    sub longs longs by longs s;
} hist;
```

I can't find anything in the documentation or examples of substitutions using character classes.
