### ISSUE TITLE
fontloader error when trying to mix LRT/RTL text in paragraphs

### ISSUE THREAD

**Issue by ralessi** [lualatex/luaotfload#349]
With luaotfload v2.7 (from TeXLive 2016 pretest), I cannot anymore mix RTL and LTR text in one and the same paragraph, namely without inserting blank lines before `\textdir TRT` and the like.

Here is a mwe:
````
\documentclass{article}

\usepackage{fontspec}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\section*{This works:}
English text: hello, world.

\textdir TRT\arabicfont
دَخَكَ مُبتَسِمًا

\textdir TLT\normalfont
English text back again.

\section*{But this doesn't}
English text: hello, world.
\textdir TRT\arabicfont
دَخَكَ مُبتَسِمًا
\textdir TLT\normalfont
English text back again.

\end{document}
````

This mwe gives me the following error: `[...]texmf/tex/luatex/luaotfload/fontloader-2016-04-27.lua:13071: attempt to index local 'i' (a nil value)`

Furthermore, if I force the compilation, I get this:
![screenshot](https://cloud.githubusercontent.com/assets/389498/14937368/9ae1cf94-0f05-11e6-9953-afc1309fc91b.png)
Which is wrong, for we should read the last line as follows:

> English text: hello, world. دَخَلَ مُبتَسِمًا English text back again.

Many thanks in anticipation for your help. -- Robert

**Comment by ralessi** [comment]
> Furthermore, if I force the compilation, I get this [...]
_I_ am wrong, sorry. The brave old TeXLive 2015 and luaotfload v2.6 give the same word order.

**Comment by ralessi** [comment]
So here is the actual issue in my opinion:

With luaotfload v2.7 (from TeXLive 2016 pretest), I cannot anymore mix RTL and LTR text in one and the same paragraph, namely without inserting blank lines before `\textdir TRT` and the like.

Here is a mwe:
````
\documentclass{article}

\usepackage{fontspec}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\section*{This works:}
English text: hello, world.

\textdir TRT\arabicfont
دَخَكَ مُبتَسِمًا

\textdir TLT\normalfont
English text back again.

\section*{But this doesn't}
English text: hello, world.
\textdir TRT\arabicfont
دَخَكَ مُبتَسِمًا
\textdir TLT\normalfont
English text back again.

\end{document}
````
This mwe gives me the following error: `[...]texmf/tex/luatex/luaotfload/fontloader-2016-04-27.lua:13071: attempt to index local 'i' (a nil value)`

**Comment by ralessi** [comment]
**NB1:** I think `fontspec` is not implicated for I get the same error with this preamble:
````
\documentclass{article}

\usepackage{luaotfload}
\font\normalfont = {name:Libertinus Serif:script=latn} at 12pt
\font\arabicfont = {name:Amiri:script=arab} at 12pt

\usepackage{arabluatex}

\begin{document}
````

**NB2:** `\textdir xyz` must be combined with `\normal|arabifont` for the error to come out.

**Comment by phi-gamma** [comment]
Hi,

thanks for the report!

I think this was an instance of this bug: https://mailman.ntg.nl/pipermail/ntg-context/2016/085321.html
In any case, it doesn’t occur anymore with the latest fontloader code
so please wait for the next Luaotfload release.

Philipp

**Comment by ralessi** [comment]
Hi Philipp,

Excellent.  I will test it as soon as it is out.  Good to hear that this will be part of the test repo: so we kill two birds with one stone.

Robert

**Comment by ralessi** [comment]
Hi Philipp,

I still have an issue in this mwe:
````
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Libertinus Serif}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

Hello: this is not so efficient:
\textdir TRT\arabicfont دَخَلَ مُبتَسِمًا

Hello: this is good:
\textdir TRT\arabicfont دَخَلَ مُبتَسِمًا

\end{document}
````
It gives me this error:
````
error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-05-04.lua:13129: attempt to index local 'i' (a nil value)
.
l.11
````

Oddly, the culprit is the word 'efficient' on line 9; if you take it out, or replace it with 'good', the mwe compiles smoothly. Is it because of the 'ffi' ligature?

Robert

**Comment by phi-gamma** [comment]
Hi Robert,

thanks for testing.

> It gives me this error:
> ````
> error: ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-05-04.lua:13129: attempt to index local 'i' (a nil value)

Confirmed. Looks like this is triggered by the transition from
Latin to Arabic script:

    https://bitbucket.org/phg/lua-la-tex-tests/src/684543a96a38ca647ca63c3301036b18fa39d7a0/latex/ltx-arabic-4.tex

I’ll file a bug with Hans.

Best,
Philipp

**Comment by ralessi** [comment]
Great! I can't wait to test this new release! Many thanks, -R

**Comment by phi-gamma** [comment]
···<date: 2016-06-14, Tuesday>···<from: Robert Alessi>···

> Great! I can't wait to test this new release! Many thanks, -R

Don’t thank me just yet ;) I still have to run another batch of
tests before releasing.

**Comment by ralessi** [comment]
Fingers crossed! If I understood well, this fontloader update does not address issue #361 yet. Is that so? Many thanks again for your efforts. -R

**Comment by phi-gamma** [comment]
> If I understood well, this fontloader update does not address issue #361 yet. Is that so?

I’m afraid so. I forwarded the issue to Hans but so far no new developments
in this regard. Give him some slack, though, most other issues are fixed within
ours.

**Comment by phi-gamma** [comment]
···<date: 2016-06-15, Wednesday>···<from: Robert Alessi>···

>                  If I understood well, this fontloader update
> does not address issue #361 yet.

Try the new release, you’re in for a treat :)

**Comment by ralessi** [comment]
Well it looks like only some very little slack was actually needed!  Everything is just fine now, and I am so very grateful, what a treat indeed!

By the way, I had to wait for the tds archive to be available on CTAN because `make tds` fails on my machine (Parabola GNU/Linux, with graphviz and python-docutils installed). But it's not a big deal, and I don't want to bother you with that kind ot glitch.

Many thanks again, this is great!

Robert
