### ISSUE TITLE
kerning and double ligature

### ISSUE THREAD

**Issue by schlcht** [lualatex/luaotfload#350]
The following:

```
\input luaotfload.sty
\font\x="EB Garamond:kernfactor=0.100"
\x affig
\bye
```

crashes with 
```
! error:  (nodes): attempt to double-free glyph (g) node 348, ignored
!  ==> Fatal error occurred, no output PDF file produced!
```

EDIT: sorry, the title should of course read "kernfactor and double ligature"

**Comment by phi-gamma** [comment]
···<date: 2016-05-01, Sunday>···<from: schlcht>···

> The following:
> 
> ```
> \input luaotfload.sty
> \font\x="EB Garamond:kernfactor=0.100"
> \x affig
> \bye
> ```
> 
> crashes with 
> ```
> ! error:  (nodes): attempt to double-free glyph (g) node 348, ignored
> !  ==> Fatal error occurred, no output PDF file produced!
> ```

Strange. That doesn’t happen here. What font are we talking about?

    $ luaotfload-tool --list='*' | grep -i "EB Garamond 12 Regular"
    EB Garamond 12 Regular  Version 0.016+
    $ luaotfload-tool --find="EB Garamond 12 Regular"
    luaotfload | resolve : Font "EB Garamond 12 Regular" found!
    luaotfload | resolve : Resolved file name "/home/phg/.local/texlive/2016/texmf-dist/fonts/opentype/public/ebgaramond/EBGaramond12-Regular.otf"
    $ sha1sum /home/phg/.local/texlive/2016/texmf-dist/fonts/opentype/public/ebgaramond/EBGaramond12-Regular.otf
    209845b6b286fbed0add537dfe07e8ef9cb8d90f  /home/phg/.local/texlive/2016/texmf-dist/fonts/opentype/public/ebgaramond/EBGaramond12-Regular.otf

Tested with the Luatex and Luaotfload from the pretest.

Philipp

**Comment by schlcht** [comment]
It was an older version of EB Garamond (0.14d), and with the current version I don't get the crash either. However, I still get the same error with other fonts, eg., with Linux Libertine (from pretest): 

```
$ luaotfload-tool --list='*' | grep -i "Linux Libertine O"
Linux Libertine O	Version 5.3.0 
$ luaotfload-tool --find="Linux Libertine O"
luaotfload | resolve : Font "Linux Libertine O" found!
luaotfload | resolve : Resolved file name "/Users/schlcht/Library/texlive/2016-pretest/texmf-dist/fonts/opentype/public/libertine/LinLibertine_R.otf"
```

**Comment by phi-gamma** [comment]
Confirmed. Looks like it’s not occurring with TL2015 Luatex. In any case
we might see the ``components`` field vanish before Luatex 1.0 so it’s
probably just a temporary issue. Fixed in next release.
