### ISSUE TITLE
Version 2016-04-21 breaks simple document

### ISSUE THREAD

**Issue by 7Z0t99** [lualatex/luaotfload#353]
I'm using MikTeX on Windows 7, which recently updated luaotfload to version 2016-04-21. Now I always get the following error in lualatex when compiling the attached simple document. (Unfortunately GitHub doesn't allow .tex, so I renamed it)
tex/luatex/luaotfload/fontloader-2016-04-21.lua:19357: attempt to call upvalue 'getdisc' (a nil value)

I already deleted the luatex-cache as suggested in http://tex.stackexchange.com/questions/152238/compilation-error-with-lualatex-luaotfload-database-lua but it didn't help

[test.txt](https://github.com/lualatex/luaotfload/files/247053/test.txt)

**Comment by hvoss49** [comment]
I have no problem with up-to-date TL 2016 pretest and "Time New Roman MT Std". I do not have a 
"Times New Roman Font".

**Comment by 7Z0t99** [comment]
As far as I know, MikTeX still tracks TL 2015. Where did you get your version of Times New Roman? Mine is the one that ships with Windows 7 (fully updated) aka Version 5.22

**Comment by hvoss49** [comment]
I am a Linux User and I do not know where I get this version of Times

**Comment by 7Z0t99** [comment]
Then you have probably got the version from the Corefonts project at http://corefonts.sourceforge.net/

I just found that there is also MikTeX Next that tracks TL 2016 pretest and everything works there. But it has already got luaotfload from 2016-04-27. I don't know about TL 2015.

**Comment by phi-gamma** [comment]
> I'm using MikTeX on Windows 7, which recently updated
> luaotfload to version 2016-04-21. Now I always get the following
> error in lualatex when compiling the attached simple document.
> (Unfortunately GitHub doesn't allow .tex, so I renamed it)
>
> tex/luatex/luaotfload/fontloader-2016-04-21.lua:19357: attempt to call upvalue 'getdisc' (a nil value)

Your Luatex is out of date. The 2.7 series of Luaotfload requires
at least a 0.95.0 Luatex (e. g. the one in tex live).

Anyways, the actual issue is that I accidentally the version
check when killing off legacy code. This will be fixed in the
next release of Luaotfload and instead of cryptic failures you’ll
get a more informative error message.

Best,
Philipp

**Comment by 7Z0t99** [comment]
Ok, that means that this version of luaotfload should have never landed in MikTeX stable, as it has got luatex 0.80.0 like TL 2015.

Thank you!

**Comment by phi-gamma** [comment]
···<date: 2016-05-03, Tuesday>···<from: 7Z0t99>···

> Ok, that means that this version of luaotfload should have
> never landed in MikTeX stable, as it has got luatex 0.80.0 like
> TL 2015.

I’m not sure by what process packages end up in Miktex
but I wouldn’t call it their fault: One perennial issue
with CTAN is that distros use it as the main upstream but
there’s no way for a packager / developer to convey version
dependencies to them. So packages are normalized against
the TeX live binaries and … bang!

Of course, considering the stability of the original TeX this
wasn’t much of a concern until recently. But today everyone
expects a pre-1.0.x release of a bleeding edge engine to be part
of the distro. (I’m no exception, of course, but my main TeX
distro, the Context Minimals, work a bit differently.)

Perhaps this is a good time for Miktex to update Luatex too?

**Comment by u-fischer** [comment]
Miktex is currently beta testing the new luatex (and other changes): http://miktex.org/announcement/miktex-next-5900. I also made a bug report that luaotfload 2.7. is not suitable for the stable version. https://sourceforge.net/p/miktex/bugs/2461/.

**Comment by phi-gamma** [comment]
Version 2.8 is out and I was notified that Miktex already ships Luatex 1.x. Closing this.
Please reopen if appropriate.
