### ISSUE TITLE
Problem with the luaotfload and calt feature when implemented as normal contextual substitution

### ISSUE THREAD

**Issue by orchidee2** [lualatex/luaotfload#354]
After the problem with the calt feature when implemented as contextual chaining substitution could be solved in luaotfload 2.7 (which is extremely helpful for most of my applications – so, thanks a lot!), the problem with the calt feature still remains if implemented as normal contextual substitution in the font. The substitution only works as desired, when the glyph to be substituted is the first one of the word/ phrase.
I will send some testfiles later.

**Comment by orchidee2** [comment]
The issue seems to be fixed in version 2.7-fix-3, but I will do some more test.

**Comment by orchidee2** [comment]
My test results show, that the mentioned problem was solved with version 2.7-fix-3, but now there are 2 new problems concerning contextual substitutions. In the result the calt and also other features may still not work as desired. I will open a new item for that.

**Comment by u-fischer** [comment]
closing as it looks as if this has been resolved in a previous version.
