### ISSUE TITLE
funny ligatures with Arabic script

### ISSUE THREAD

**Issue by ralessi** [lualatex/luaotfload#361]
Hi Philipp,

This mwe:

```
\documentclass[12pt]{article}

\usepackage{luaotfload}

\font\arabicfont = {name:Amiri:script=arab} at 12pt

\begin{document}

\textdir TRT\arabicfont
اَلحِمَارُ، اَلجَدِيدُ، اَلحَارِثُ.

\end{document}
```

gives me this, where the last two words are obvioulsy wrong::
![amiri](https://cloud.githubusercontent.com/assets/389498/15888026/8d1bc22e-2d65-11e6-9be3-1aa0da74c0c9.png)

I suspect this issue may be related to the latest `luaotfload` and not to Amiri for XeLaTeX + `fontspec` do not have it.  I checked the following mwe with `xelatex:

```
\documentclass[12pt]{article}

\usepackage{fontspec}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\usepackage{polyglossia}
\setdefaultlanguage{arabic}

\begin{document}
اَلحِمَارُ، اَلجَدِيدُ، اَلحَارِثُ.
\end{document}
```

Best,

Robert

**Comment by ralessi** [comment]
[Update] Other ligatures are broken too, as in the name of God for example. Let's assume that they all are related to the one and the same issue.

**Comment by phi-gamma** [comment]
Dear Robert,

thanks for reporting. I’m not qualified to judge that output but
I do notice the difference to the Xetex version.

> This mwe:
> ````
> \documentclass[12pt]{article}
> \usepackage{luaotfload}
> \font\arabicfont = {name:Amiri:script=arab} at 12pt
> \begin{document}
> \textdir TRT\arabicfont
> اَلحِمَارُ، اَلجَدِيدُ، اَلحَارِثُ.
> \end{document}
> ````
> gives me this, where the last two words are obvioulsy wrong::
> ![amiri](https://cloud.githubusercontent.com/assets/389498/15888026/8d1bc22e-2d65-11e6-9be3-1aa0da74c0c9.png)

It happens in Context too, so it’s most likely a problem in the
fontloader:

    http://i.imgur.com/ihnxEEs.png

(Clockwise starting at the top: Luatex, Context, Xelatex.)

I’ll forward the issue to Hans.
Philipp

**Comment by ralessi** [comment]
Dear Philipp,

Yes, what happens in luatex also happens in context.  Thank you for your efforts, let me know if I can be of any help.

Robert

**Comment by ralessi** [comment]
Many thanks, it now works like a charm!

**Comment by u-fischer** [comment]
I'm closing this as probably resolved. Feel free to reopen if something still isn't working.

**Comment by ralessi** [comment]
Yes, I confirm it has been resolved.
