### ISSUE TITLE
faulty contextual substitutions

### ISSUE THREAD

**Issue by orchidee2** [lualatex/luaotfload#368]
Contextual substitutions may work erroneous if a subtable of a lookup contains more than one entry. Character tables are somehow mixed, so that in the result substitutions occur (additionally to those, defined in the lookup), that you would not expect. I will provide a test font and a tex file for testing.

**Comment by u-fischer** [comment]
I'm closing as no example for test has been provided. If the issue still exist, open a new issue at https://github.com/u-fischer/luaotfload/issues/85.
