### ISSUE TITLE
Diacritical character + ligature + other characters create error when compiling in specific font

### ISSUE THREAD

**Issue by sujato** [lualatex/luaotfload#371]
I seem to have come across an incredibly specific bug which occurs when I compile a document using luatex and the font Skolar Sans PE. It occurs only when there are both specific character combinations, including certain ligatures, and characters with diacriticals in the same paragraph. 

The error occurs when using all families of Skolar Sans PE, but not in Skolar PE (the serif version), not in the simpler version of the font (Skolar Sans Latin), and not in any of the other fonts I've tested. Also, it compiles fine in XeTeX. 

A MWE:

    \documentclass{book}
    \usepackage{fontspec}
    \setmainfont{Skolar Sans PE}
    \begin{document}
          often ā
    \end{document}

This throws the following error:

    ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-05-04.lua:13159: attempt to index local 'i' (a nil value)

Changing the exact sequence of characters shows that certain ligatures provoke the error (fb, ff, ft, fj) while others don't (tt, fl, fi). Changing the diacritical character has no effect. Changing other letters in the sequence sometimes has an effect. For example, "often ā" triggers the error, as does "ofben ā". But if I change the vowel to i,  "oftin ā" is fine, while "ofbin ā" is not. 

Suspecting a bug in the font, I contacted the designer David Brezina, but he was unable to locate a bug and we suspect the issue may lie with luaotfload.

**Comment by phi-gamma** [comment]
···<date: 2016-07-19, Tuesday>···<from: sujato>···

> I seem to have come across an incredibly specific bug which occurs when I compile a document using luatex and the font Skolar Sans PE. It occurs only when there are both specific character combinations, including certain ligatures, and characters with diacriticals in the same paragraph. 
> 
> The error occurs when using all families of Skolar Sans PE, but not in Skolar PE (the serif version), not in the simpler version of the font (Skolar Sans Latin), and not in any of the other fonts I've tested. Also, it compiles fine in XeTeX. 
> 
> A MWE:
> 
>     \documentclass{book}
>     \usepackage{fontspec}
>     \setmainfont{Skolar Sans PE}
>     \begin{document}
>           often ā
>     \end{document}
> 
> This throws the following error:
> 
>     ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-05-04.lua:13159: attempt to index local 'i' (a nil value)

Please update to the latest version (2016-06-16) and test again.

Thanks,
Philipp

**Comment by sujato** [comment]
Thanks so much for the quick response! I ran `tlmgr update --all` and the problem is now fixed.
