### ISSUE TITLE
luaotfload tries to recompile an existing .luc file

### ISSUE THREAD

**Issue by cjorssen** [lualatex/luaotfload#375]
As reported in [question of mine](http://tex.stackexchange.com/q/324564/8425),  `luaotfload` shipped with TeXLive2016  (`luatex` 0.95) tries first to compile a `.luc` file in a directory without write permission and then load the existing one in an other directory. As it may be a TeXLive issue, I cross post to TeXLive mailing-list.

**Comment by phi-gamma** [comment]
Hi,

thanks for reporting.

> As reported in [question of mine](http://tex.stackexchange.com/q/324564/8425),
> `luaotfload` shipped with TeXLive2016  (`luatex` 0.95) tries
> first to compile a `.luc` file in a directory without write
> permission and then load the existing one in an other directory.
> As it may be a TeXLive issue, I cross post to TeXLive
> mailing-list.

Please try this patch:

    https://github.com/phi-gamma/luaotfload/commit/a0af5eb29908a78df4fea1be5ff2f9b11bdbbd59

If it doesn’t apply let me know, I can backport it to the TL
version.

Best,
Philipp

**Comment by cjorssen** [comment]
This seems to work. Thanks a lot!

**Comment by phi-gamma** [comment]
···<date: 2016-08-24, Wednesday>···<from: cjorssen>···

> This seems to work. Thanks a lot!

Great. I’m still waiting for Hans to include the change upstream.

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2016-08-24, Wednesday>···<from: cjorssen>···

> This seems to work. Thanks a lot!

Just so you know there won’t be a definite fix right away. We’ll
see whether global caching (including the font names index) is
salvagable.

Best,
Philipp

**Comment by phi-gamma** [comment]
Latest master has a better fix, please test.

**Comment by phi-gamma** [comment]
Closing, this should be fixed with v2.8; please reopen if the issue persists.
