### ISSUE TITLE
can no longer use Coelacanth

### ISSUE THREAD

**Issue by mewtant** [lualatex/luaotfload#377]
With TeX Live 2015, I was able to use the Coelacanth type family ([benwhitmore.altervista.org/coelacanth-type-family/](http://benwhitmore.altervista.org/coelacanth-type-family/)) with `luatex`. With an up-to-date TeX Live 2016, I can use the font with `xetex`, but not with `luatex`.  Whether with `fontspec` or `luaotfload`, the error is: `luaotfload/fontloader-2016-06-16.lua:9016: bad argument #1 to 'for iterator' (table expected, got number)`. Example:

```
\documentclass{article}
\usepackage{luaotfload}
\begin{document}
\font\foo="Coelacanth:mode=base" at 12pt
\foo The cat sat on the mat.
\end{document}
```

**Comment by phi-gamma** [comment]
Hi @mewtant,

thanks for the report.

> With TeX Live 2015, I was able to use the Coelacanth type
> family
> ([benwhitmore.altervista.org/coelacanth-type-family/](http://benwhitmore.altervista.org/coelacanth-type-family/))
> with `luatex`. With an up-to-date TeX Live 2016, I can use the
> font with `xetex`, but not with `luatex`.  Whether with
> `fontspec` or `luaotfload`, the error is:
> `luaotfload/fontloader-2016-06-16.lua:9016: bad argument #1 to
> 'for iterator' (table expected, got number)`. Example:

Indeed, this is reproducible in Context too. I’ve relayed the
issue to Hans.

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2016-08-25, Thursday>···<from: mewtant>···

> With TeX Live 2015, I was able to use the Coelacanth type
> family
> ([benwhitmore.altervista.org/coelacanth-type-family/](http://benwhitmore.altervista.org/coelacanth-type-family/))
> with `luatex`. With an up-to-date TeX Live 2016, I can use the
> font with `xetex`, but not with `luatex`.  Whether with
> `fontspec` or `luaotfload`, the error is:
> `luaotfload/fontloader-2016-06-16.lua:9016: bad argument #1 to
> 'for iterator' (table expected, got number)`. Example:

The crash will be fixed in the next version. If you’re curious,
the fix looks like this:

    https://github.com/phi-gamma/luaotfload/commit/698d75bb7f02853f5bb7d0582864d4fe5368773a

Best,
Philipp

**Comment by phi-gamma** [comment]
New release (2.8) is about to reach CTAN, please retest. Thank you!

**Comment by mewtant** [comment]
It works perfectly now.  Thanks very much!

**Comment by phi-gamma** [comment]
2017-01-31 (Tuesday), notifications@github.com (mewtant):

> It works perfectly now.  Thanks very much!

Great to hear, thanks for reporting in the first place!
