### ISSUE TITLE
Metric TFM files for MetaFont bitmap fonts are not automatically generated

### ISSUE THREAD

**Issue by pali** [lualatex/luaotfload#381]
Let's take bitmap font cmb12 (part of texlive-fonts-extra). In pdftex it can be easily used, just:

```
\pdfpkresolution=600
\font\bitmap=cmb12
\bitmap test
\bye
```

And pdftex generate PDF document.

Similarly in luatex with luaotfload bitmap font cmb12 can be inserted as:

```
\input plain
\input luatexiniconfig.tex
\input luatex85.sty
\input luaotfload.sty
\pdfpkresolution=600
\font\bitmap=file:cmb12.tfm:reencode=8r.enc;bitmap=yes
\bitmap test
\bye
```

But luatex show error:

```
luaotfload | main : initialization completed in 0.091 seconds)
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: "File not found: cmb12.".
! Font \bitmap=file:cmb12.tfm:reencode=8r.enc;bitmap=yes not loadable: metric d
ata not found or bad.
<to be read again> 
\bitmap 
l.6 \bitmap
          test
?
```

If I generate PDF document via pdftex first then luatex (when called after pdftex) can generate it too. It is becuase cmb12.tfm font metric is not preinstalled and pdftex calls mktextfm to generate it on demand (if not exist).

So looks like that luaotfload does not generate metric TFM files for MetaFont bitmap fonts automatically like pdftex.

Patch below do that, it automatically generate TFM metric files when needed.

I tried experimenting with function `kpse.lookup(filename, { format = "tfm", mktextfm = true }` but even if `mktextfm` was set to true, it did not called `mktextfm` and did not generated metric file...

```
--- a/src/luaotfload-database.lua
+++ b/src/luaotfload-database.lua
@@ -685,6 +685,11 @@ lookup_font_file = function (filename)
         if resolvers.findfile(filename, format) then
             return file.addsuffix(filename, format), format, true
         end
+        if type1_metrics[i] == "tfm" then
+            if os.execute("kpsewhich -format=tfm -mktex=tfm " .. filename) then
+                return file.addsuffix(filename, format), format, true
+            end
+        end
     end

     if not fonts_reloaded and config.luaotfload.db.update_live == true then
```

**Comment by phi-gamma** [comment]
Hi Pali, could you try with luatex 1.0.0?

**Comment by pali** [comment]
With luatex 1.0.0 whole luaotfload is broken...

```
This is LuaTeX, Version 1.0.0 (TeX Live 2017/dev/Debian)  (INITEX)
...
        FATAL ERROR
        Luaotfload requires a Luatex version >= 0.95.0.
        Please update your TeX distribution!
```

**Comment by pali** [comment]
With my patch for minimum version, problem is still there, I cannot load cmb12:
```
luaotfload | main : initialization completed in 0.091 seconds)
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: "File not found: cmb12.".
! Font \bitmap=file:cmb12.tfm:reencode=8r.enc;bitmap=yes not loadable: metric d
ata not found or bad.
<to be read again> 
\bitmap 
l.6 \bitmap
          test
?
```

**Comment by pali** [comment]
Update: luaotfload from current master branch (commit 9b4a3f094b8574b262d1636e9977c6a592399c0d) with LuaTeX version 1.0.0 (svn revision 6149) without any applied patch.

And problem is still there:
```
luaotfload | main : initialization completed in 0.091 seconds)
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: "File not found: cmb12.".
! Font \bitmap=file:cmb12.tfm:reencode=8r.enc;bitmap=yes not loadable: metric d
ata not found or bad.
<to be read again> 
\bitmap 
l.7 \bitmap
          test
? x
```

@phi-gamma: Can you look at it?

**Comment by pali** [comment]
@phi-gamma: Can you look at this problem?

**Comment by u-fischer** [comment]
this is not luaotfload related. see also https://github.com/u-fischer/luaotfload/issues/50
