### ISSUE TITLE
luaotfload seems not to recognize LuaTeX 1.0.0

### ISSUE THREAD

**Issue by eg9** [lualatex/luaotfload#387]
Running a document loading `luaotfload` with LuaTeX 1.0.0 seems to result in an error:

        FATAL ERROR
        Luaotfload requires a Luatex version >= 0.95.0.
        Please update your TeX distribution!

Reference: http://tex.stackexchange.com/questions/336875/bug-in-miktex-2-9-6147

**Comment by davidcarlisle** [comment]
see https://github.com/lualatex/luaotfload/issues/382

**Comment by davidcarlisle** [comment]
Although texlive won't be using 1.0 by default until tl2017 miktex is apparently already using it, so this will start to hit end users. Any chance of a ctan release if only for this?

**Comment by u-fischer** [comment]
As it starts to hit the miktex users here the work-around for miktex users until the package is updated officially:

Get the prerelease of luaotfload https://github.com/lualatex/luaotfload/releases. Use the `tds.zip`, unpack it somewhere outside miktex and add the root folder as a new root with miktex settings. When luaotfload is updated in miktex one can easily remove this root from miktex settings.

**Comment by brentpayton** [comment]
u-fischer,

I followed your instructions but still encountered the problem despite removing the luaotfload package with the MiKTex package manager.

1.  Download https://github.com/lualatex/luaotfload/releases/download/v2.8-rc3/luaotfload.tds.zip
2.  Extract files to some location outside of miktex (c:\luaotfload)
3.  Add c:\luaotfload to miktex roots.

**4.  The missing step appears to be renaming the folder C:\Users\$username\AppData\Local\Programs\MiKTeX 2.9\tex\luatex\luaotfload.**  In my case, I renamed it to luaotfload.bad.

**Comment by u-fischer** [comment]
@brentpayton you are right, I forgot that in a multiuser installation a luaotfload  installed by the package manager of the user is found first (I have a singleuser installation). In this case you should either deinstalll the package with the package manager or separate UserInstall and UserConfig, https://sourceforge.net/p/miktex/bugs/2534/

**Comment by davidcarlisle** [comment]
Hi pinging here again, could I ask for a ctan release fixing the version check so it can get to miktex and texlive by default? We are considering adjusting the default encoding for lualatex and xelatex to be Unicode, at the next release (nominally 1st January) but currently this issue would mean that lualatex doesn't wok at all with the distributed files. Thanks.

**Comment by davidcarlisle** [comment]
we hope to release latex 2017/01/01 this weekend, which loads luaotfload-main in everyjob, could I ask again if there is any progress towards a ctan release with the version check fixed?

a minimal change would be to just change the test to `if false` to disable the version check pending a full release,, if you've no time at present could you authorize such a change in ctan?

**Comment by phi-gamma** [comment]
New release is on its way to CTAN, sorry for the delay.
