### ISSUE TITLE
! error:  (linebreak): invalid list tail, probably missing glue

### ISSUE THREAD

**Issue by u-fischer** [lualatex/luaotfload#388]
With the following document

```
\listfiles
\documentclass{article}
\usepackage{luaotfload}
%\font\test={Cambria:mode=base;script=latn;language=DFLT;}
%\font\test={Calibri:mode=base;script=latn;language=DFLT;}
\font\test={SourceSansPro:mode=base;script=latn;language=DFLT;}
\begin{document}

 \test
   iltintin%iltintin %iltinba %atolkinti

\end{document}
```

I get the error 

```
! error:  (linebreak): invalid list tail, probably missing glue
!  ==> Fatal error occurred, no output PDF file produced!

```

I'm using a prerelease luaotfload (fontloader-2016-10-21.lua) together with `LuaTeX, Version 1.0.0 (MiKTeX 2.9.6100 NEXT)`.

With the luatex from texlive (LuaTeX, Version 0.95.0) and the same fontloader there is no problem.

The error is related to `mode=base`. I don't get it with all fonts but the three in the example all show it. It only appears for some combination of chars but I didn't find a understandable pattern.

I got the error also when using the context minimals fontloader, but couldn't reproduce it with context itself.

## Edit
It seems to be important that the problematic font with mode base is active at the end of a paragraph:
```

\documentclass{article}
\usepackage{luaotfload}

\font\testb={SourceSansPro:mode=node;script=latn;language=DFLT;}
\font\test={SourceSansPro:mode=base;script=latn;language=DFLT;}
\begin{document}

\test
   iltintin%iltintin %iltinba %atolkinti
%\par %uncomment to get the error
\testb b   


\end{document}
```

**Comment by phi-gamma** [comment]
I get some of these too under certain circumstances, even with the new loader.
The new release does not appear to fix it. I’ll look into it.

**Comment by phi-gamma** [comment]
2016-11-15 (Tuesday), notifications@github.com (u-fischer):

> I got the error also when using the context minimals
> fontloader, but couldn't reproduce it with context itself.

Tests for Plain and Context:

    https://bitbucket.org/phg/lua-la-tex-tests/src/tip/plain/pln-luatex-2-crash-kern-base.tex
    https://bitbucket.org/phg/lua-la-tex-tests/src/tip/context/cnt-luatex-2-crash-kern-base.tex

The latter seems worse in that ``mtxrun`` appears to hang.
Terminating it via SIGINT leaks the ``luatex`` process …
ugh.

**Comment by phi-gamma** [comment]
2017-02-03 (Friday), phg@phi-gamma.net (phg):

> 2016-11-15 (Tuesday), notifications@github.com (u-fischer):
> 
> > I got the error also when using the context minimals
> > fontloader, but couldn't reproduce it with context itself.
> 
> Tests for Plain and Context:
> 
>     https://bitbucket.org/phg/lua-la-tex-tests/src/tip/plain/pln-luatex-2-crash-kern-base.tex
>     https://bitbucket.org/phg/lua-la-tex-tests/src/tip/context/cnt-luatex-2-crash-kern-base.tex
> 
> The latter seems worse in that ``mtxrun`` appears to hang.
> Terminating it via SIGINT leaks the ``luatex`` process …
> ugh.
> 

Backtrace of Luatex hanging with Context:

    #0  0x0000000000581d09 in add_kern_before (left=1253, right=901) at ../../../source/texk/web2c/luatexdir/font/luafont.w:2035
    #1  0x00000000005821a9 in do_handle_kerning (root=2999, init_left=0, init_right=0)
        at ../../../source/texk/web2c/luatexdir/font/luafont.w:2076
    #2  0x0000000000582733 in handle_kerning (head=2999, tail=0) at ../../../source/texk/web2c/luatexdir/font/luafont.w:2132
    #3  0x000000000054d7a5 in font_tex_direct_kerning (L=0x2524de0) at ../../../source/texk/web2c/luatexdir/lua/lnodelib.c:4646
    #4  0x000000000070b2d7 in luaD_precall (L=0x2524de0, func=0x65fcfb0, nresults=1)
        at ../../../source/libs/lua52/lua52-src/src/ldo.c:319
    #5  0x0000000000723ad4 in luaV_execute (L=0x2524de0) at ../../../source/libs/lua52/lua52-src/src/lvm.c:709
    #6  0x000000000070b73e in luaD_call (L=0x2524de0, func=0x65fcd40, nResults=1, allowyield=0)
        at ../../../source/libs/lua52/lua52-src/src/ldo.c:402
    #7  0x0000000000702ba2 in f_call (L=0x2524de0, ud=0x7fff7db55ba0) at ../../../source/libs/lua52/lua52-src/src/lapi.c:923
    #8  0x000000000070a900 in luaD_rawrunprotected (L=0x2524de0, f=0x702b6b <f_call>, ud=0x7fff7db55ba0)
        at ../../../source/libs/lua52/lua52-src/src/ldo.c:131
    #9  0x000000000070bea5 in luaD_pcall (L=0x2524de0, func=0x702b6b <f_call>, u=0x7fff7db55ba0, old_top=416, ef=0)
        at ../../../source/libs/lua52/lua52-src/src/ldo.c:603
    #10 0x0000000000702c6e in lua_pcallk (L=0x2524de0, nargs=6, nresults=1, errfunc=0, ctx=0, k=0x0)
        at ../../../source/libs/lua52/lua52-src/src/lapi.c:949
    #11 0x00000000005b7412 in lua_hpack_filter (head_node=1313, size=0, pack_type=1, extrainfo=2, pack_direction=0, attr=794)
        at ../../../source/texk/web2c/luatexdir/lua/luanode.w:226
    #12 0x00000000004d650d in filtered_hpack (p=825, qt=1283, w=0, m=1, grp=2, pac=0, just_pack=0, attr=794)
        at ../../../source/texk/web2c/luatexdir/tex/packaging.w:1145
    #13 0x00000000004d7a4d in package (c=0) at ../../../source/texk/web2c/luatexdir/tex/packaging.w:1604
    #14 0x00000000004c8c5c in handle_right_brace () at ../../../source/texk/web2c/luatexdir/tex/maincontrol.w:1190
    #15 0x00000000004c8119 in main_control () at ../../../source/texk/web2c/luatexdir/tex/maincontrol.w:910
    #16 0x00000000004c4902 in main_body () at ../../../source/texk/web2c/luatexdir/tex/mainbody.w:460
    #17 0x000000000048be55 in main (ac=11, av=0x7fff7db55e08) at ../../../source/texk/web2c/luatexdir/luatex.c:579

**Comment by phi-gamma** [comment]
This particular crash should be fixed by this patch:
https://github.com/phi-gamma/luaotfload/commit/94649446c7d25187901b396845067dc7d8b7d61d

But there’s at least one similar, equally fatal crash out there
that occurs in node mode.

**Comment by u-fischer** [comment]
I installed some days ago luatex version 1.0.4 (from w32tex.org) and with it the error seems to be gone. The code compiles with the default fontloader and a current context fontloader.

**Comment by u-fischer** [comment]
Closing as it is resolved in newer version.
