### ISSUE TITLE
optical size choice: wrong point unit used

### ISSUE THREAD

**Issue by eroux** [lualatex/luaotfload#389]
Following [this bug report](https://sourceforge.net/p/xetex/bugs/136/) on the XeTeX tracker, it seems that the wrong point unit is used when selecting the optical size because the indications given in the font are interpreted as given in `pt` while they should be interpreted as given in `bp` (see the XeTeX bug report for more info).

For instance the example

```tex
\input luaotfload.sty
\font\rm="Arno Pro" at 13.99bp \rm
Hello, world!\bye
```

will choose the `Subhead` version while it should choose the `Regular` one (the "top" range for regular being 14 and the bottom range for subhead being 14 too). I didn't manage to find an example of free font with multiple optical sizes...

**Comment by phi-gamma** [comment]
There’s a config option now that allows to choose from ``bp``, ``pt``, and ``dd``
with ``bp`` being the default.

**Comment by eroux** [comment]
Thanks a lot!

**Comment by ArchangeGabriel** [comment]
Just for the record, a free font with multiple optical sizes could be https://github.com/georgd/EB-Garamond. There are 8 and 12 pt sizes available. ;)
