### ISSUE TITLE
Error in fontloader-2016-06-16.lua.

### ISSUE THREAD

**Issue by ijaradnam** [lualatex/luaotfload#391]
I am using texlive2016 lualatex.
With the following document
```
\documentclass[b5paper]{article}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}
\newfontfamily\siddham[Script=Devanagari]{Muktamsiddham}
\begin{document}
{\siddham ओं अमोघवैरोचन महामुद्र मणिपद्मज्वल प्रवर्तय हूं}\\
\end{document}
```
I got the error
`fontloader-2016-06-16.lua:9010: invalid value (table) at index 2 in table for 'concat'.`.

The font is obtained from
`https://github.com/MihailJP/Muktamsiddham`.

**Comment by phi-gamma** [comment]
Please retest. The new release should be on CTAN any minute.

Btw. I couldn’t get that font to build from the repo because it makes
my Fontforge crash. Do you happen to know where I can download
a TTF or OTF? Thanks!

**Comment by ijaradnam** [comment]
Thanks for reply!

You can get the font from https://drive.google.com/drive/folders/0B_UdxS5ZFxZQd0J1am1GY3AwRmM .

**Comment by ijaradnam** [comment]
I tried the new version, but I got the same error.

`fontloader-2017-01-29.lua:9007:invalid value (table) at index 2 in table for 'concat'.`

**Comment by phi-gamma** [comment]
2017-01-31 (Tuesday), notifications@github.com (ijaradnam):

> I tried the new version, but I got the same error.
> 
> `fontloader-2017-01-29.lua:9007:invalid value (table) at index 2 in table for 'concat'.`

Can be reproduced with the loader. Apparently the font parsing
completes but the subsequent attempt to load the tables crashes.
I’ll file a report with Hans.

Btw. that file seems to be buggy to begin with and the loader
complains *loudly* about that:

    ▶ mtxrun --script fonts --convert Muktamsiddham.otf 
    
    otf reader      | found cmaps:
    otf reader      |   platform 0: unicode
    otf reader      |     encoding 3: unicode 2.0 bmp
    otf reader      |       formats: 4
    otf reader      |   platform 1: macintosh (unsupported)
    otf reader      |     encoding 0: roman (unsupported)
    otf reader      |       formats: 6 (unsupported)
    otf reader      |   platform 3: windows
    otf reader      |     encoding 1: unicode bmp
    otf reader      |       formats: 4
    otf reader      | cmap checked: platform 3 (windows), encoding 1 (unicode bmp), format 4, new unicodes 535
    otf reader      | cmap checked: platform 0 (unicode), encoding 3 (unicode 2.0 bmp), format 4, new unicodes 0
    otf reader      | not unicoded: DDa.0001 DNa.0001 Dga.0001 DhNa.0001 Dhma.0001 Dhna.0001 Dhva.0001 Dma.0001 Dna.0001 Dva.0001 GNa.0001 GSa.0001 Gga.0001 Ggha.0001 GkSa.0001 GkSva.0001 Gka.0001 Gkha.0001 Gkta.0001 Gma.0001 Gna.0001 Gsa.0001 Gva.0001 Gza.0001 JNa.0001 Jca.0001 Jcha.0001 Jja.0001 Jjha.0001 Jma.0001 Jna.0001 Jva.0001 Jza.0001 Jzva.0001 NDa.0001 NDva.0001 NNa.0001 Nma.0001 Nna.0001 Nva.0001 SNa.0001 STva.0001 Ska.0001 Skva.0001 Sma.0001 Sna.0001 Spa.0001 Sva.0001 TNa.0001 TSa.0001 TScha.0001 ThNa.0001 Thma.0001 Thna.0001 Thva.0001 Tka.0001 Tma.0001 Tna.0001 Tva.0001 Tza.0001 bNa.0001 bba.0001 bbha.0001 bda.0001 bdha.0001 bdhva.0001 bhNa.0001 bhma.0001 bhna.0001 bhva.0001 bja.0001 bma.0001 bna.0001 bva.0001 cJa.0001 cNa.0001 cca.0001 ccha.0001 cchva.0001 chNa.0001 chma.0001 chna.0001 chva.0001 cma.0001 cna.0001 cva.0001 dDa.0001 dNa.0001 dba.0001 dbha.0001 dda.0001 ddha.0001 ddhma.0001 ddhna.0001 ddhva.0001 ddva.0001 dga.0001 dgha.0001 dhNa.0001 dhma.0001 dhna.0001 dhva.0001 dma.0001 dna.0001 dsva.0001 dva.0001 gNa.0001 gbha.0001 gda.0001 gdha.0001 gdhva.0001 gga.0001 ghNa.0001 ghma.0001 ghna.0001 ghva.0001 gja.0001 gma.0001 gna.0001 gva.0001 hNa.0001 hma.0001 hna.0001 hva.0001 jJa.0001 jNa.0001 jhNa.0001 jhma.0001 jhna.0001 jhva.0001 jjJa.0001 jja.0001 jjha.0001 jjva.0001 jma.0001 jna.0001 jva.0001 kNa.0001 kSNa.0001 kSa.0001 kSma.0001 kSna.0001 kSva.0001 kca.0001 khNa.0001 khma.0001 khna.0001 khva.0001 kka.0001 kkha.0001 kma.0001 kna.0001 kpa.0001 ksa.0001 kta.0001 ktha.0001 ktva.0001 kva.0001 kza.0001 lNa.0001 lba.0001 lda.0001 lga.0001 lka.0001 lma.0001 lna.0001 lpa.0001 lta.0001 lva.0001 mNa.0001 mba.0001 mbha.0001 mma.0001 mna.0001 mpa.0001 mva.0001 nNa.0001 nba.0001 nbha.0001 nda.0001 ndda.0001 nddha.0001 ndha.0001 ndva.0001 nga.0001 nka.0001 nma.0001 nna.0001 npa.0001 nsa.0001 nspa.0001 nstha.0001 nsva.0001 nta.0001 ntha.0001 ntsa.0001 nva.0001 nza.0001 pNa.0001 phNa.0001 phma.0001 phna.0001 phva.0001 pma.0001 pna.0001 ppa.0001 psa.0001 pta.0001 ptva.0001 pva.0001 sNa.0001 ska.0001 skha.0001 sma.0001 sna.0001 spa.0001 sta.0001 stha.0001 stva.0001 sva.0001 tNa.0001 thNa.0001 thma.0001 thna.0001 thva.0001 tkSa.0001 tka.0001 tkha.0001 tkva.0001 tma.0001 tna.0001 tpa.0001 tsa.0001 tsma.0001 tsna.0001 tstha.0001 tsva.0001 tta.0001 ttha.0001 ttna.0001 ttva.0001 tva.0001 vNa.0001 vca.0001 vcha.0001 vda.0001 vdha.0001 vja.0001 vjha.0001 vkSa.0001 vma.0001 vna.0001 vva.0001 yNa.0001 yma.0001 yna.0001 yva.0001 zNa.0001 zba.0001 zca.0001 zcha.0001 zma.0001 zna.0001 zva.0001
    otf reader      | 834 base class tags removed (default is base)
    mtx-fonts       | font: 'Muktamsiddham.otf' saved as 'muktamsiddham.lua'

I agree though that it shouldn’t crash.
Philipp

**Comment by ijaradnam** [comment]
Thank you! This issue is fixed.
