### ISSUE TITLE
Ligatures for the reverted Spanish question/exclamation marks do not work

### ISSUE THREAD

**Issue by svitalsky** [lualatex/luaotfload#405]
After the fix for the issue #397 (typographic (UTF-8) quotes making ligatures with exclamation and question marks) now the standard ligatures "?\`" and "!\`" do NOT work, so that this MWE:
```
\documentclass[a4paper, 12pt]{article}
\begin{document}
Hi?`

Hi!`
\end{document}
```

gives different results with LuaTeX (standard q./ex. marks followed by back quote) and with XeTeX or pdfTeX (reverted Spanish q./ex. marks).

**Comment by eg9** [comment]
The removal of ligatures in `luaotfload-features.lua` has been too drastic and should be reconsidered.

**Comment by svitalsky** [comment]
I don't “speak Lua” so I may be totally wrong but it seems to me that only lines 1291 to 1294 should be removed and the rest (1305–1317) should be kept.

**Comment by u-fischer** [comment]
closing as ligatures works as expected now.
