### ISSUE TITLE
contextual substitution is not working.

### ISSUE THREAD

**Issue by ijaradnam** [lualatex/luaotfload#406]
The half glyphs and the phonetic signs are not substituted correctly. An example is as follows.
```
\documentclass[a4paper]{article}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}
\newfontfamily\siddham[Script=Devanagari]{Muktamsiddham}
\begin{document}
{\siddham काङाजाञारुलुहुकुखुगु}
\end{document}
```
xelatex, of course, outputs correctly.

**Comment by phi-gamma** [comment]
2017-02-08 (Wednesday), notifications@github.com (ijaradnam):

> The half glyphs and the phonetic signs are not substituted correctly. An example is as follows.

> \newfontfamily\siddham[Script=Devanagari]{Muktamsiddham}

The Devanagari specific code comes with a few caveats:
https://bitbucket.org/phg/context-mirror/src/beta/tex/context/base/mkiv/font-osd.lua#font-osd.lua-9

Since it’s still WIP I suggest you take this to the Context
mailing list.

Best,
Philipp

**Comment by u-fischer** [comment]
Could you please try with the development files in the texmf-tree here https://github.com/u-fischer/luaotfload/tree/dev? It improves devanagari greatly. See also https://github.com/u-fischer/luaotfload/issues/9.

To test you can download the whole texmf and activate it in a current texlive with 

`tlmgr conf auxtrees add path/to/texmf` .

**Comment by ijaradnam** [comment]
I tried the development version. The problems are solved much more than in past editions. I appreciate the wonderful work. However, I have found some problems.
1. In ArialUnicodeMS, vowel "i" may change to "iM".
Below is a bug in my own siddham font [https://www.mandaraji.jp/bonji/Fonts/AfeySiddham.otf](url)
2. Ligatures ending with "yu", "yU" can not be output correctly.
3. Vowel symbol "I" can not cope with character change of the parent character with ligatures such as "kyI", "ngI", "nzI".
These three points are correctly displayed on xelatex.

Example.
```
\documentclass[a4paper]{article}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}
\newfontfamily\siddham[Script=Devanagari]{AfeySiddham}
\begin{document}
{\siddham ज्यज्याज्यिज्यीज्युज्यूज्येज्यैज्योज्यौज्यंज्यः\\
म्युम्यूब्युब्यूक्युक्यू\\क्यीख्यी\\न्गन्गिन्गी\\
}
\end{document}
```

**Comment by u-fischer** [comment]
I moved the report about afeysiddham to https://github.com/u-fischer/luaotfload/issues/13 and will close here. I didn't know how to describe the ArialUnicodeMS problem. Please add an new issue about it at my github site in a similar way I did for your font. Please take in mind that I know nothing about the script and don't know what are the vowels  etc ;-).
