### ISSUE TITLE
accessing glyphs after tlig feature substitution.

### ISSUE THREAD

**Issue by davidcarlisle** [lualatex/luaotfload#409]
We are trying to enable the standard latex commands `\textquotesingle` and `\textquotedouble` for straight  single and double quotes. this could just be `\char"27` and `\char"22` except that by default (or by choice at font loading) the tlig feature has mapped these to the right quotation marks.

The test file below works with lualatex and xelatex but does so by taking the \fontname of the loaded font stripping off any `+tlig;` and then reloading the font, which works but seems a bit excessive just to access a single character.

With xetex can instead do

```

\XeTeXglyph\XeTeXcharglyph`\'
```

which accesses the straight quote  `'` even if the tex-ligatures mapping is in place.

Is there (or could there be) a convenient way to access this glyph with luaotfload, or is re-loading the font the best way?

```
\documentclass{article}

% Trying other fonts..
%\usepackage{fontspec}
%\setmainfont{Times New Roman}

\makeatletter
\ifx\directlua\@undefined
  \edef\remove@@tlig{\detokenize{mapping=tex-text;}}
\else
  \edef\remove@@tlig{\detokenize{+tlig;}}
\fi

\def\reserved@a#1{%
  \def\@remove@tlig##1{\@remove@tlig@##1\@nil#1\@nil\relax}
  \def\@remove@tlig@##1#1{\@remove@tlig@@##1}}
\expandafter\reserved@a\expandafter{\remove@@tlig}
\def\@remove@tlig@@#1\@nil#2\relax{#1}

\def\remove@tlig#1{%
\begingroup
\font\reserved@a
 \expandafter\@remove@tlig\expandafter{\fontname\font}%
 \reserved@a
 \char#1\relax
 \endgroup
}

\ifx\directlua\@undefined

\DeclareTextCommand\textquotesingle{TU}{\XeTeXglyph\XeTeXcharglyph`\'}
\DeclareTextCommand\textasciigrave{TU}{\XeTeXglyph\XeTeXcharglyph`\`}
\DeclareTextCommand\textquotedbl{TU}{\XeTeXglyph\XeTeXcharglyph`\"}

\else

\DeclareTextCommand\textquotesingle{TU}{\remove@tlig{`\'}}
\DeclareTextCommand\textasciigrave{TU}{\remove@tlig{`\`}}
\DeclareTextCommand\textquotedbl{TU}{\remove@tlig{`\"}}

\fi

\begin{document}

\typeout{\fontname\font}

`hello\textquotesingle there'

`hello\textasciigrave there'

``hello\textquotedbl there''

``hello\textquotedbl there" %hmm


\Huge
\typeout{\fontname\font}

`hello\textquotesingle there'

`hello\textasciigrave there'

``hello\textquotedbl there''

``hello\textquotedbl there" %hmm


\end{document}
```

**Comment by khaledhosny** [comment]
Note that using `\XeTeXglyph` in XeTeX will prevent any kerning or other font features between the inserted glyph and the text around it, which might not be desired.

**Comment by u-fischer** [comment]
Moved to https://github.com/latex3/latex2e/issues/165.
