### ISSUE TITLE
Bad glyph positioning inside \hbox

### ISSUE THREAD

**Issue by khaledhosny** [lualatex/luaotfload#410]
In the following example, the rightmost is shifted a few glyphs to the left when inside an `\hbox`. No issue with XeTeX.
```tex
\ifdefined\directlua                                                            
  \textdir TRT                                                                  
  \def\rlbox#1{\hbox dir TRT {#1}}                                              
  \input luaotfload.sty                                                         
\else                                                                           
  \let\rlbox=\hbox                                                              
\fi                                                                             
\font\amiri="Amiri:script=arab" at 80pt                                         
\amiri                                                                          
محيط\par                                                                        
\leavevmode\rlbox{محيط}                                                         
\bye
```

![image](https://cloud.githubusercontent.com/assets/93914/23373874/85979d26-fd2a-11e6-9db0-1d95f71bca20.png)

**Comment by u-fischer** [comment]
I can reproduce the problem.

The good news are that with a development version of luatex (This is LuaTeX, Version 1.0.4) **and** the newest fontloader from the context minimals (I load it in my luaotfload.conf with `fontloader= context:D:/context-minimals/context/tex/texmf-context` ) in the following document the output in and outside the box is identical. The bad news is that it looks as if now all three versions are wrong (but as I don't know arabic I'm not sure). The context output looks completly wrong. I don't have other arabic fonts which I could use for tests to decide if it is a fault specific to amiri.

(I use the ^^^-notation as real right-to-left is to confusing)

```

\documentclass{article}

\begin{document}
\textdir TRT

\font\amiri={file:amiri-regular.ttf:script=arab} at 80pt
\amiri

^^^^0637 ^^^^0645^^^^062d^^^^064a^^^^0637\par

\leavevmode\hbox dir TRT {^^^^0637 ^^^^0645^^^^062d^^^^064a^^^^0637}   

\vbox dir TRT {^^^^0637 ^^^^0645^^^^062d^^^^064a^^^^0637}   

\end{document}
```

![amiri](https://cloud.githubusercontent.com/assets/4047173/23471547/019a36ba-feaa-11e6-86e6-1408ed8909fd.PNG)

**Comment by khaledhosny** [comment]
Yes, they are all equally wrong now. My guess is that the horizontal glyph movement went in the other (wrong) direction.

**Comment by khaledhosny** [comment]
The issue seems to be related to the use of OpenType cursive anchors. The same example using “Noto Nastaliq Urdu” is completely broken as well:
![luatex](https://cloud.githubusercontent.com/assets/93914/23472284/005c0b1a-feb5-11e6-8063-9e0ca43ea819.png)
compared to XeTeX output:
![xetex](https://cloud.githubusercontent.com/assets/93914/23472325/1e80be6a-feb5-11e6-8100-f41e1372fc03.png)

**Comment by u-fischer** [comment]
Imho you should move the issue to the luatex list. It looks like an engine problem. With miktex (which has luatex 1.0.0) the output is wrong only in the hbox. In both cases I used the same (context) fontloader. So something happened between 1.0.0. and 1.0.4.

**Comment by khaledhosny** [comment]
Might be an engine issue indeed, adding `\textdir TRT` inside the box fixes the issue. That is a good enough workaround for me.

**Comment by u-fischer** [comment]
But not in the long run. When I add  in my development system or in miktex `\textdir TRT` in the hbox then the content disappears. You should really better inform the luatex maintainers if you don't want that it breaks in the upcomming texlive 2017.
