### ISSUE TITLE
.notdef glyph embedded, even when no undefined characters

### ISSUE THREAD

**Issue by ghost** [lualatex/luaotfload#411]
I first mentioned this at fontspec, but it does not originate there. Perhaps luaotfload?

Most Open Type fonts have a visible glyph (often a crossed box) for the .notdef slot. A few fonts simply leave .notdef as a blank glyph, either the width of a space or the width of em.

Issue: If the font has a visible .notdef glyph, it is placed in the PDF, whether or not it is needed. MWE:

% !TeX program = LuaLaTeX
% !TeX encoding = UTF-8
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Linux Libertine O}
\begin{document}
\thispagestyle{empty}
a\par
\end{document}

If you extract the font from the PDF using FontForge, you will see that it contains exactly two glyphs: The letter a, and the .notdef box, even though there is no undefined character in the file. Font "Linux Libertine O" has a crossed-box .notdef glyph.

For comparison, comment-out \setmainfont, so that the default "Latin Modern Roman" is used instead. This font has a blank .notdef. When you extract the font from the PDF, there is no .notdef glyph there, not even a blank.

In other words: The presence of a non-blank .notdef causes that glyph to be embedded in the PDF, even if it is unused and no characters refer to it.

Why this might be a problem: In PDF/X and PDF/A, any reference to .notdef is prohibited, because the PDF is not allowed to have missing characters. Even though there is no reference, the presence of .notdef may mislead a reviewer into thinking that it is used.

**Comment by u-fischer** [comment]
I don't think that the problem is still there. Please check if the problem still persists in the newest luaotfload (texlive 2019, 2.99). If yes reopen the issue at  https://github.com/u-fischer/luaotfload/.
