### ISSUE TITLE
Ability to query luaotfload database/resolver for fonts

### ISSUE THREAD

**Issue by deepakjois** [lualatex/luaotfload#413]
This request is slightly related to [my comment here](https://github.com/lualatex/luaotfload/issues/314#issuecomment-167118688).

I have a working prototype of a LuaTeX node processor that does BiDi processing according to [UAX #9](http://unicode.org/reports/tr9/), and then uses Harfbuzz to shape the text.

I have a custom callback defined on `pre_linebreak_filter` and `hpack_filter` that does the processing. I would like to use the luaotfload database to parse the font specification and resolve it to a font file, without invoking any of the callback code (or disable it so that I can use my own callbacks instead).

Ideally, I would like to do something like:

```lua
local luaotfload = require("luaotfload")

-- a bit like luaotfload-tool --find=<…font name or file name…> 
local font = luaotfload.find_font("…<font name or filename>…") 

if font then print("FOUND") else print("NOT FOUND") end
```

* Is this possible already?
* Is exposing this functionality desirable from your perspective?
* If I were to try implementing it…what would be a good place to start making changes to the code?

**Comment by wspr** [comment]
I guess a TeX-based solution is out of the question? This is done in fontspec using something along the lines of

    \luatexsuppressfontnotfounderror
    \font\x=“[somefont.otf]” at 12pt\relax
    \ifx\x\nullfont
      % font not found
    \fi

(off the top of my head — there could be typos…)

**Comment by deepakjois** [comment]
On Mon, May 22, 2017 at 8:37 AM, Will Robertson <notifications@github.com>
wrote:

> I guess a TeX-based solution is out of the question? This is done in
> fontspec using something along the lines of
>

Well…I am not sure. I guess it might work if I can somehow hook it up with
Lua.


>
> \luatexsuppressfontnotfounderror
> \font\x=“[somefont.otf]” at 12pt\relax
> \ifx\x\nullfont
> % font not found
> \fi
>
> (off the top of my head — there could be typos…)
>
>
Thank you. I will try out something like this for now.

I would still request for a API based solution for this. I think there is a
good case for the font querying functionality of luaotfload to be exposed
for other libraries to use. It would save me (and potentially others) from
writing my own font parser, font cache and db etc. in the long run.

**Comment by wspr** [comment]
I agree — I’m not a luaotfload developer (well, I might have contributed in a very minor way early on) so I can only recommend a short-term workaround :)

**Comment by u-fischer** [comment]
Î'm closing the issue here but added a reference at https://github.com/u-fischer/luaotfload/issues/87.
