### ISSUE TITLE
luaotfload and luatex --safer

### ISSUE THREAD

**Issue by davidcarlisle** [lualatex/luaotfload#416]
If lualatex is used with the `--safer` option as in

`lualatex --safer sample2e`

Then the result is not so good:

```
This is LuaTeX, Version 1.0.5 (TeX Live 2017) 
 restricted system commands enabled.
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/sample2e.tex
LaTeX2e <2017-04-15>


luaotfload | load : FATAL ERROR
luaotfload | load :   × Failed to load module "fontloader-basics-gen.lua".
luaotfload | load :   × Error message:
luaotfload | load :     × "...live/2017/texmf-dist/tex/luatex/lualibs/lualibs-file.lua:341: attempt to call field 'open' (a nil value)".

stack traceback:
        ...017/texmf-dist/tex/luatex/luaotfload/luaotfload-main.lua:159: in function 'fontloader'
        ...017/texmf-dist/tex/luatex/luaotfload/luaotfload-init.lua:176: in function 'early'
        ...017/texmf-dist/tex/luatex/luaotfload/luaotfload-main.lua:268: in function 'main'
        [\directlua]:1: in main chunk
```

luaotfload probably can't work with `--safer` but could it detect that and do nothing, with a warning,  rather than accessing undefined fields and stopping with a stack trace?

Alternatively I suppose latex could detect this in everyjob and not load luaotfload in that case but
it might be better if the test was inside the main luaotfload code so is there however it gets loaded, not just via latex `\everyjob`

**Comment by u-fischer** [comment]
The error message is now (?) or on windows better:

~~~~
G:\Z-Test>lualatex --safer test-utf8
This is LuaTeX, Version 1.07.0 (TeX Live 2018/W32TeX)
 restricted system commands enabled.
(./test-utf8.tex
LaTeX2e <2018-04-01> patch level 5

safer option set, function "io.open" is limited
~~~~

But it would be certainly better to test this in luaotfload-main.lua. I added an issue https://github.com/u-fischer/luaotfload/issues/12

**Comment by u-fischer** [comment]
This will be resolved with the next version. The code is already in the development branch on https://github.com/u-fischer/luaotfload
