### ISSUE TITLE
wrong radix for \sqrt

### ISSUE THREAD

**Issue by hvoss49** [lualatex/luaotfload#419]
With xelatex everything is fine, with lualatex the 3 is set completely wrong.  
Compare [xelatex](http://hvoss.org/xelatex.png) and [lualatex](http://hvoss.org/lualatex.png). It happens for all math fonts

```
\listfiles
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{texgyredejavu-math.otf}
\begin{document}
$\sqrt[3]{\frac1n}$
\end{document}
```

up-to-date TL 2017

**Comment by u-fischer** [comment]
This was a passing bug in unicode-math. After the last update it works fine again.
