### ISSUE TITLE
Explicitely loading of bitmap font does not work

### ISSUE THREAD

**Issue by pali** [lualatex/luaotfload#421]
Simple tex file:
```
\input plain
\input luatexiniconfig.tex
\input luatex85.sty
\input luaotfload.sty
\pdfpkresolution=600
\font\bitmap=file:cmr10.tfm:reencode=8a.enc;bitmap=yes
\bitmap test
\bye
```
Bitmap font is explicitely requested, but in luatex log can be found that cmr10.pfb file is used. Also pdffonts say that final PDF file has Type 1 (and not Type 3).

**Comment by pali** [comment]
@u-fischer: Can you look at this problem?

**Comment by u-fischer** [comment]
Can you please add an issue to https://github.com/u-fischer/luaotfload/issues.  (But I must say that I don't quite understand why you want to force bitmaps).

**Comment by pali** [comment]
> But I must say that I don't quite understand why you want to force bitmaps.

2 reasons:

1) Use of bitmap version of font specially prepared (via metafont) for facsimile as fax format has rectangular pixels (in both Standard and Fine resolutions). Really all vector fonts are not prepared for such thing and metafont has parameters for configuring that output device has rectangular pixels (and not square).

2) Testing purpose, compare font which has two formats (bitmap/metafont and T1 vector) what is better for printed documents.

**Comment by pali** [comment]
> Can you please add an issue to https://github.com/u-fischer/luaotfload/issues.

Done: https://github.com/u-fischer/luaotfload/issues/50

**Comment by u-fischer** [comment]
closed,  see https://github.com/u-fischer/luaotfload/issues/50
