### ISSUE TITLE
difficulty using versions of fonts other than those provided by TeX Live

### ISSUE THREAD

**Issue by mewtant** [lualatex/luaotfload#422]
Since TeX Live 2018, `luaotfload` uses the fonts supplied by TeX Live rather than any newer or corrected versions one may keep in `/home/username/.fonts`. There’s an extended discussion of this at [tex.stackexchange.com](https://tex.stackexchange.com/q/434273), with a proposed patch by Marcel Krüger.

**Comment by mewtant** [comment]
See also the discussion at <https://github.com/u-fischer/lua-font-pond/issues/5>

**Comment by u-fischer** [comment]
the discussion has been moved to https://github.com/u-fischer/luaotfload/issues/84. I'm closing the issue here.
