### ISSUE TITLE
.luc files touched during compilation for no apparent reason

### ISSUE THREAD

**Issue by ysalmon** [lualatex/luaotfload#425]
I stumbled on a problem where latexmk would endlessly compile the following document
```latex
\documentclass{article}
\usepackage{fontspec}
\setmonofont{Source Code Pro}
\begin{document}
gh
\end{document}
```
The problem does not occur on the first compilation (more precisely : if there is not a .aux file left from a previous compilation) or if ``luaotfload-tool --cache=erase`` is executed just prior to re-compiling.

latexmk reports that
```
Changed files, or newly in use since previous run(s):
      '/opt/yann/texlive/2018/texmf-var/luatex-cache/generic/fonts/otl/sourcecodepro-boldit.luc'
      '/opt/yann/texlive/2018/texmf-var/luatex-cache/generic/fonts/otl/sourcecodepro-regular.luc'
```
and indeed, these files are both modified : their md5 sum changes.

A workaround is to instruct latexmk to ignore changes to .luc files, but the whole things still looks very strange. As seems strange that latexmk seems to not be bothered by this change of .luc file when an .aux file is not present in the compilation directory.

This bears resemblance to #375, except I have write access to the whole texlive directories.

Attached is the log file (it remains the same whether the problem arises or not).
[test.log](https://github.com/lualatex/luaotfload/files/2875106/test.log)

**Comment by u-fischer** [comment]
has been moved to https://github.com/u-fischer/luaotfload/issues/40.
