### ISSUE TITLE
update of alt_getopt on CTAN?

### ISSUE THREAD

**Issue by eroux** [lualatex/luaotfload#44]
Reading https://github.com/lualatex/lualatex-doc, I've seen that alt-getopt has been updated [here](https://github.com/LuaDist/alt-getopt) , maybe it could be updated on CTAN and we should test with the new scripts in luaotfload?

We can do that after the TeXLive 2013 release of course, just a reminder...

**Comment by phi-gamma** [comment]
I grepped my TL tree: It would appear that we’re the only
users of the module. Since we’re quite fine with it as-is and
there’s noone else to care, I think we can safely suspend
the issue.
