### ISSUE TITLE
font size bug with Prospero font

### ISSUE THREAD

**Issue by eroux** [lualatex/luaotfload#93]
The prospero font (http://norgz.guiling.fr/PRSPRORG.TTF, link to be dead soon) was working well under TeXLive 2012 but has a size problem with the last (and certainly previous) updates of TeXLive 2013.

MWE :

```
\documentclass[11pt]{minimal}
\usepackage{luaotfload}
\font\prospero=Prospero
\begin{document}
\prospero test prospero
\end{document}
```

It looks a bit as if luaotfload was reading it well, but was giving a wrong size value at font inclusion stage... The font might not be bug-free, but it used to work so I guess it's still doable?

I have problems with kpathsea right now: it doesn't consider files in current directory as prioritary compared to other ones, I'll bugreport that, but in the meantime, it's difficult to test with something other than TeXLive 2013...

**Comment by u-fischer** [comment]
I'm closing this as impossible to reproduce now after 5 years. If the problem still exists please open a new issue as https://github.com/u-fischer/luaotfload/issues/.
